In [1]:
import os
from langchain_openai import AzureOpenAIEmbeddings
from langchain.chains import RetrievalQAWithSourcesChain
import pandas as pd
from langchain_pinecone import PineconeVectorStore
from pinecone import Pinecone as pi
from langchain.vectorstores import Pinecone as PC
from langchain.schema import Document
import pickle
from langchain.retrievers import BM25Retriever, EnsembleRetriever
from typing import List,Tuple
from langchain.prompts import ChatPromptTemplate
from langchain_databricks import ChatDatabricks
import json,asyncio,math

/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pinecone/data/index.py:1: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from tqdm.autonotebook import tqdm

## Mapping data with metadata attached

### Load Mapping Data

In [2]:
# df = pd.read_excel("PPA side by Side 7_29 (1) (2).xlsx",sheet_name="side by side")

import openpyxl

workbook = openpyxl.load_workbook("/home/ec2-user/Pepsico_Hackathon/Pepsico_Main_Hackathon/Pepsico_demo_new_gen_mapping_approach/mapping_assistant/assistant_common/Mosaic-ER Diagram.xlsx", data_only=True)
sheet = workbook["Topline Metadata"]

# Create a dictionary to store merged cell information
merged_cells = {}

# Loop through merged cell ranges
for merged_range in sheet.merged_cells.ranges:
    # Get the top-left cell's value
    start_cell = sheet.cell(merged_range.min_row, merged_range.min_col)
    value = start_cell.value

    # Extract coordinates of merged cells
    for row in range(merged_range.min_row, merged_range.max_row + 1):
        for col in range(merged_range.min_col, merged_range.max_col + 1):
            merged_cells[(row, col)] = value


# Create a list of rows
data = []
for row in sheet.iter_rows(values_only=True):
    data.append(list(row))

# Fill merged cells using the dictionary
for (row, col), value in merged_cells.items():
    data[row - 1][col - 1] = value  # Adjusting for zero-based indexing

# Convert to a DataFrame
df = pd.DataFrame(data[1:], columns=data[0])
df.head()
# doc_list=[]
# for i,row in df.iterrows():

#     row_dict= {col:row[col] for col in df.columns if col!="Explanation"}

#     doc_object = Document(page_content=row["Explanation"], metadata=row_dict)
#     doc_list.append(doc_object)
# print(doc_list)

,Topline Metadata,OPEX Metadata,Topline ER Diagram,OPEX ER Diagram,Relationship,None,None
0,None,None,None,None,None,None,None
1,Dim_Customer,Dim_Customer,Dim_Customer,None,Dim_SalesGeo,Dim_SalesGeo,Dim_SalesGeo
2,Column,Type,Description,None,Column,Type,Description
3,CUST_HASH_CMPST_KEY,Bigint,"Represents the Customer Hash Composite Key, a ...",None,SLS_GEO_HASH_CMPST_KEY,Bigint,Represents a unique hashed composite key that ...
4,MU,String,The Business Unit break-down within a Cluster,None,SYS_ID,Int,None

In [3]:
df.head(20)

,Topline Metadata,OPEX Metadata,Topline ER Diagram,OPEX ER Diagram,Relationship,None,None
0,None,None,None,None,None,None,None
1,Dim_Customer,Dim_Customer,Dim_Customer,None,Dim_SalesGeo,Dim_SalesGeo,Dim_SalesGeo
2,Column,Type,Description,None,Column,Type,Description
3,CUST_HASH_CMPST_KEY,Bigint,"Represents the Customer Hash Composite Key, a ...",None,SLS_GEO_HASH_CMPST_KEY,Bigint,Represents a unique hashed composite key that ...
4,MU,String,The Business Unit break-down within a Cluster,None,SYS_ID,Int,None
5,BU,String,The Market Unit break-down within a Business Unit,None,SUB_SYS_ID,String,None
6,HRMNZD_CUST_GRPNG_NM,String,None,None,CTRY_ISO_CDV,String,None
7,CSTM_HRCHY_LVL_1_NM,String,None,None,LFL_FLG,String,The Like for Like flag. Like for Like refers t...
8,CUST_LOCL_ATRBT_2_NM,String,None,None,RGN,String,Strategic Cluster. It classifies for Beverages...
9,CUST_LOCL_ATRBT_3_NM,String,None,None,CLSTR,String,The Cluster break-down within a Sector
10,CUST_LOCL_ATRBT_4_NM,String,None,None,SCTR,String,The highest level functional organizational st...
11,datetime,Timestamp,"Represents the Timestamp, marking when the rec...",None,datetime,Timestamp,"Represents the Timestamp, marking when the rec..."
12,None,None,None,None,None,None,None
13,None,None,None,None,None,None,None
14,Dim_Finance,Dim_Finance,Dim_Finance,None,Dim_Time,Dim_Time,Dim_Time
15,Column,Type,Description,None,Column,Type,Description
16,FINC_HASH_CMPST_KEY,Bigint,"Stands for Finance Hash Composite Key, a hashe...",None,TME_HASH_CMPST_KEY,Bigint,Represents a unique hashed composite key for i...
17,BU_ACCT_LVL_1,String,"The highest level in the Account Hierarchy, th...",None,YR,Int,None
18,BU_ACCT_LVL_2,String,The subtype of the Account Level 1 that furthe...,None,QRTR,String,"The calendar Quarter within a Year, Q1 through..."
19,BU_ACCT_LVL_3,String,The subtype of the Account Level 2 that furthe...,None,PRD,Int,The numeric portion of the 4 week time Periods...

In [5]:
dim_customer = df.iloc[2:12,0:3]
dim_customer.columns = dim_customer.iloc[0]
dim_customer = dim_customer[1:]
dim_customer["Table"] = "dim_customer"
display(dim_customer)


dim_salesgeo = df.iloc[2:12,4:7]
dim_salesgeo.columns = dim_salesgeo.iloc[0]
dim_salesgeo = dim_salesgeo[1:]
dim_salesgeo["Table"] = "dim_salesgeo"

display(dim_salesgeo)

dim_time = df.iloc[15:24,4:7]
dim_time.columns = dim_time.iloc[0]
dim_time = dim_time[1:]
dim_time["Table"] = "dim_time"

display(dim_time)

dim_finance = df.iloc[15:23,0:3]
dim_finance.columns = dim_finance.iloc[0]
dim_finance = dim_finance[1:]
dim_finance["Table"] = "dim_finance"

display(dim_finance)

dim_gotomarket = df.iloc[27:33,0:3]
dim_gotomarket.columns = dim_gotomarket.iloc[0]
dim_gotomarket = dim_gotomarket[1:]
dim_gotomarket["Table"] = "dim_gotomarket"

display(dim_gotomarket)

dim_product = df.iloc[36:42,0:3]
dim_product.columns = dim_product.iloc[0]
dim_product = dim_product[1:]
dim_product["Table"] = "dim_product"

display(dim_product)

dim_localorg = df.iloc[27:33,4:7]
dim_localorg.columns = dim_localorg.iloc[0]
dim_localorg = dim_localorg[1:]
dim_localorg["Table"] = "dim_localorg"

display(dim_localorg)

2,Column,Type,Description,Table
3,CUST_HASH_CMPST_KEY,Bigint,"Represents the Customer Hash Composite Key, a ...",dim_customer
4,MU,String,The Business Unit break-down within a Cluster,dim_customer
5,BU,String,The Market Unit break-down within a Business Unit,dim_customer
6,HRMNZD_CUST_GRPNG_NM,String,None,dim_customer
7,CSTM_HRCHY_LVL_1_NM,String,None,dim_customer
8,CUST_LOCL_ATRBT_2_NM,String,None,dim_customer
9,CUST_LOCL_ATRBT_3_NM,String,None,dim_customer
10,CUST_LOCL_ATRBT_4_NM,String,None,dim_customer
11,datetime,Timestamp,"Represents the Timestamp, marking when the rec...",dim_customer

2,Column,Type,Description,Table
3,SLS_GEO_HASH_CMPST_KEY,Bigint,Represents a unique hashed composite key that ...,dim_salesgeo
4,SYS_ID,Int,None,dim_salesgeo
5,SUB_SYS_ID,String,None,dim_salesgeo
6,CTRY_ISO_CDV,String,None,dim_salesgeo
7,LFL_FLG,String,The Like for Like flag. Like for Like refers t...,dim_salesgeo
8,RGN,String,Strategic Cluster. It classifies for Beverages...,dim_salesgeo
9,CLSTR,String,The Cluster break-down within a Sector,dim_salesgeo
10,SCTR,String,The highest level functional organizational st...,dim_salesgeo
11,datetime,Timestamp,"Represents the Timestamp, marking when the rec...",dim_salesgeo

15,Column,Type,Description,Table
16,TME_HASH_CMPST_KEY,Bigint,Represents a unique hashed composite key for i...,dim_time
17,YR,Int,None,dim_time
18,QRTR,String,"The calendar Quarter within a Year, Q1 through...",dim_time
19,PRD,Int,The numeric portion of the 4 week time Periods...,dim_time
20,WK,Int,None,dim_time
21,VRSN,String,None,dim_time
22,FCST_MNTH,Int,"In general terms, this refers to the Period th...",dim_time
23,datetime,Timestamp,"Represents the Timestamp, marking when the rec...",dim_time

15,Column,Type,Description,Table
16,FINC_HASH_CMPST_KEY,Bigint,"Stands for Finance Hash Composite Key, a hashe...",dim_finance
17,BU_ACCT_LVL_1,String,"The highest level in the Account Hierarchy, th...",dim_finance
18,BU_ACCT_LVL_2,String,The subtype of the Account Level 1 that furthe...,dim_finance
19,BU_ACCT_LVL_3,String,The subtype of the Account Level 2 that furthe...,dim_finance
20,ACCT_TYP,String,The classification that designates the source ...,dim_finance
21,LOCL_CRNCY_CDV,String,None,dim_finance
22,datetime,Timestamp,"Represents the Timestamp, marking when the rec...",dim_finance

27,Column,Type,Description,Table
28,GTM_HASH_CMPST_KEY,Bigint,"Refers to the Go-To-Market Hash Composite Key,...",dim_gotomarket
29,GTM_DESC,String,None,dim_gotomarket
30,GTM_HRCHY_LVL_1_NM,String,None,dim_gotomarket
31,GTM_HRCHY_LVL_2_NM,String,None,dim_gotomarket
32,datetime,Timestamp,"Represents the Timestamp, marking when the rec...",dim_gotomarket

36,Column,Type,Description,Table
37,PRDT_HASH_CMPST_KEY,Bigint,"Represents the Product Hash Composite Key, a u...",dim_product
38,PROD_HRCHY_LVL_2_NM,String,None,dim_product
39,PROD_HRCHY_LVL_3_NM,String,None,dim_product
40,PROD_LOCL_ATRBT_1_NM,String,None,dim_product
41,datetime,Timestamp,"Represents the Timestamp, marking when the rec...",dim_product

27,Column,Type,Description,Table
28,LOCL_ORG_HASH_CMPST_KEY,Bigint,Represents a unique hashed composite key to id...,dim_localorg
29,LOCL_ORG_L1_NM,String,None,dim_localorg
30,LOCL_ORG_HRCHY_LVL_1_NM,String,None,dim_localorg
31,LOCL_ORG_HRCHY_LVL_3_NM,String,None,dim_localorg
32,datetime,Timestamp,"Represents the Timestamp, marking when the rec...",dim_localorg

In [7]:
merged_df = pd.concat([dim_customer,dim_salesgeo, dim_time, dim_finance,dim_gotomarket,dim_product, dim_localorg])
merged_df.to_csv("mosaic_merged_table_info.csv",index=False)
merged_df

,Column,Type,Description,Table
3,CUST_HASH_CMPST_KEY,Bigint,"Represents the Customer Hash Composite Key, a ...",dim_customer
4,MU,String,The Business Unit break-down within a Cluster,dim_customer
5,BU,String,The Market Unit break-down within a Business Unit,dim_customer
6,HRMNZD_CUST_GRPNG_NM,String,None,dim_customer
7,CSTM_HRCHY_LVL_1_NM,String,None,dim_customer
8,CUST_LOCL_ATRBT_2_NM,String,None,dim_customer
9,CUST_LOCL_ATRBT_3_NM,String,None,dim_customer
10,CUST_LOCL_ATRBT_4_NM,String,None,dim_customer
11,datetime,Timestamp,"Represents the Timestamp, marking when the rec...",dim_customer
3,SLS_GEO_HASH_CMPST_KEY,Bigint,Represents a unique hashed composite key that ...,dim_salesgeo
4,SYS_ID,Int,None,dim_salesgeo
5,SUB_SYS_ID,String,None,dim_salesgeo
6,CTRY_ISO_CDV,String,None,dim_salesgeo
7,LFL_FLG,String,The Like for Like flag. Like for Like refers t...,dim_salesgeo
8,RGN,String,Strategic Cluster. It classifies for Beverages...,dim_salesgeo
9,CLSTR,String,The Cluster break-down within a Sector,dim_salesgeo
10,SCTR,String,The highest level functional organizational st...,dim_salesgeo
11,datetime,Timestamp,"Represents the Timestamp, marking when the rec...",dim_salesgeo
16,TME_HASH_CMPST_KEY,Bigint,Represents a unique hashed composite key for i...,dim_time
17,YR,Int,None,dim_time
18,QRTR,String,"The calendar Quarter within a Year, Q1 through...",dim_time
19,PRD,Int,The numeric portion of the 4 week time Periods...,dim_time
20,WK,Int,None,dim_time
21,VRSN,String,None,dim_time
22,FCST_MNTH,Int,"In general terms, this refers to the Period th...",dim_time
23,datetime,Timestamp,"Represents the Timestamp, marking when the rec...",dim_time
16,FINC_HASH_CMPST_KEY,Bigint,"Stands for Finance Hash Composite Key, a hashe...",dim_finance
17,BU_ACCT_LVL_1,String,"The highest level in the Account Hierarchy, th...",dim_finance
18,BU_ACCT_LVL_2,String,The subtype of the Account Level 1 that furthe...,dim_finance
19,BU_ACCT_LVL_3,String,The subtype of the Account Level 2 that furthe...,dim_finance
20,ACCT_TYP,String,The classification that designates the source ...,dim_finance
21,LOCL_CRNCY_CDV,String,None,dim_finance
22,datetime,Timestamp,"Represents the Timestamp, marking when the rec...",dim_finance
28,GTM_HASH_CMPST_KEY,Bigint,"Refers to the Go-To-Market Hash Composite Key,...",dim_gotomarket
29,GTM_DESC,String,None,dim_gotomarket
30,GTM_HRCHY_LVL_1_NM,String,None,dim_gotomarket
31,GTM_HRCHY_LVL_2_NM,String,None,dim_gotomarket
32,datetime,Timestamp,"Represents the Timestamp, marking when the rec...",dim_gotomarket
37,PRDT_HASH_CMPST_KEY,Bigint,"Represents the Product Hash Composite Key, a u...",dim_product
38,PROD_HRCHY_LVL_2_NM,String,None,dim_product
39,PROD_HRCHY_LVL_3_NM,String,None,dim_product
40,PROD_LOCL_ATRBT_1_NM,String,None,dim_product
41,datetime,Timestamp,"Represents the Timestamp, marking when the rec...",dim_product
28,LOCL_ORG_HASH_CMPST_KEY,Bigint,Represents a unique hashed composite key to id...,dim_localorg
29,LOCL_ORG_L1_NM,String,None,dim_localorg
30,LOCL_ORG_HRCHY_LVL_1_NM,String,None,dim_localorg
31,LOCL_ORG_HRCHY_LVL_3_NM,String,None,dim_localorg
32,datetime,Timestamp,"Represents the Timestamp, marking when the rec...",dim_localorg

Not creating any context through llm for columns with no description

Creating pickle file for definition set which has some description

In [8]:
merged_df_with_desc = merged_df[~merged_df["Description"].isnull()]
merged_df_with_desc

,Column,Type,Description,Table
3,CUST_HASH_CMPST_KEY,Bigint,"Represents the Customer Hash Composite Key, a ...",dim_customer
4,MU,String,The Business Unit break-down within a Cluster,dim_customer
5,BU,String,The Market Unit break-down within a Business Unit,dim_customer
11,datetime,Timestamp,"Represents the Timestamp, marking when the rec...",dim_customer
3,SLS_GEO_HASH_CMPST_KEY,Bigint,Represents a unique hashed composite key that ...,dim_salesgeo
7,LFL_FLG,String,The Like for Like flag. Like for Like refers t...,dim_salesgeo
8,RGN,String,Strategic Cluster. It classifies for Beverages...,dim_salesgeo
9,CLSTR,String,The Cluster break-down within a Sector,dim_salesgeo
10,SCTR,String,The highest level functional organizational st...,dim_salesgeo
11,datetime,Timestamp,"Represents the Timestamp, marking when the rec...",dim_salesgeo
16,TME_HASH_CMPST_KEY,Bigint,Represents a unique hashed composite key for i...,dim_time
18,QRTR,String,"The calendar Quarter within a Year, Q1 through...",dim_time
19,PRD,Int,The numeric portion of the 4 week time Periods...,dim_time
22,FCST_MNTH,Int,"In general terms, this refers to the Period th...",dim_time
23,datetime,Timestamp,"Represents the Timestamp, marking when the rec...",dim_time
16,FINC_HASH_CMPST_KEY,Bigint,"Stands for Finance Hash Composite Key, a hashe...",dim_finance
17,BU_ACCT_LVL_1,String,"The highest level in the Account Hierarchy, th...",dim_finance
18,BU_ACCT_LVL_2,String,The subtype of the Account Level 1 that furthe...,dim_finance
19,BU_ACCT_LVL_3,String,The subtype of the Account Level 2 that furthe...,dim_finance
20,ACCT_TYP,String,The classification that designates the source ...,dim_finance
22,datetime,Timestamp,"Represents the Timestamp, marking when the rec...",dim_finance
28,GTM_HASH_CMPST_KEY,Bigint,"Refers to the Go-To-Market Hash Composite Key,...",dim_gotomarket
32,datetime,Timestamp,"Represents the Timestamp, marking when the rec...",dim_gotomarket
37,PRDT_HASH_CMPST_KEY,Bigint,"Represents the Product Hash Composite Key, a u...",dim_product
41,datetime,Timestamp,"Represents the Timestamp, marking when the rec...",dim_product
28,LOCL_ORG_HASH_CMPST_KEY,Bigint,Represents a unique hashed composite key to id...,dim_localorg
32,datetime,Timestamp,"Represents the Timestamp, marking when the rec...",dim_localorg

In [9]:
merged_df_with_desc_no_duplicates = merged_df_with_desc.drop_duplicates()
merged_df_with_desc_no_duplicates.reset_index(drop=True, inplace=True)

In [10]:
merged_df_with_desc_no_duplicates.head()

,Column,Type,Description,Table
0,CUST_HASH_CMPST_KEY,Bigint,"Represents the Customer Hash Composite Key, a ...",dim_customer
1,MU,String,The Business Unit break-down within a Cluster,dim_customer
2,BU,String,The Market Unit break-down within a Business Unit,dim_customer
3,datetime,Timestamp,"Represents the Timestamp, marking when the rec...",dim_customer
4,SLS_GEO_HASH_CMPST_KEY,Bigint,Represents a unique hashed composite key that ...,dim_salesgeo

In [11]:
from langchain.schema import Document
doc_list=[]
for i,row in merged_df_with_desc_no_duplicates.iterrows():

    row_dict= {col:row[col] for col in merged_df_with_desc_no_duplicates.columns if col!="Description"}

    doc_object = Document(page_content=row["Description"], metadata=row_dict)
    doc_list.append(doc_object)
print(doc_list)

[Document(metadata={'Column': 'CUST_HASH_CMPST_KEY', 'Type': 'Bigint', 'Table': 'dim_customer'}, page_content='Represents the Customer Hash Composite Key, a unique identifier for customer records created using a hash function to ensure integrity across systems.'), Document(metadata={'Column': 'MU', 'Type': 'String', 'Table': 'dim_customer'}, page_content='The Business Unit break-down within a Cluster'), Document(metadata={'Column': 'BU', 'Type': 'String', 'Table': 'dim_customer'}, page_content='The Market Unit break-down within a Business Unit'), Document(metadata={'Column': 'datetime', 'Type': 'Timestamp', 'Table': 'dim_customer'}, page_content='Represents the Timestamp, marking when the record was created or last modified.'), Document(metadata={'Column': 'SLS_GEO_HASH_CMPST_KEY', 'Type': 'Bigint', 'Table': 'dim_salesgeo'}, page_content='Represents a unique hashed composite key that identifies specific sales geographies, combining multiple attributes for efficient indexing and lookup.'), Document(metadata={'Column': 'LFL_FLG', 'Type': 'String', 'Table': 'dim_salesgeo'}, page_content='The Like for Like flag. Like for Like refers to the method of financial comparison by eliminating transactions from prior periods that no longer apply to the current time period.'), Document(metadata={'Column': 'RGN', 'Type': 'String', 'Table': 'dim_salesgeo'}, page_content='Strategic Cluster. It classifies for Beverages, the markets depending on the Share versus Coke'), Document(metadata={'Column': 'CLSTR', 'Type': 'String', 'Table': 'dim_salesgeo'}, page_content='The Cluster break-down within a Sector'), Document(metadata={'Column': 'SCTR', 'Type': 'String', 'Table': 'dim_salesgeo'}, page_content='The highest level functional organizational structure of PepsiCo, which will be broken down further by Business Unit, then Market Unit.'), Document(metadata={'Column': 'datetime', 'Type': 'Timestamp', 'Table': 'dim_salesgeo'}, page_content='Represents the Timestamp, marking when the record was created or last modified.'), Document(metadata={'Column': 'TME_HASH_CMPST_KEY', 'Type': 'Bigint', 'Table': 'dim_time'}, page_content='Represents a unique hashed composite key for identifying specific time-related dimensions, combining multiple time attributes for efficient querying'), Document(metadata={'Column': 'QRTR', 'Type': 'String', 'Table': 'dim_time'}, page_content='The calendar Quarter within a Year, Q1 through Q4.'), Document(metadata={'Column': 'PRD', 'Type': 'Int', 'Table': 'dim_time'}, page_content='The numeric portion of the 4 week time Periods that PepsiCo breaks down their financials into. The periods are P1 through P13, and this fields contains the numeric portion of those values.'), Document(metadata={'Column': 'FCST_MNTH', 'Type': 'Int', 'Table': 'dim_time'}, page_content='In general terms, this refers to the Period that the Forecast begins in and then continues through the rest of the Periods through the end of the Year. For example, a Forecast Month of "2" means Period 1 and 2 as Actuals, and P3 through Period 13 Forecasts. There are many special conditions for this column that must be considered.'), Document(metadata={'Column': 'datetime', 'Type': 'Timestamp', 'Table': 'dim_time'}, page_content='Represents the Timestamp, marking when the record was created or last modified.'), Document(metadata={'Column': 'FINC_HASH_CMPST_KEY', 'Type': 'Bigint', 'Table': 'dim_finance'}, page_content='Stands for Finance Hash Composite Key, a hashed unique identifier for financial data records, enabling efficient data linkage and retrieval.'), Document(metadata={'Column': 'BU_ACCT_LVL_1', 'Type': 'String', 'Table': 'dim_finance'}, page_content='The highest level in the Account Hierarchy, this generally correlates to the actual P&L Metric that the transaction is related to.'), Document(metadata={'Column': 'BU_ACCT_LVL_2', 'Type': 'String', 'Table': 'dim_finance'}, page_content='The subtype of the Account Level 1 that further breaks down the account hierarchy.'), Document(metadata={'Column': 'BU_ACCT_LVL_3', 'Type': 'String', 'Table': 'dim_finance'}, page_content='The subtype of the Account Level 2 that further breaks down the account hierarchy'), Document(metadata={'Column': 'ACCT_TYP', 'Type': 'String', 'Table': 'dim_finance'}, page_content='The classification that designates the source of the transaction. This can be from the Income Statement, Cash Flow, Brand P&L, Cause of Change records or other type designations.'), Document(metadata={'Column': 'datetime', 'Type': 'Timestamp', 'Table': 'dim_finance'}, page_content='Represents the Timestamp, marking when the record was created or last modified.'), Document(metadata={'Column': 'GTM_HASH_CMPST_KEY', 'Type': 'Bigint', 'Table': 'dim_gotomarket'}, page_content='Refers to the Go-To-Market Hash Composite Key, uniquely identifying go-to-market strategies or operations within the data.'), Document(metadata={'Column': 'datetime', 'Type': 'Timestamp', 'Table': 'dim_gotomarket'}, page_content='Represents the Timestamp, marking when the record was created or last modified.'), Document(metadata={'Column': 'PRDT_HASH_CMPST_KEY', 'Type': 'Bigint', 'Table': 'dim_product'}, page_content='Represents the Product Hash Composite Key, a unique identifier for the product record. This hashed key helps ensure data integrity and simplifies the process of identifying and linking products across systems.'), Document(metadata={'Column': 'datetime', 'Type': 'Timestamp', 'Table': 'dim_product'}, page_content='Represents the Timestamp, marking when the record was created or last modified.'), Document(metadata={'Column': 'LOCL_ORG_HASH_CMPST_KEY', 'Type': 'Bigint', 'Table': 'dim_localorg'}, page_content='Represents a unique hashed composite key to identify specific local organizational entities, combining multiple attributes for efficient lookups.'), Document(metadata={'Column': 'datetime', 'Type': 'Timestamp', 'Table': 'dim_localorg'}, page_content='Represents the Timestamp, marking when the record was created or last modified.')]

In [12]:
# definition_set = [{doc.metadata["Column"]:doc.page_content} for doc in doc_list]

definition_set = [{doc.metadata["Column"]:{"definition":doc.page_content, "Type": doc.metadata['Type'], "Table": doc.metadata['Table']}} for doc in doc_list]
definition_set

[{'CUST_HASH_CMPST_KEY': {'definition': 'Represents the Customer Hash Composite Key, a unique identifier for customer records created using a hash function to ensure integrity across systems.',
   'Type': 'Bigint',
   'Table': 'dim_customer'}},
 {'MU': {'definition': 'The Business Unit break-down within a Cluster',
   'Type': 'String',
   'Table': 'dim_customer'}},
 {'BU': {'definition': 'The Market Unit break-down within a Business Unit',
   'Type': 'String',
   'Table': 'dim_customer'}},
 {'datetime': {'definition': 'Represents the Timestamp, marking when the record was created or last modified.',
   'Type': 'Timestamp',
   'Table': 'dim_customer'}},
 {'SLS_GEO_HASH_CMPST_KEY': {'definition': 'Represents a unique hashed composite key that identifies specific sales geographies, combining multiple attributes for efficient indexing and lookup.',
   'Type': 'Bigint',
   'Table': 'dim_salesgeo'}},
 {'LFL_FLG': {'definition': 'The Like for Like flag. Like for Like refers to the method of financial comparison by eliminating transactions from prior periods that no longer apply to the current time period.',
   'Type': 'String',
   'Table': 'dim_salesgeo'}},
 {'RGN': {'definition': 'Strategic Cluster. It classifies for Beverages, the markets depending on the Share versus Coke',
   'Type': 'String',
   'Table': 'dim_salesgeo'}},
 {'CLSTR': {'definition': 'The Cluster break-down within a Sector',
   'Type': 'String',
   'Table': 'dim_salesgeo'}},
 {'SCTR': {'definition': 'The highest level functional organizational structure of PepsiCo, which will be broken down further by Business Unit, then Market Unit.',
   'Type': 'String',
   'Table': 'dim_salesgeo'}},
 {'datetime': {'definition': 'Represents the Timestamp, marking when the record was created or last modified.',
   'Type': 'Timestamp',
   'Table': 'dim_salesgeo'}},
 {'TME_HASH_CMPST_KEY': {'definition': 'Represents a unique hashed composite key for identifying specific time-related dimensions, combining multiple time attributes for efficient querying',
   'Type': 'Bigint',
   'Table': 'dim_time'}},
 {'QRTR': {'definition': 'The calendar Quarter within a Year, Q1 through Q4.',
   'Type': 'String',
   'Table': 'dim_time'}},
 {'PRD': {'definition': 'The numeric portion of the 4 week time Periods that PepsiCo breaks down their financials into. The periods are P1 through P13, and this fields contains the numeric portion of those values.',
   'Type': 'Int',
   'Table': 'dim_time'}},
 {'FCST_MNTH': {'definition': 'In general terms, this refers to the Period that the Forecast begins in and then continues through the rest of the Periods through the end of the Year. For example, a Forecast Month of "2" means Period 1 and 2 as Actuals, and P3 through Period 13 Forecasts. There are many special conditions for this column that must be considered.',
   'Type': 'Int',
   'Table': 'dim_time'}},
 {'datetime': {'definition': 'Represents the Timestamp, marking when the record was created or last modified.',
   'Type': 'Timestamp',
   'Table': 'dim_time'}},
 {'FINC_HASH_CMPST_KEY': {'definition': 'Stands for Finance Hash Composite Key, a hashed unique identifier for financial data records, enabling efficient data linkage and retrieval.',
   'Type': 'Bigint',
   'Table': 'dim_finance'}},
 {'BU_ACCT_LVL_1': {'definition': 'The highest level in the Account Hierarchy, this generally correlates to the actual P&L Metric that the transaction is related to.',
   'Type': 'String',
   'Table': 'dim_finance'}},
 {'BU_ACCT_LVL_2': {'definition': 'The subtype of the Account Level 1 that further breaks down the account hierarchy.',
   'Type': 'String',
   'Table': 'dim_finance'}},
 {'BU_ACCT_LVL_3': {'definition': 'The subtype of the Account Level 2 that further breaks down the account hierarchy',
   'Type': 'String',
   'Table': 'dim_finance'}},
 {'ACCT_TYP': {'definition': 'The classification that designates the source of the transaction. This can be from the Income Statement, Cash Flow, Brand P&L, Cause of Change records or other type designations.',
   'Type': 'String',
   'Table': 'dim_finance'}},
 {'datetime': {'definition': 'Represents the Timestamp, marking when the record was created or last modified.',
   'Type': 'Timestamp',
   'Table': 'dim_finance'}},
 {'GTM_HASH_CMPST_KEY': {'definition': 'Refers to the Go-To-Market Hash Composite Key, uniquely identifying go-to-market strategies or operations within the data.',
   'Type': 'Bigint',
   'Table': 'dim_gotomarket'}},
 {'datetime': {'definition': 'Represents the Timestamp, marking when the record was created or last modified.',
   'Type': 'Timestamp',
   'Table': 'dim_gotomarket'}},
 {'PRDT_HASH_CMPST_KEY': {'definition': 'Represents the Product Hash Composite Key, a unique identifier for the product record. This hashed key helps ensure data integrity and simplifies the process of identifying and linking products across systems.',
   'Type': 'Bigint',
   'Table': 'dim_product'}},
 {'datetime': {'definition': 'Represents the Timestamp, marking when the record was created or last modified.',
   'Type': 'Timestamp',
   'Table': 'dim_product'}},
 {'LOCL_ORG_HASH_CMPST_KEY': {'definition': 'Represents a unique hashed composite key to identify specific local organizational entities, combining multiple attributes for efficient lookups.',
   'Type': 'Bigint',
   'Table': 'dim_localorg'}},
 {'datetime': {'definition': 'Represents the Timestamp, marking when the record was created or last modified.',
   'Type': 'Timestamp',
   'Table': 'dim_localorg'}}]

In [13]:
with open("mosaic_context.pkl", "wb") as file:
    pickle.dump(definition_set, file)

Llama 3.1

In [9]:
from langchain_databricks import ChatDatabricks
import os, json
os.environ["DATABRICKS_HOST"] = "https://adb-6926527074777965.5.azuredatabricks.net"
os.environ["DATABRICKS_TOKEN"] = "dapi477662799536f4c6227fc9ba317d49f8-3"

llm_pa= ChatDatabricks(
        endpoint = "databricks-meta-llama-3-1-70b-instruct",
        max_tokens=8192,
        temperature=0,
    )

In [ ]:
def create_definition_through_llama():

    query_generalized_template = """
        <|begin_of_text|><|start_header_id|>system<|end_header_id|>
        You are an AI assistant expert specializing in understanding of the {source_type} data and {source_desc}, particularly for a CPG (Consumer Packaged Goods) company and you will be provided with a set of definitions for some {source_type} terms and your task is to use your immense knowledge and these set of definitions to expand the input by adding a clear and concise context around the {source_type} related term mentioned in the input to improve retrieval in a RAG system.
        |eot_id|><|start_header_id|>user<|end_header_id|>
        It's not necessary to use the definition given here. If you do not find any match for the input in the definition set then use your knowledge to create the final definition.
        Make sure that context is concise and to the point and is not more than 20 words.

        Definitions for some {source_type} terms: {definitions}
        Input: {original_query}

        Do not write an introduction, summary or explanation. Just provide the final context-enriched input.
        Note: DO not include statements such as "in the context of the {source_type} data for a Consumer Packaged Goods (CPG) company".
        <|eot_id|><|start_header_id|>assistant<|end_header_id|>"""



    with open("/home/ec2-user/Pepsico_Hackathon/Pepsico_Main_Hackathon/Pepsico_demo_new_gen_mapping_approach/mapping_assistant/mosaic_context.pkl", "rb") as file:

        definition_set = pickle.load(file)

    query_expander_prompt = PromptTemplate(
        input_variables=["original_query"],
        partial_variables={"definitions": definition_set,"source_type":"Retail","source_desc": "sales data"},
        template=query_generalized_template
    )

query_expander_chain = query_expander_prompt | llm_pa

Columns with no description

In [25]:
merged_df_without_desc = merged_df[merged_df["Description"].isnull()]
merged_df_without_desc

                     Column    Type Description           Table
3      HRMNZD_CUST_GRPNG_NM  String         NaN    dim_customer
4       CSTM_HRCHY_LVL_1_NM  String         NaN    dim_customer
5      CUST_LOCL_ATRBT_2_NM  String         NaN    dim_customer
6      CUST_LOCL_ATRBT_3_NM  String         NaN    dim_customer
7      CUST_LOCL_ATRBT_4_NM  String         NaN    dim_customer
10                   SYS_ID     Int         NaN    dim_salesgeo
11               SUB_SYS_ID  String         NaN    dim_salesgeo
12             CTRY_ISO_CDV  String         NaN    dim_salesgeo
19                       YR     Int         NaN        dim_time
22                       WK     Int         NaN        dim_time
23                     VRSN  String         NaN        dim_time
31           LOCL_CRNCY_CDV  String         NaN     dim_finance
34                 GTM_DESC  String         NaN  dim_gotomarket
35       GTM_HRCHY_LVL_1_NM  String         NaN  dim_gotomarket
36       GTM_HRCHY_LVL_2_NM  String         NaN  dim_gotomarket
39      PROD_HRCHY_LVL_2_NM  String         NaN     dim_product
40      PROD_HRCHY_LVL_3_NM  String         NaN     dim_product
41     PROD_LOCL_ATRBT_1_NM  String         NaN     dim_product
44           LOCL_ORG_L1_NM  String         NaN    dim_localorg
45  LOCL_ORG_HRCHY_LVL_1_NM  String         NaN    dim_localorg
46  LOCL_ORG_HRCHY_LVL_3_NM  String         NaN    dim_localorg

In [21]:
gen_def_list = []
for column in merged_df_without_desc["Column"].to_list():
    generated_definition = query_expander_chain.invoke(column).content
    print(column)
    print(generated_definition)
    gen_def_list.append({
        "column": column,
        "generated_defintion": generated_definition
    })

generated_definition_df = pd.DataFrame(gen_def_list)
generated_definition_df.head()

HRMNZD_CUST_GRPNG_NM
HRMNZD_CUST_GRPNG_NM: Harmonized customer grouping name.
CSTM_HRCHY_LVL_1_NM
Customer Hierarchy Level 1 Name
CUST_LOCL_ATRBT_2_NM
Customer Local Attribute 2 Name
CUST_LOCL_ATRBT_3_NM
Customer Local Attribute 3 Name
CUST_LOCL_ATRBT_4_NM
Customer Local Attribute 4 Name
SYS_ID
System Identifier
SUB_SYS_ID
SUB_SYS_ID: System identifier for subsystems.
CTRY_ISO_CDV
CTRY_ISO_CDV: Country code identifier.
YR
YR: Calendar Year
WK
WK: Week period in sales data.
VRSN
Version identifier for data tracking.
LOCL_CRNCY_CDV
Local Currency Code Value
GTM_DESC
GTM_DESC: Go-To-Market description.
GTM_HRCHY_LVL_1_NM
GTM_HRCHY_LVL_1_NM: Top-level Go-To-Market hierarchy name.
GTM_HRCHY_LVL_2_NM
GTM_HRCHY_LVL_2_NM: Go-To-Market hierarchy level 2 name.
PROD_HRCHY_LVL_2_NM
Product Hierarchy Level 2 Name
PROD_HRCHY_LVL_3_NM
Product Hierarchy Level 3 Name
PROD_LOCL_ATRBT_1_NM
Product Local Attribute 1 Name
LOCL_ORG_L1_NM
Local Organization Level 1 Name
LOCL_ORG_HRCHY_LVL_1_NM
Local Organization Hierarchy Level 1 Name
LOCL_ORG_HRCHY_LVL_3_NM
Local Organization Hierarchy Level 3 Name

                 column                                generated_defintion
0  HRMNZD_CUST_GRPNG_NM  HRMNZD_CUST_GRPNG_NM: Harmonized customer grou...
1   CSTM_HRCHY_LVL_1_NM                    Customer Hierarchy Level 1 Name
2  CUST_LOCL_ATRBT_2_NM                    Customer Local Attribute 2 Name
3  CUST_LOCL_ATRBT_3_NM                    Customer Local Attribute 3 Name
4  CUST_LOCL_ATRBT_4_NM                    Customer Local Attribute 4 Name

Google search

In [26]:
%pip install --upgrade --quiet  langchain_google_community==1.0.5

Note: you may need to restart the kernel to use updated packages.

In [10]:
from langchain.agents import initialize_agent
from langchain.agents import AgentType

# agent = AgentExecutor()
agent = initialize_agent(tools = tool,
                         llm = llm_pa,
                         agent=AgentType.SELF_ASK_WITH_SEARCH,
                         verbose=True)

# agent = initialize_agent(tool, agent='zero-shot-react-description', llm=llm_pa, verbose=False, handle_parsing_errors=True)

/tmp/ipykernel_215401/2227213321.py:19: LangChainDeprecationWarning: The function `initialize_agent` was deprecated in LangChain 0.1.0 and will be removed in 0.3.0. Use Use new agent constructor methods like create_react_agent, create_json_agent, create_structured_chat_agent, etc. instead.
  agent = initialize_agent(tools = tool,

AttributeError: 'tuple' object has no attribute 'is_single_input'

In [21]:
from langchain.agents import initialize_agent, load_tools
from langchain.agents import AgentType

tools = load_tools(["google-search"], llm=llm)
# agent = AgentExecutor()
agent = initialize_agent(tools = tools,
                         llm = llm,
                         agent=AgentType.SELF_ASK_WITH_SEARCH,
                         verbose=True)

# agent = initialize_agent(tool, agent='zero-shot-react-description', llm=llm_pa, verbose=False, handle_parsing_errors=True)

AttributeError: 'list' object has no attribute 'is_single_input'

In [26]:
from langchain_core.messages import BaseMessage, HumanMessage


executor.invoke({"messages": [
            HumanMessage(
                content=f"HRMNZD_CUST_GRPNG_NM"
            )
        ],})

> Entering new AgentExecutor chain...

HRMNZD_CUST_GRPNG_NM stands for "Humanized Customer Grouping Name". It is a term used in the field of customer segmentation and marketing.

Customer grouping refers to the process of categorizing customers into different groups based on certain characteristics or behaviors. This helps businesses to better understand their customers and tailor their marketing strategies accordingly.

The term "Humanized" in HRMNZD_CUST_GRPNG_NM suggests that the customer grouping is done in a way that takes into account the human aspect of the customers. It implies that the grouping is not solely based on demographic or transactional data, but also considers the individual preferences, needs, and behaviors of the customers.

The HRMNZD_CUST_GRPNG_NM can be used as a variable or field name in a database or software system to store the name or label of a specific customer grouping. It helps to identify and differentiate between different customer segments within the system.

Overall, HRMNZD_CUST_GRPNG_NM represents a customer grouping name that is created with a human-centric approach, aiming to better understand and serve the needs of customers.

> Finished chain.

{'messages': [HumanMessage(content='HRMNZD_CUST_GRPNG_NM')],
 'output': 'HRMNZD_CUST_GRPNG_NM stands for "Humanized Customer Grouping Name". It is a term used in the field of customer segmentation and marketing. \n\nCustomer grouping refers to the process of categorizing customers into different groups based on certain characteristics or behaviors. This helps businesses to better understand their customers and tailor their marketing strategies accordingly.\n\nThe term "Humanized" in HRMNZD_CUST_GRPNG_NM suggests that the customer grouping is done in a way that takes into account the human aspect of the customers. It implies that the grouping is not solely based on demographic or transactional data, but also considers the individual preferences, needs, and behaviors of the customers.\n\nThe HRMNZD_CUST_GRPNG_NM can be used as a variable or field name in a database or software system to store the name or label of a specific customer grouping. It helps to identify and differentiate between different customer segments within the system.\n\nOverall, HRMNZD_CUST_GRPNG_NM represents a customer grouping name that is created with a human-centric approach, aiming to better understand and serve the needs of customers.'}

In [ ]:
result = {'messages': [HumanMessage(content='HRMNZD_CUST_GRPNG_NM')],
 'output': 'HRMNZD_CUST_GRPNG_NM stands for "Humanized Customer Grouping Name". It is a term used in the field of customer segmentation and marketing. \n\nCustomer grouping refers to the process of categorizing customers into different groups based on certain characteristics or behaviors. This helps businesses to better understand their customers and tailor their marketing strategies accordingly.\n\nThe term "Humanized" in HRMNZD_CUST_GRPNG_NM suggests that the customer grouping is done in a way that takes into account the human aspect of the customers. It implies that the grouping is not solely based on demographic or transactional data, but also considers the individual preferences, needs, and behaviors of the customers.\n\nThe HRMNZD_CUST_GRPNG_NM can be used as a variable or field name in a database or software system to store the name or label of a specific customer grouping. It helps to identify and differentiate between different customer segments within the system.\n\nOverall, HRMNZD_CUST_GRPNG_NM represents a customer grouping name that is created with a human-centric approach, aiming to better understand and serve the needs of customers.'}

In [4]:
import pickle
from langchain_core.prompts import PromptTemplate
from langchain.agents import AgentExecutor, create_openai_functions_agent
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.tools import Tool, StructuredTool
from langchain_google_community import GoogleSearchAPIWrapper
from langchain_openai import AzureChatOpenAI
from langchain_core.messages import BaseMessage, HumanMessage
import os
llm = AzureChatOpenAI(
        api_version="2023-03-15-preview",
        api_key="ede9daf6a5424bc181860e02ed75b492",
        azure_endpoint="https://sanjoy-llm-accelerator.openai.azure.com/",
        azure_deployment="llm-accelerator-new",
        model="GPT-4o-mini",
        openai_api_type="azure",
        temperature=0,
    )



# Initializing Google search Agent

os.environ["GOOGLE_API_KEY"] = "AIzaSyCL1h3A2uusR63mCvcyolmMNn2Zpyq1FCE"
os.environ["GOOGLE_CSE_ID"] = "8358fe5affe6d4baa"


search = GoogleSearchAPIWrapper()

# tool = Tool(
#     name="google_search",
#     description="Search Google for recent results.",
#     func=search.run,
# )

# system_prompt = """
# You are an expert who is responsible in creating description for the given input with the help of available tools.
# """

# prompt = ChatPromptTemplate.from_messages(
#         [
#             (
#                 "system",
#                 system_prompt,
#             ),
#             MessagesPlaceholder(variable_name="messages"),
#             MessagesPlaceholder(variable_name="agent_scratchpad"),
#         ]
#     )

# agent = create_openai_functions_agent(llm, [tool], prompt)
# google_search_executor = AgentExecutor(agent=agent, tools=[tool], handle_parsing_errors=True, verbose=True)


# google_search_executor.invoke({"messages": [
#             HumanMessage(
#                 content="""Give me only the short description for HRMNZD_CUST_GRPNG_NM field present in the dim_customer.
#                 Give the output in the below format:
#                     Short Description:"""
#             )
#         ],})

# Using StructuredTool instead of Tool earlier because we faced the below error
# Too many arguments to single-input tool google_search.\n Consider using StructuredTool instead

tool = StructuredTool.from_function(
    func=search.run,
    name="google_search",
    description="Search Google for recent results.",
    # args_schema=GoogleSearchInput,
    return_direct=True,
    # coroutine= ... <- you can specify an async method if desired as well
)
from langgraph.prebuilt import create_react_agent

# system prompt is used to inform the tools available to when to use each
system_prompt = """Act as a helpful assistant.
    Use the tools at your disposal to perform tasks as needed.
        - google_search: whenever user asks for some description about certain attribute of an entity present in a data model or if you don't know the answer.
    """

# we can initialize the agent using the llama3 model, tools, and system prompt.
agent = create_react_agent(model=llm, tools=[tool], messages_modifier=system_prompt)

def print_stream(stream):
    for s in stream:
        message = s["messages"][-1]
        if isinstance(message, tuple):
            print(message)
        else:
            message.pretty_print()

inputs = {"messages": [("user", """In the context of retail CPG data provide me a short description of the HRMNZD_CUST_GRPNG_NM attribute present under dim_customer entity.
Give the output in the below format:
Short Description:
NOTE: Consider the first observation if you are further not able to find the answer or use your knowledge of retail CPG data""")]}
print_stream(agent.stream(inputs, stream_mode="values"))
# agent.invoke(inputs)["messages"][-1].content

('user', 'In the context of retail CPG data provide me a short description of the HRMNZD_CUST_GRPNG_NM attribute present under dim_customer entity.\nGive the output in the below format:\nShort Description:\nNOTE: Consider the first observation if you are further not able to find the answer or use your knowledge of retail CPG data')

================================== Ai Message ==================================
Tool Calls:
  google_search (call_wKeBbn64xL7LXyC8q3YmXjzR)
 Call ID: call_wKeBbn64xL7LXyC8q3YmXjzR
  Args:
    query: HRMNZD_CUST_GRPNG_NM attribute in retail CPG data
================================= Tool Message =================================
Name: google_search

No good Google Search Result was found
================================== Ai Message ==================================

Short Description:
The attribute HRMNZD_CUST_GRPNG_NM under the dim_customer entity in retail CPG data represents the customer grouping name. It is used to categorize customers into different groups based on certain criteria such as demographics, purchasing behavior, or loyalty status. This attribute helps in analyzing and segmenting customers for targeted marketing campaigns, personalized offers, and customer relationship management strategies.

GPT-4o mini + Google search

In [63]:
import pickle
from langchain_core.prompts import PromptTemplate
from langchain.agents import AgentExecutor, create_openai_functions_agent
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.tools import Tool
from langchain_google_community import GoogleSearchAPIWrapper
from langchain_openai import AzureChatOpenAI
from langchain_core.messages import BaseMessage, HumanMessage
from langgraph.prebuilt import create_react_agent

# Initializing GPT-4o-mini


llm = AzureChatOpenAI(
        api_version="2023-03-15-preview",
        api_key="ede9daf6a5424bc181860e02ed75b492",
        azure_endpoint="https://sanjoy-llm-accelerator.openai.azure.com/",
        azure_deployment="llm-accelerator-new",
        model="GPT-4o-mini",
        openai_api_type="azure",
        temperature=0,
    )



# Initializing Google search Agent

os.environ["GOOGLE_API_KEY"] = "AIzaSyCL1h3A2uusR63mCvcyolmMNn2Zpyq1FCE"
os.environ["GOOGLE_CSE_ID"] = "8358fe5affe6d4baa"


search = GoogleSearchAPIWrapper()

tool = StructuredTool.from_function(
    func=search.run,
    name="google_search",
    description="Search Google for recent results.",
    # args_schema=GoogleSearchInput,
    return_direct=True,
    # coroutine= ... <- you can specify an async method if desired as well
)

# system prompt is used to inform the tools available to when to use each
system_prompt = """Act as a helpful assistant.
    Use the tools at your disposal to perform tasks as needed.
        - google_search: whenever user asks for some description about certain attribute of an entity present in a data model or if you don't know the answer.
    """

# we can initialize the agent using the gpt-4o mini model, tools, and system prompt.
agent = create_react_agent(model=llm, tools=[tool], messages_modifier=system_prompt)

# For generating Table context

def get_external_context(entity, source_type):

    context_prompt = f'''You have immense knowledge in the {source_type} systems.
    You are given an input table named {entity} used in the {source_type} systems.
    Give the complete context of the table:
        What data is stored in the table
        The main purpose/usage of the table
        How the table usage can be extended with customization
    Give the context output in the form of bullet points
    '''
    context = llm.invoke(context_prompt)
    # token=len(encoding.encode(context+context_prompt))
    # print("Ti")
    return context

def business_def_create(short_name, source_type, attribute, entity, context):
    prompt = """
    Context:
        {context}
    Task:
        Given the context about {source_type} main table {entity_name}, for an input attribute along with its short description of this table, provide the following information:
        Business Definition: A brief explanation of the {source_type} field's purpose and the data it contains.
    Input:
        {source_type} attribute name: {attribute_name}
        Short description: {short_name}
    Output Format:
        Attribute Name:
        Business Definition:
    NOTE: Do not provide any other irrelevant information.
    """
    template = prompt.format(source_type = source_type,entity_name=entity, attribute_name=attribute, context=context, short_name=short_name)
    business_def = llm.invoke(template).content
    # token=len(encoding.encode(business_def+sap_prompt))
    # st.write(f"input for sap business def:{len(encoding.encode(sap_prompt))}")
    # st.write(f"ioutput for sap business def:{len(encoding.encode(business_def))}")
    lines = business_def.split('\n')
    for line in lines:
        if line.startswith("Business Definition:"):
            business_def = line.replace("Business Definition: ", "")
            break
    return business_def

# Google search

def search(attribute, entity, context, source_type):

    # executor.invoke({"messages": [
    #         HumanMessage(
    #             content=f"HRMNZD_CUST_GRPNG_NM"
    #         )
    #     ],})
    # result = google_search_executor.invoke(
    #     {
    #     "messages":
    #         [
    #         HumanMessage
    #             (
    #             content=f'''Give me only the short description for {attribute} field present in the {entity}.
    #             Give the output in the below format:
    #                 Short Description:
    #             NOTE: Give the output in the same format as mentioned. Do not deviate from it.
    #             Consider the first observation if you are further not able to find the answer or use your knowledge of {source_type}
    #             '''
    #             )
    #         ],
    #     }
    # )["output"]

    inputs = {"messages": [("user", f"""In the context of {source_type} provide me a short description of the {attribute} attribute present under {entity} entity.
    Give the output in the below format:
    Short Description:
    NOTE: Consider the first observation if you are further not able to find the answer or use your knowledge of {source_type}""")]}

    result = agent.invoke(inputs)["messages"][-1].content
    print(result)
    lines_data = result.split('\n')
    for line in lines_data:
        if line.startswith("Short Description:"):
            short_name = line.replace("Short Description: ", "")
            business_def = business_def_create(short_name, source_type, attribute, entity, context)

            break
        else:
            short_name="None"
            business_def="None"

    business_def= business_def_create(short_name, source_type, attribute, entity, context)
    return short_name, business_def

merged_df = pd.read_csv("/home/ec2-user/Pepsico_Hackathon/Pepsico_Main_Hackathon/Pepsico_demo_new_gen_mapping_approach/mapping_assistant/mosaic_merged_table_info.csv")

merged_df_without_desc = merged_df[merged_df["Description"].isnull()]

display(merged_df_without_desc)

# Capturing Entity context for all unique entities
entity_context_list = []
for entity in merged_df["Table"].unique():

    source_type = "Retail CPG data"

    entity_context = get_external_context(entity, source_type)

    print(entity)
    print(entity_context)
    entity_context_list.append({
        "entity": entity,
        "entity_context": entity_context
    })

entity_context_df = pd.DataFrame(entity_context_list)

display(entity_context_df)
gen_def_list = []

for idx,row in merged_df_without_desc.iterrows():

    attribute = row["Column"]
    entity = row["Table"]
    source_type = "Retail CPG data"

    entity_context = entity_context_df[entity_context_df["entity"] == entity]["entity_context"].values[0]
    # entity_context = get_external_context(entity, source_type)

    google_def, business_def = search(attribute, entity, entity_context, source_type)
    gen_def_list.append({
        "attribute": attribute,
        "entity": entity,
        "google_def": google_def,
        "business_def":business_def
    })

generated_definition_df = pd.DataFrame(gen_def_list)
display(generated_definition_df)


# for column in merged_df_without_desc["Column"].to_list():

#     generated_definition = query_expander_chain.invoke(column).content
#     print(column)
#     print(generated_definition)
#     gen_def_list.append({
#         "column": column,
#         "generated_defintion": generated_definition
#     })

# generated_definition_df = pd.DataFrame(gen_def_list)
# generated_definition_df.head()


# query_expander_prompt.pretty_print()

                     Column    Type Description           Table
3      HRMNZD_CUST_GRPNG_NM  String         NaN    dim_customer
4       CSTM_HRCHY_LVL_1_NM  String         NaN    dim_customer
5      CUST_LOCL_ATRBT_2_NM  String         NaN    dim_customer
6      CUST_LOCL_ATRBT_3_NM  String         NaN    dim_customer
7      CUST_LOCL_ATRBT_4_NM  String         NaN    dim_customer
10                   SYS_ID     Int         NaN    dim_salesgeo
11               SUB_SYS_ID  String         NaN    dim_salesgeo
12             CTRY_ISO_CDV  String         NaN    dim_salesgeo
19                       YR     Int         NaN        dim_time
22                       WK     Int         NaN        dim_time
23                     VRSN  String         NaN        dim_time
31           LOCL_CRNCY_CDV  String         NaN     dim_finance
34                 GTM_DESC  String         NaN  dim_gotomarket
35       GTM_HRCHY_LVL_1_NM  String         NaN  dim_gotomarket
36       GTM_HRCHY_LVL_2_NM  String         NaN  dim_gotomarket
39      PROD_HRCHY_LVL_2_NM  String         NaN     dim_product
40      PROD_HRCHY_LVL_3_NM  String         NaN     dim_product
41     PROD_LOCL_ATRBT_1_NM  String         NaN     dim_product
44           LOCL_ORG_L1_NM  String         NaN    dim_localorg
45  LOCL_ORG_HRCHY_LVL_1_NM  String         NaN    dim_localorg
46  LOCL_ORG_HRCHY_LVL_3_NM  String         NaN    dim_localorg

dim_customer
content='- The dim_customer table stores data related to customers in the Retail CPG data systems.\n- The table includes information such as customer ID, name, address, contact details, loyalty program status, purchase history, and demographic information.\n- The main purpose of the table is to provide a centralized repository for customer data, allowing for efficient management and analysis of customer information.\n- The table is used for various purposes, including customer segmentation, targeted marketing campaigns, personalized recommendations, customer service, and loyalty program management.\n- The table can be extended with customization by adding additional columns to capture specific customer attributes or preferences.\n- Customization can also involve integrating the table with other data sources, such as social media or third-party data providers, to enhance customer insights and enable more advanced analytics.\n- The table usage can be extended by implementing data quality checks and validation rules to ensure the accuracy and completeness of customer data.\n- Customization can also involve creating additional indexes or optimizing the table structure for faster query performance.\n- The table can be integrated with other tables in the data system, such as sales transactions or product information, to enable comprehensive analysis and reporting on customer behavior and preferences.' response_metadata={'token_usage': {'completion_tokens': 233, 'prompt_tokens': 90, 'total_tokens': 323}, 'model_name': 'gpt-35-turbo-16k', 'system_fingerprint': None, 'finish_reason': 'stop', 'logprobs': None, 'content_filter_results': {}} id='run-01138779-8a59-4dc9-82e0-fa446fd627e6-0' usage_metadata={'input_tokens': 90, 'output_tokens': 233, 'total_tokens': 323}
dim_salesgeo
content='- The dim_salesgeo table stores data related to sales geography in the Retail CPG data systems.\n- It contains information about different sales geographies such as regions, countries, states, cities, and store locations.\n- The table may include attributes such as geography ID, geography name, parent geography ID, latitude, longitude, population, area, and other relevant demographic information.\n- The main purpose of the dim_salesgeo table is to provide a standardized and structured representation of sales geographies within the retail CPG data systems.\n- It allows for the categorization and organization of sales data based on different geographical levels, enabling analysis and reporting at various levels of granularity.\n- The table can be used to track sales performance across different regions, countries, states, and cities, helping retailers and CPG companies understand market trends and make informed business decisions.\n- With customization, the table usage can be extended by adding additional attributes specific to the business needs, such as sales territory, market segment, customer demographics, or competitor information.\n- Customization can also involve creating hierarchies or relationships with other tables, such as linking sales geographies to specific product categories or customer segments.\n- The table can be integrated with other data sources, such as sales transaction data or marketing data, to provide a comprehensive view of sales performance and market dynamics.\n- Customized reports and analytics can be built on top of the dim_salesgeo table to gain insights into sales patterns, market share, customer behavior, and other key metrics.' response_metadata={'token_usage': {'completion_tokens': 301, 'prompt_tokens': 91, 'total_tokens': 392}, 'model_name': 'gpt-35-turbo-16k', 'system_fingerprint': None, 'finish_reason': 'stop', 'logprobs': None, 'content_filter_results': {}} id='run-60f8b629-bb82-4d5f-8b0d-caa1dd6f90f6-0' usage_metadata={'input_tokens': 91, 'output_tokens': 301, 'total_tokens': 392}
dim_time
content="- The dim_time table stores data related to time in the Retail CPG data systems.\n- It includes information such as date, day of the week, month, year, and other time-related attributes.\n- The main purpose of the table is to provide a reference for time-related analysis and reporting in the Retail CPG data systems.\n- It allows users to track and analyze sales, inventory, promotions, and other retail metrics over time.\n- The table can be extended with customization by adding additional columns or attributes specific to the business needs.\n- For example, custom columns like fiscal year, quarter, or week can be added to align with the company's financial reporting calendar.\n- Customization can also include adding flags or indicators for special events or holidays that impact retail sales.\n- The table usage can be extended by integrating it with other tables in the data system, such as sales or inventory tables, to perform more complex analysis and reporting." response_metadata={'token_usage': {'completion_tokens': 188, 'prompt_tokens': 90, 'total_tokens': 278}, 'model_name': 'gpt-35-turbo-16k', 'system_fingerprint': None, 'finish_reason': 'stop', 'logprobs': None, 'content_filter_results': {}} id='run-42dbe519-f680-47be-ba87-684f6890b34f-0' usage_metadata={'input_tokens': 90, 'output_tokens': 188, 'total_tokens': 278}
dim_finance
content='- The dim_finance table stores financial data related to the Retail CPG industry.\n- It includes information such as sales revenue, expenses, profit margins, and financial ratios.\n- The table is used to track and analyze the financial performance of the retail CPG business.\n- It provides insights into the profitability, cost structure, and financial health of the company.\n- The table can be extended with customization by adding additional columns to capture specific financial metrics or KPIs relevant to the business.\n- Customization can also involve creating additional tables or views that join with dim_finance to provide more comprehensive financial analysis.\n- The table can be integrated with other data tables in the Retail CPG data systems to perform advanced analytics and reporting on financial data.\n- It can be used to generate financial reports, dashboards, and visualizations for management and stakeholders.\n- The table can be leveraged for budgeting, forecasting, and financial planning purposes.\n- It can also be used for benchmarking the financial performance against industry standards or competitors.' response_metadata={'token_usage': {'completion_tokens': 206, 'prompt_tokens': 91, 'total_tokens': 297}, 'model_name': 'gpt-35-turbo-16k', 'system_fingerprint': None, 'finish_reason': 'stop', 'logprobs': None, 'content_filter_results': {}} id='run-f7ab6443-a658-47bf-a63c-43ad7857cd81-0' usage_metadata={'input_tokens': 91, 'output_tokens': 206, 'total_tokens': 297}
dim_gotomarket
content='- The dim_gotomarket table stores data related to different go-to-market strategies used in the Retail CPG data systems.\n- The table includes information such as the go-to-market strategy ID, strategy name, description, and any other relevant attributes.\n- The main purpose of the table is to provide a reference for the various go-to-market strategies implemented in the Retail CPG data systems.\n- It allows users to identify and categorize different strategies used for distributing products to the market.\n- The table can be extended with customization by adding additional attributes or columns to capture more specific details about each go-to-market strategy.\n- Customization can also involve linking the table with other tables in the data system to establish relationships and enable more comprehensive analysis and reporting.\n- The table usage can be extended by integrating it with other data sources or systems to gather additional information about the effectiveness or performance of each go-to-market strategy.\n- Customization can also involve creating views or derived tables based on the dim_gotomarket table to provide more specialized or aggregated insights for specific business needs.' response_metadata={'token_usage': {'completion_tokens': 215, 'prompt_tokens': 93, 'total_tokens': 308}, 'model_name': 'gpt-35-turbo-16k', 'system_fingerprint': None, 'finish_reason': 'stop', 'logprobs': None, 'content_filter_results': {}} id='run-67874d26-1b5d-41b4-b5a1-faf92e7262b1-0' usage_metadata={'input_tokens': 93, 'output_tokens': 215, 'total_tokens': 308}
dim_product
content='- The dim_product table stores data related to products in the Retail CPG data systems.\n- The table includes information such as product ID, name, description, brand, category, subcategory, price, and other attributes.\n- The main purpose of the table is to provide a centralized repository for product data, allowing for efficient management and analysis of products in the retail industry.\n- The table can be used for various purposes, including:\n  - Product catalog management: The table can be used to store and update product information, enabling retailers to easily manage their product catalogs.\n  - Sales and inventory analysis: By linking the dim_product table with other tables such as sales and inventory, retailers can analyze product performance, identify best-selling products, and manage stock levels effectively.\n  - Pricing and promotions: The table can be customized to include pricing information, allowing retailers to set and manage product prices, as well as track promotions and discounts.\n  - Product recommendations: By analyzing the attributes and characteristics stored in the dim_product table, retailers can develop personalized product recommendations for customers.\n- The table usage can be extended with customization by adding additional columns or attributes to capture specific product information relevant to the retail CPG industry.\n- Customization can also involve linking the dim_product table with other tables or data sources to enhance data analysis and decision-making capabilities.\n- Additionally, the table can be customized to include data validation rules, data quality checks, and data governance processes to ensure the accuracy and consistency of product data.' response_metadata={'token_usage': {'completion_tokens': 299, 'prompt_tokens': 90, 'total_tokens': 389}, 'model_name': 'gpt-35-turbo-16k', 'system_fingerprint': None, 'finish_reason': 'stop', 'logprobs': None, 'content_filter_results': {}} id='run-985d6e3d-2344-413d-a54b-0745d65143c7-0' usage_metadata={'input_tokens': 90, 'output_tokens': 299, 'total_tokens': 389}
dim_localorg
content="- The dim_localorg table stores data related to local organizations in the Retail CPG data systems.\n- The table includes information such as the organization's ID, name, address, contact details, and other relevant attributes.\n- The main purpose of the table is to provide a centralized repository for managing and organizing data about local organizations within the retail industry.\n- It allows for efficient tracking and analysis of various aspects related to local organizations, such as their performance, sales, distribution, and relationships with other entities.\n- The table can be extended with customization by adding additional columns to capture specific attributes or information relevant to the retail CPG data systems.\n- Customization can also involve creating additional tables that are linked to the dim_localorg table to store more detailed or specialized information about local organizations.\n- The table usage can be extended by integrating it with other data systems or applications to enhance data sharing, reporting, and analysis capabilities.\n- Customized views or reports can be created based on the data stored in the dim_localorg table to meet specific business requirements or analytical needs." response_metadata={'token_usage': {'completion_tokens': 213, 'prompt_tokens': 91, 'total_tokens': 304}, 'model_name': 'gpt-35-turbo-16k', 'system_fingerprint': None, 'finish_reason': 'stop', 'logprobs': None, 'content_filter_results': {}} id='run-cb22fb7e-eb8f-413d-8997-544e59a5a579-0' usage_metadata={'input_tokens': 91, 'output_tokens': 213, 'total_tokens': 304}

           entity                                     entity_context
0    dim_customer  content='- The dim_customer table stores data ...
1    dim_salesgeo  content='- The dim_salesgeo table stores data ...
2        dim_time  content="- The dim_time table stores data rela...
3     dim_finance  content='- The dim_finance table stores financ...
4  dim_gotomarket  content='- The dim_gotomarket table stores dat...
5     dim_product  content='- The dim_product table stores data r...
6    dim_localorg  content="- The dim_localorg table stores data ...

Short Description:
The attribute HRMNZD_CUST_GRPNG_NM under the dim_customer entity in Retail CPG data represents the customer grouping name. It is used to categorize customers into different groups based on certain criteria such as demographics, purchasing behavior, or loyalty status. This attribute helps in analyzing and segmenting customers for targeted marketing campaigns, personalized offers, and customer relationship management.
Short Description:
The attribute CSTM_HRCHY_LVL_1_NM in the dim_customer entity represents the first level of hierarchy in the customer hierarchy in the Retail CPG data. It is used to categorize customers into broader groups or segments based on certain criteria such as demographics, purchasing behavior, or geographic location. The specific details of this attribute may vary depending on the specific implementation of the Retail CPG data model.
Short Description:
The attribute CUST_LOCL_ATRBT_2_NM under the dim_customer entity in Retail CPG data represents a customer's second local attribute. This attribute could be any additional information or characteristic specific to the customer, such as their preferred store location, loyalty program status, or demographic information. The exact meaning and usage of this attribute may vary depending on the specific implementation of the data model in the Retail CPG context.
Short Description:
The attribute CUST_LOCL_ATRBT_3_NM under the dim_customer entity in Retail CPG data represents a customer's local attribute. However, since there is no specific information available about this attribute in the context of Retail CPG data, it is recommended to consider the first observation or use your knowledge of Retail CPG data to determine the exact meaning and purpose of this attribute.
Short Description:
The attribute CUST_LOCL_ATRBT_4_NM is a customer local attribute present under the dim_customer entity in the Retail CPG data model. Unfortunately, I couldn't find a specific description for this attribute. However, in the context of Retail CPG data, customer local attributes typically refer to additional information or characteristics specific to individual customers, such as their preferred store location, loyalty program status, or purchase history at a particular store. These attributes are used to segment and analyze customer behavior, personalize marketing campaigns, and improve customer experience.
Short Description:
The SYS_ID attribute in the dim_salesgeo entity in Retail CPG data is a unique identifier that is used to uniquely identify each sales geography in the system. It is typically a system-generated identifier and is used for internal purposes such as data management and referencing.
Short Description:
The SUB_SYS_ID attribute in the dim_salesgeo entity in Retail CPG data represents the unique identifier for the subsystem within the sales geography. It is used to identify and differentiate different subsystems within the sales geography, which can include various divisions, regions, or territories.
Short Description:
The CTRY_ISO_CDV attribute in the dim_salesgeo entity of Retail CPG data represents the ISO country code for the sales geography. It is a unique identifier assigned to each country in accordance with the ISO 3166 standard.
Short Description:
The YR attribute in the dim_time entity of Retail CPG data represents the year. It provides contextual information about the time dimension, allowing analysis and reporting based on yearly trends and comparisons.
Short Description:
The WK attribute in the dim_time entity of Retail CPG data represents the week number. It is used to track and analyze data based on the week of the year.
Short Description:
The VRSN attribute in the dim_time entity of Retail CPG data represents the version number or version identifier associated with a particular time dimension. It helps in tracking and managing different versions of time-related data within the Retail CPG data model.
Short Description:
The LOCL_CRNCY_CDV attribute in the dim_finance entity of Retail CPG data represents the local currency code value. It is used to indicate the currency in which financial transactions are recorded and reported within a specific location or country.
Short Description:
The GTM_DESC attribute in the dim_gotomarket entity in Retail CPG data refers to the description of the go-to-market strategy or approach used by a company in the retail consumer packaged goods industry. It provides information about how the company plans to distribute and sell its products to consumers, including the channels, tactics, and strategies employed.
Short Description:
The GTM_HRCHY_LVL_1_NM attribute in the dim_gotomarket entity represents the first level of the hierarchy in the Go-To-Market (GTM) structure in the context of Retail CPG data. It is a categorical attribute that categorizes the different market segments or channels within the retail industry. This attribute provides a high-level classification of the various sales channels or distribution channels used by a company to reach its customers.
Short Description:
The GTM_HRCHY_LVL_2_NM attribute in the dim_gotomarket entity is a field that represents the second level of hierarchy in the Go-To-Market (GTM) structure in the Retail CPG data. It is used to categorize and classify different sales channels or distribution channels within the retail industry. This attribute provides information about the specific level of the GTM hierarchy that a particular sales channel or distribution channel belongs to.
Short Description:
The PROD_HRCHY_LVL_2_NM attribute in the dim_product entity represents the second level of hierarchy in the product hierarchy for Retail CPG data. It provides a categorization or classification of products at a more specific level than the first level of hierarchy. This attribute helps in organizing and grouping products based on their characteristics or attributes, allowing for easier analysis and decision-making in the retail industry.
Short Description:
The PROD_HRCHY_LVL_3_NM attribute is a field present under the dim_product entity in Retail CPG data. It represents the third level of hierarchy for product classification. This attribute provides information about the specific category or group to which a product belongs. It helps in organizing and categorizing products based on their similarities and characteristics.
Short Description:
The PROD_LOCL_ATRBT_1_NM attribute is a local attribute associated with the dim_product entity in the Retail CPG data. It represents a specific attribute or characteristic of a product that is relevant to the local market. The exact nature of this attribute may vary depending on the specific implementation and requirements of the Retail CPG data model.
Short Description:
The LOCL_ORG_L1_NM attribute in the dim_localorg entity of Retail CPG data represents the name of the first level local organization. It is used to categorize and identify different local organizations within the retail industry.
Short Description:
The LOCL_ORG_HRCHY_LVL_1_NM attribute is a field present under the dim_localorg entity in the Retail CPG data model. It represents the name of the first level of the local organization hierarchy. This attribute is used to categorize and classify local organizations within the retail industry.
Short Description:
The LOCL_ORG_HRCHY_LVL_3_NM attribute in the dim_localorg entity represents the name of the third level of the hierarchical structure of a local organization in the Retail CPG data. It provides information about the specific category or division within a local organization.

,attribute,entity,google_def,business_def
0,HRMNZD_CUST_GRPNG_NM,dim_customer,Short Description:,This attribute stores the grouping name of cus...
1,CSTM_HRCHY_LVL_1_NM,dim_customer,Short Description:,The CSTM_HRCHY_LVL_1_NM field in the dim_custo...
2,CUST_LOCL_ATRBT_2_NM,dim_customer,Short Description:,This attribute stores the second local attribu...
3,CUST_LOCL_ATRBT_3_NM,dim_customer,Short Description:,This attribute stores the third local attribut...
4,CUST_LOCL_ATRBT_4_NM,dim_customer,Short Description:,This attribute stores the fourth local attribu...
5,SYS_ID,dim_salesgeo,Short Description:,The SYS_ID attribute in the dim_salesgeo table...
6,SUB_SYS_ID,dim_salesgeo,Short Description:,The SUB_SYS_ID attribute in the dim_salesgeo t...
7,CTRY_ISO_CDV,dim_salesgeo,Short Description:,The CTRY_ISO_CDV attribute in the dim_salesgeo...
8,YR,dim_time,Short Description:,The YR attribute in the dim_time table represe...
9,WK,dim_time,Short Description:,"The ""WK"" attribute in the dim_time table repre..."
10,VRSN,dim_time,Short Description:,The VRSN attribute in the dim_time table of Re...
11,LOCL_CRNCY_CDV,dim_finance,Short Description:,The LOCL_CRNCY_CDV attribute in the dim_financ...
12,GTM_DESC,dim_gotomarket,Short Description:,The GTM_DESC attribute in the dim_gotomarket t...
13,GTM_HRCHY_LVL_1_NM,dim_gotomarket,Short Description:,The GTM_HRCHY_LVL_1_NM attribute in the dim_go...
14,GTM_HRCHY_LVL_2_NM,dim_gotomarket,Short Description:,GTM_HRCHY_LVL_2_NM is an attribute in the dim_...
15,PROD_HRCHY_LVL_2_NM,dim_product,Short Description:,The PROD_HRCHY_LVL_2_NM attribute in the dim_p...
16,PROD_HRCHY_LVL_3_NM,dim_product,Short Description:,This attribute in the dim_product table repres...
17,PROD_LOCL_ATRBT_1_NM,dim_product,Short Description:,PROD_LOCL_ATRBT_1_NM is an attribute in the di...
18,LOCL_ORG_L1_NM,dim_localorg,Short Description:,The LOCL_ORG_L1_NM attribute in the dim_localo...
19,LOCL_ORG_HRCHY_LVL_1_NM,dim_localorg,Short Description:,This attribute stores the name of the local or...
20,LOCL_ORG_HRCHY_LVL_3_NM,dim_localorg,Short Description:,This attribute in the dim_localorg table repre...

In [64]:
generated_definition_df.to_csv("generated_mosaic_definition.csv", index=False)

#### Context Generation for fields which doesn't have the proper explanation/all the fields (YET TO DECIDE)

In [6]:
config = json.load(open("/home/ec2-user/Pepsico_Hackathon/Pepsico_Main_Hackathon/Pepsico_Data_Foundation_with_multi_table_indices_llama/config/config.json"))


def get_llm():

    os.environ["DATABRICKS_HOST"] = config["LLAMA"]["DATABRICKS_HOST"]
    os.environ["DATABRICKS_TOKEN"] = config["LLAMA"]["DATABRICKS_TOKEN"]
    llm = ChatDatabricks(
        endpoint = config["LLAMA"]["ENDPOINT"],
        max_tokens=config["LLAMA"]["max_tokens"],
        temperature=config["LLAMA"]["temperature"],
    )
    return llm

llama_llm = get_llm()

prompt = ChatPromptTemplate.from_template("""
        <|begin_of_text|><|start_header_id|>system<|end_header_id|>
        You are an AI assistant expert specializing in understanding of the PPA (Price Pack Architecture) data, particularly for a CPG (Consumer Packaged Goods) company. Your task is to provide brief, relevant context for the given data by enhancing the provided explanation using your immense knowledge of CPG industry.
        |eot_id|><|start_header_id|>user<|end_header_id|>
        Data : {data}
        Explanation: {explanation}

        Provide a concise context (2-3 sentences) for this Data, considering the following guidelines:
        1. Identify the main parameter which is mentioned in the explanation
        2. If the explanation is very short, then expand it based on your PPA knowledge.

        Please give a short succinct context to situate this data within the overall PPA mapping document for the purposes of improving search retrieval of the data. Answer only with the succinct context and nothing else.

        <|eot_id|><|start_header_id|>assistant<|end_header_id|>
        """)

contextualized_doc_list = []

async def make_llm_call(prompt,doc):

    response = await llama_llm.ainvoke(prompt.format_messages(data=doc.metadata, explanation = doc.page_content))
    context = response.content
    contextualized_content = f"{context}\n\n{doc.page_content}"
    final_context = Document(page_content=contextualized_content, metadata=doc.metadata)
    return final_context

async def contextualize_mapping(prompt,doc_list):

    tasks = [make_llm_call(prompt,doc) for doc in doc_list]

    # Run tasks concurrently and gather results
    return await asyncio.gather(*tasks)

contextualized_doc_list = await contextualize_mapping(prompt, doc_list)

contextualized_doc_list

[Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'COGS_AMOUNT', 'Source Column from Input/PPA': 'COGS/unit', 'Mapping logic': 'Direct pull', 'Alternative names': 'COGS/unit'}, page_content="The main parameter mentioned is Cost of Goods Sold (COGS). In the context of a CPG company's PPA data, COGS represents the direct costs incurred to produce a product, including labor, materials, and overhead, which is crucial for determining product profitability and pricing strategy. This data point is essential for financial analysis and decision-making, as it directly impacts the company's bottom line.\n\nCost of Goods Sold.  All direct costs needed to produce a product for sale."),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'BB_DSCNT_AMT', 'Source Column from Input/PPA': 'SCAN', 'Mapping logic': 'Direct pull', 'Alternative names': 'Coupon'}, page_content="The main parameter mentioned is the allowance amount approved by the business, specifically the BB_DSCNT_AMT (Bill Back Discount Amount) paid by PepsiCo to the retailer when a promotion is scanned. This data point is crucial in tracking the financial transactions between PepsiCo and its retailers, enabling accurate reimbursement for promotional activities. In the context of PPA mapping, this data helps to reconcile the promotional spend with the actual sales data, ensuring that PepsiCo's trade promotion strategies are effectively executed and measured.\n\nThis is the allowance amount approved by the business paid by PepsiCo to the retailer when a promotion is Scanned. The retailer sends an invoice back to PepsiCo as dues to be paid by PepsiCo for only the count of products which triggered the promotion conditions. "),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'CRNCY_CDV', 'Source Column from Input/PPA': nan, 'Mapping logic': 'hard code', 'Alternative names': nan}, page_content='The main parameter mentioned in the explanation is the "Currency Code". In the context of a CPG company\'s PPA data, the Currency Code is a crucial element for financial transactions and pricing strategies, as it enables the company to manage multiple currencies across different regions and markets. This data point is essential for accurate financial reporting, invoicing, and revenue analysis.\n\nCurrency Code'),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'CTRY_CDV', 'Source Column from Input/PPA': nan, 'Mapping logic': 'hard code', 'Alternative names': nan}, page_content='The main parameter mentioned in the explanation is "Country Code". In the context of a CPG company\'s PPA data, the Country Code is a crucial piece of information that identifies the country of origin or destination for a product, which is essential for logistics, taxation, and regulatory compliance purposes. This code is likely used to map product distribution and sales data across different regions and countries.\n\nCountry Code'),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'DSCNT_AMT', 'Source Column from Input/PPA': 'EDLP Trade', 'Mapping logic': 'Direct pull', 'Alternative names': nan}, page_content='The main parameter mentioned in the explanation is EDLP (Everyday Low Price) Trade, a pricing strategy in the CPG industry where a flat discount is offered to certain products, deducted directly from the invoice, unaffected by promotions. This data point is crucial in understanding the pricing architecture of the company, as it influences the final cost of products to customers. In the context of PPA mapping, this data helps in accurately calculating the net sales and revenue, enabling better financial analysis and decision-making.\n\nDefinition - EDLP is a flat discount given to certain PPGs, off invoice regardless of any promotions '),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'PRMTN_ALWNC_DSCNT_AMT', 'Source Column from Input/PPA': 'PA \nPromo', 'Mapping logic': 'Direct pull', 'Alternative names': 'Retro / Unit'}, page_content='The main parameter mentioned in the explanation is Promotional Allowance (PA), a type of price reduction offered to retailers as an incentive to display and feature specific Frito-Lay items. In the context of PPA mapping, PA is a key component of the Net Cost Sheet, derived from Off Invoice (OI) discounts, which are applied to all units loaded, regardless of scanning. This data point is crucial for accurately calculating the net cost of goods and understanding the financial impact of promotional activities on sales and revenue.\n\nPromotional allowance.  Price reductions that Customers(retailers) sometimes receive as incentives to display and feature specific Frito-Lay items.  PA is derived from OI (off invoice) on the Net Cost Sheet.  Off invoice (OI) is the discount given off invoice.  OI is received on all units loaded in, regardless of whether they scanned or not.'),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'MCHNC_NM', 'Source Column from Input/PPA': nan, 'Mapping logic': 'hard code', 'Alternative names': nan}, page_content='The main parameter mentioned in the explanation is the "Mechanic name". In the context of CPG PPA data, the Mechanic name refers to a specific promotional mechanic or tactic used to drive sales, such as "Buy One Get One Free" or "10% Off". This data point is crucial in understanding the type of promotion being offered, which can impact pricing, packaging, and overall marketing strategy.\n\nMechanic name'),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'MCHNC_PRC_AMT', 'Source Column from Input/PPA': 'Promo Price', 'Mapping logic': 'Direct pull', 'Alternative names': '\nDeal,Promotion\nFeature_Price'}, page_content='The main parameter mentioned in the explanation is the "promoted price". In the context of CPG PPA data, the promoted price refers to the temporary discounted price offered to customers during a promotional period, which is a key pricing strategy to drive sales and increase market share. This data point is crucial for analyzing the effectiveness of promotional campaigns and informing future pricing decisions.\n\npromoted price'),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'MCHNC_PRC_PER_UNIT_AMT', 'Source Column from Input/PPA': 'Promo Price per unit', 'Mapping logic': 'calculated', 'Alternative names': '\nFeature_Price,Retail,ISP - Base/ Deal'}, page_content='The main parameter mentioned in the explanation is the "Promo Price per unit", which is a crucial metric in the CPG industry for calculating the price of a single unit during promotional periods. This data point is essential for analyzing the effectiveness of promotions and understanding the revenue impact on the business. In the context of PPA mapping, this field is used to calculate the promoted price of a single unit, enabling accurate revenue management and pricing strategy optimization.\n\nPromo price / promo qty - promoted price of a single unit'),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'MCHNC_PRC_QTY', 'Source Column from Input/PPA': 'Promo Qty', 'Mapping logic': 'Direct pull', 'Alternative names': 'Deal\nPromotion\nEvent'}, page_content='The main parameter mentioned in the explanation is the quantity required to purchase in order to be eligible for a promotion. In the context of CPG PPA data, this refers to the minimum quantity of a product that a customer must buy to qualify for a promotional offer, such as a discount or buy-one-get-one-free deal. This data point is crucial for tracking and analyzing the effectiveness of promotional campaigns and optimizing pricing strategies.\n\nQuantity to purchase to get a promotion'),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'MCHNC_TYP_NM', 'Source Column from Input/PPA': 'Mechanic Flag', 'Mapping logic': 'calculated', 'Alternative names': nan}, page_content="The main parameter mentioned in the explanation is the type of promotion. This data point, 'MCHNC_TYP_NM', is crucial in the PPA mapping as it helps categorize promotions into distinct types, such as price-based, buy-one-get-one-free, or coupon-based offers, enabling CPG companies to analyze and optimize their promotional strategies effectively.\n\nDenotes the type of promotion (ex. price, must buy, coupon, etc.)"),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'MKT_BNNR_NM', 'Source Column from Input/PPA': 'Sobeys English Conventional or Sobeys IGA QC', 'Mapping logic': 'hard code', 'Alternative names': nan}, page_content='The main parameter mentioned in the explanation is "Grouping of stores for promotions". This data point is crucial in the PPA mapping document as it enables the CPG company to categorize stores like Sobeys English Conventional or Sobeys IGA QC under a specific banner (MKT_BNNR_NM) for targeted promotional activities, ensuring effective marketing strategies and improved sales. This grouping also facilitates the analysis of promotional performance across different store types.\n\nGrouping of stores for promotions.'),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'MKT_RTLR_NM', 'Source Column from Input/PPA': '"Sobeys"', 'Mapping logic': 'hard code', 'Alternative names': nan}, page_content='The main parameter mentioned in the explanation is the "retailer name". In the context of the CPG company\'s PPA data, this refers to the specific retailer, in this case, Sobeys, which is a Canadian supermarket chain. This data point is crucial for mapping and analyzing sales data, as it helps to identify the performance of the company\'s products across different retail partners.\n\nretailer name'),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'RDMPTN_DSCNT_PCT', 'Source Column from Input/PPA': nan, 'Mapping logic': 'hard code', 'Alternative names': nan}, page_content="This data pertains to the 'RDMPTN_DSCNT_PCT' metric, which represents the expected percentage of units purchased due to a specific promotional tactic, such as a discount or offer. In the context of CPG PPA analysis, this metric is crucial for evaluating the effectiveness of promotional strategies and their impact on sales volume. By tracking this percentage, manufacturers can refine their tactics to optimize sales and revenue growth.\n\nExpected percentage of units which are purchased due to the tactic."),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'SDV_COST_AMT', 'Source Column from Input/PPA': 'SDV', 'Mapping logic': 'Direct pull', 'Alternative names': nan}, page_content="This data pertains to the 'Importance' of a tactic in driving sales, specifically measuring the expected percentage of units purchased due to the tactic. The 'SDV_COST_AMT' column is directly pulled from the 'SDV' source column, indicating a key metric for evaluating the tactic's effectiveness. In the context of CPG PPA, this data likely informs pricing and promotion strategies to maximize sales volume and revenue.\n\nExpected percentage of units which are purchased due to the tactic.\n"),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'UCOST_AMT', 'Source Column from Input/PPA': nan, 'Mapping logic': 'hard code', 'Alternative names': nan}, page_content='The main parameter mentioned is the unit cost amount, specifically the manufacturing cost of a single unit. In the context of CPG PPA data, this unit cost amount is a critical component in calculating the total cost of goods sold and is often used to determine profitability and pricing strategies. This data point is essential for financial analysis and decision-making within the organization.\n\nField denotes the unit cost amount. This is the manufacturing cost of a single unit.'),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'VAT_AMT', 'Source Column from Input/PPA': nan, 'Mapping logic': 'hard code', 'Alternative names': 'Vat %'}, page_content="The main parameter mentioned in the explanation is Value Added Tax (VAT). In the context of CPG, VAT is a consumption tax levied on the value added to goods and services at each stage of production and distribution. This VAT amount is crucial for accurate pricing and revenue calculation, making it a 'Must Have' field in the PPA mapping document.\n\nValue Added Tax - consumption tax."),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'PRC_EFF_END_DT', 'Source Column from Input/PPA': 'start date', 'Mapping logic': 'Direct pull from from price matrix', 'Alternative names': 'From Period file of the corresponding retailers'}, page_content='The main parameter mentioned in the explanation is the "effective start date of financials". This data point is crucial in the PPA mapping document as it determines the commencement date of promotional or base pricing for a specific product, influencing revenue calculations and financial reporting. In the context of CPG companies, this date is essential for tracking pricing changes, managing trade promotions, and analyzing sales performance.\n\neffective start date of financials related to promoted/base record'),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'PRC_EFF_STRT_DT', 'Source Column from Input/PPA': 'end date', 'Mapping logic': 'Direct pull from from price matrix', 'Alternative names': 'From Period file of the corresponding retailers'}, page_content='The main parameter mentioned in the explanation is the "effective end date of financials". This data point is crucial in the PPA mapping document as it determines the end date of promotional or base pricing for a specific product, influencing financial calculations and analysis. In the context of CPG companies, this date is essential for tracking pricing strategies and their impact on sales and revenue.\n\neffective end date of financials related to promoted/base record'),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'PRC_TYP_NM', 'Source Column from Input/PPA': 'Promo type', 'Mapping logic': 'calculated', 'Alternative names': 'price_type'}, page_content='The main parameter mentioned in the explanation is the "Promotion or base indicator". This data point is crucial in distinguishing between promotional and non-promotional pricing strategies, enabling CPG companies to analyze the effectiveness of their pricing tactics and make informed decisions. In the context of PPA, this field helps to categorize prices as either regular/base prices or promotional prices, which is essential for accurate price analysis and optimization.\n\nPromotion or base indicator'),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'PROD_ATRBT_1_TYP_NM', 'Source Column from Input/PPA': nan, 'Mapping logic': 'hard code', 'Alternative names': nan}, page_content="The main parameter mentioned in the explanation is the product attribute type name, which is a crucial element in defining price matrices for various markets in the CPG industry. This attribute type name is used to categorize products based on characteristics such as SKU, UPC, Flavor, or Promoted Product Group (PPG), allowing for targeted pricing strategies across different sectors. By standardizing this attribute type name, the company can ensure consistency in its pricing approach and facilitate more effective market analysis.\n\nField denotes the product attribute type name based on which the price matrix is defined for different markets. A product attribute can be SKU, UPC, Flavor, Promoted Product Group (PPG), etc. A product attribute can be any level of product hierarchy as received from different price matrix field from different sectors. In case for any market if the attribute value is not present or not applicable this will be populated as  'NA'  or 'UNKNOWN' or 'NOT AVAILABLE'."),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'PROD_ATRBT_1_VAL', 'Source Column from Input/PPA': 'Final PPG Name', 'Mapping logic': 'Direct pull from PGT Naming input file', 'Alternative names': nan}, page_content='The main parameter mentioned in the explanation is PPG (Promo Product Group), which represents the grain of product at which promotions are run. In the context of PPA mapping, PPG is a critical attribute that helps in identifying the specific product configuration (Brand & Size) eligible for promotions. This data point is essential for accurately mapping promotional activities to the corresponding product groups, enabling effective sales and revenue tracking.\n\nPPG is promo product group. This is grain of product at which promotions are run. Concat Brand & Size to get a PPG'),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'PROD_ATRBT_2_TYP_NM', 'Source Column from Input/PPA': nan, 'Mapping logic': 'hard code', 'Alternative names': nan}, page_content="The main parameter mentioned in the explanation is the product attribute type name, which is a crucial element in defining price matrices for various markets in the CPG industry. This attribute type name is used to categorize products based on characteristics such as SKU, UPC, Flavor, or Promoted Product Group (PPG), allowing for nuanced pricing strategies across different sectors. By standardizing this attribute type name, the company can ensure consistency in its pricing architecture and facilitate more accurate data analysis.\n\nField denotes the product attribute type name based on which the price matrix is defined for different markets. A product attribute can be SKU, UPC, Flavor, Promoted Product Group (PPG), etc. A product attribute can be any level of product hierarchy as received from different price matrix field from different sectors. In case for any market if the attribute value is not present or not applicable this will be populated as  'NA'  or 'UNKNOWN' or 'NOT AVAILABLE'."),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'PROD_ATRBT_2_VAL', 'Source Column from Input/PPA': nan, 'Mapping logic': 'hard code', 'Alternative names': 'L1'}, page_content="The main parameter mentioned in the explanation is the product attribute type value, which is crucial in defining the price matrix for different markets in the CPG industry. This attribute can be any level of product hierarchy, such as SKU, UPC, or Flavor, and is used to determine pricing strategies across various sectors. In the context of PPA mapping, this data is essential for accurately mapping product attributes to their corresponding price matrices, ensuring efficient price management and optimization.\n\nField denotes the product attribute type value based on which the price matrix is defined for different markets. A product attribute can be SKU, UPC, Flavor, Promoted Product Group (PPG), etc. A product attribute can be any level of product hierarchy as received from different price matrix field from different sectors. In case for any market if the attribute value is not present or not applicable this will be populated as  'NA'  or 'UNKNOWN' or 'NOT AVAILABLE'."),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'PROD_CTGY_NM', 'Source Column from Input/PPA': nan, 'Mapping logic': 'hard code', 'Alternative names': nan}, page_content='The main parameter mentioned is the Product Category Name, which is a crucial attribute in the CPG industry for categorizing products into distinct groups. This attribute is essential for product classification, inventory management, and sales analysis. In the context of PPA mapping, the Product Category Name is likely used to determine pricing and packaging strategies for different product categories.\n\nProduct Category Name'),

In [44]:
def clean_document_metadata(doc):

    cleaned_metadata = {
        key: ("" if value is None or (isinstance(value, float) and math.isnan(value)) else value)
        for key, value in doc.metadata.items()
    }
    return Document(page_content=doc.page_content, metadata=cleaned_metadata)

cleaned_contextualized_doc_list = [clean_document_metadata(doc) for doc in contextualized_doc_list]

In [36]:
len(cleaned_contextualized_doc_list)

44

In [47]:
for doc in cleaned_contextualized_doc_list:
    if 'text' in doc.metadata.keys():
        del doc.metadata['text']

In [48]:
cleaned_contextualized_doc_list

[Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'COGS_AMOUNT', 'Source Column from Input/PPA': 'COGS/unit', 'Mapping logic': 'Direct pull', 'Alternative names': 'COGS/unit'}, page_content="The main parameter mentioned is Cost of Goods Sold (COGS). In the context of a CPG company's PPA data, COGS represents the direct costs incurred to produce a product, including labor, materials, and overhead, which is crucial for determining product profitability and pricing strategy. This data point is essential for financial analysis and decision-making, as it directly impacts the company's bottom line.\n\nCost of Goods Sold.  All direct costs needed to produce a product for sale."),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'BB_DSCNT_AMT', 'Source Column from Input/PPA': 'SCAN', 'Mapping logic': 'Direct pull', 'Alternative names': 'Coupon'}, page_content="The main parameter mentioned is the allowance amount approved by the business, specifically the BB_DSCNT_AMT (Bill Back Discount Amount) paid by PepsiCo to the retailer when a promotion is scanned. This data point is crucial in tracking the financial transactions between PepsiCo and its retailers, enabling accurate reimbursement for promotional activities. In the context of PPA mapping, this data helps to reconcile the promotional spend with the actual sales data, ensuring that PepsiCo's trade promotion strategies are effectively executed and measured.\n\nThis is the allowance amount approved by the business paid by PepsiCo to the retailer when a promotion is Scanned. The retailer sends an invoice back to PepsiCo as dues to be paid by PepsiCo for only the count of products which triggered the promotion conditions. "),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'CRNCY_CDV', 'Source Column from Input/PPA': '', 'Mapping logic': 'hard code', 'Alternative names': ''}, page_content='The main parameter mentioned in the explanation is the "Currency Code". In the context of a CPG company\'s PPA data, the Currency Code is a crucial element for financial transactions and pricing strategies, as it enables the company to manage multiple currencies across different regions and markets. This data point is essential for accurate financial reporting, invoicing, and revenue analysis.\n\nCurrency Code'),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'CTRY_CDV', 'Source Column from Input/PPA': '', 'Mapping logic': 'hard code', 'Alternative names': ''}, page_content='The main parameter mentioned in the explanation is "Country Code". In the context of a CPG company\'s PPA data, the Country Code is a crucial piece of information that identifies the country of origin or destination for a product, which is essential for logistics, taxation, and regulatory compliance purposes. This code is likely used to map product distribution and sales data across different regions and countries.\n\nCountry Code'),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'DSCNT_AMT', 'Source Column from Input/PPA': 'EDLP Trade', 'Mapping logic': 'Direct pull', 'Alternative names': ''}, page_content='The main parameter mentioned in the explanation is EDLP (Everyday Low Price) Trade, a pricing strategy in the CPG industry where a flat discount is offered to certain products, deducted directly from the invoice, unaffected by promotions. This data point is crucial in understanding the pricing architecture of the company, as it influences the final cost of products to customers. In the context of PPA mapping, this data helps in accurately calculating the net sales and revenue, enabling better financial analysis and decision-making.\n\nDefinition - EDLP is a flat discount given to certain PPGs, off invoice regardless of any promotions '),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'PRMTN_ALWNC_DSCNT_AMT', 'Source Column from Input/PPA': 'PA \nPromo', 'Mapping logic': 'Direct pull', 'Alternative names': 'Retro / Unit'}, page_content='The main parameter mentioned in the explanation is Promotional Allowance (PA), a type of price reduction offered to retailers as an incentive to display and feature specific Frito-Lay items. In the context of PPA mapping, PA is a key component of the Net Cost Sheet, derived from Off Invoice (OI) discounts, which are applied to all units loaded, regardless of scanning. This data point is crucial for accurately calculating the net cost of goods and understanding the financial impact of promotional activities on sales and revenue.\n\nPromotional allowance.  Price reductions that Customers(retailers) sometimes receive as incentives to display and feature specific Frito-Lay items.  PA is derived from OI (off invoice) on the Net Cost Sheet.  Off invoice (OI) is the discount given off invoice.  OI is received on all units loaded in, regardless of whether they scanned or not.'),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'MCHNC_NM', 'Source Column from Input/PPA': '', 'Mapping logic': 'hard code', 'Alternative names': ''}, page_content='The main parameter mentioned in the explanation is the "Mechanic name". In the context of CPG PPA data, the Mechanic name refers to a specific promotional mechanic or tactic used to drive sales, such as "Buy One Get One Free" or "10% Off". This data point is crucial in understanding the type of promotion being offered, which can impact pricing, packaging, and overall marketing strategy.\n\nMechanic name'),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'MCHNC_PRC_AMT', 'Source Column from Input/PPA': 'Promo Price', 'Mapping logic': 'Direct pull', 'Alternative names': '\nDeal,Promotion\nFeature_Price'}, page_content='The main parameter mentioned in the explanation is the "promoted price". In the context of CPG PPA data, the promoted price refers to the temporary discounted price offered to customers during a promotional period, which is a key pricing strategy to drive sales and increase market share. This data point is crucial for analyzing the effectiveness of promotional campaigns and informing future pricing decisions.\n\npromoted price'),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'MCHNC_PRC_PER_UNIT_AMT', 'Source Column from Input/PPA': 'Promo Price per unit', 'Mapping logic': 'calculated', 'Alternative names': '\nFeature_Price,Retail,ISP - Base/ Deal'}, page_content='The main parameter mentioned in the explanation is the "Promo Price per unit", which is a crucial metric in the CPG industry for calculating the price of a single unit during promotional periods. This data point is essential for analyzing the effectiveness of promotions and understanding the revenue impact on the business. In the context of PPA mapping, this field is used to calculate the promoted price of a single unit, enabling accurate revenue management and pricing strategy optimization.\n\nPromo price / promo qty - promoted price of a single unit'),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'MCHNC_PRC_QTY', 'Source Column from Input/PPA': 'Promo Qty', 'Mapping logic': 'Direct pull', 'Alternative names': 'Deal\nPromotion\nEvent'}, page_content='The main parameter mentioned in the explanation is the quantity required to purchase in order to be eligible for a promotion. In the context of CPG PPA data, this refers to the minimum quantity of a product that a customer must buy to qualify for a promotional offer, such as a discount or buy-one-get-one-free deal. This data point is crucial for tracking and analyzing the effectiveness of promotional campaigns and optimizing pricing strategies.\n\nQuantity to purchase to get a promotion'),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'MCHNC_TYP_NM', 'Source Column from Input/PPA': 'Mechanic Flag', 'Mapping logic': 'calculated', 'Alternative names': ''}, page_content="The main parameter mentioned in the explanation is the type of promotion. This data point, 'MCHNC_TYP_NM', is crucial in the PPA mapping as it helps categorize promotions into distinct types, such as price-based, buy-one-get-one-free, or coupon-based offers, enabling CPG companies to analyze and optimize their promotional strategies effectively.\n\nDenotes the type of promotion (ex. price, must buy, coupon, etc.)"),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'MKT_BNNR_NM', 'Source Column from Input/PPA': 'Sobeys English Conventional or Sobeys IGA QC', 'Mapping logic': 'hard code', 'Alternative names': ''}, page_content='The main parameter mentioned in the explanation is "Grouping of stores for promotions". This data point is crucial in the PPA mapping document as it enables the CPG company to categorize stores like Sobeys English Conventional or Sobeys IGA QC under a specific banner (MKT_BNNR_NM) for targeted promotional activities, ensuring effective marketing strategies and improved sales. This grouping also facilitates the analysis of promotional performance across different store types.\n\nGrouping of stores for promotions.'),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'MKT_RTLR_NM', 'Source Column from Input/PPA': '"Sobeys"', 'Mapping logic': 'hard code', 'Alternative names': ''}, page_content='The main parameter mentioned in the explanation is the "retailer name". In the context of the CPG company\'s PPA data, this refers to the specific retailer, in this case, Sobeys, which is a Canadian supermarket chain. This data point is crucial for mapping and analyzing sales data, as it helps to identify the performance of the company\'s products across different retail partners.\n\nretailer name'),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'RDMPTN_DSCNT_PCT', 'Source Column from Input/PPA': '', 'Mapping logic': 'hard code', 'Alternative names': ''}, page_content="This data pertains to the 'RDMPTN_DSCNT_PCT' metric, which represents the expected percentage of units purchased due to a specific promotional tactic, such as a discount or offer. In the context of CPG PPA analysis, this metric is crucial for evaluating the effectiveness of promotional strategies and their impact on sales volume. By tracking this percentage, manufacturers can refine their tactics to optimize sales and revenue growth.\n\nExpected percentage of units which are purchased due to the tactic."),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'SDV_COST_AMT', 'Source Column from Input/PPA': 'SDV', 'Mapping logic': 'Direct pull', 'Alternative names': ''}, page_content="This data pertains to the 'Importance' of a tactic in driving sales, specifically measuring the expected percentage of units purchased due to the tactic. The 'SDV_COST_AMT' column is directly pulled from the 'SDV' source column, indicating a key metric for evaluating the tactic's effectiveness. In the context of CPG PPA, this data likely informs pricing and promotion strategies to maximize sales volume and revenue.\n\nExpected percentage of units which are purchased due to the tactic.\n"),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'UCOST_AMT', 'Source Column from Input/PPA': '', 'Mapping logic': 'hard code', 'Alternative names': ''}, page_content='The main parameter mentioned is the unit cost amount, specifically the manufacturing cost of a single unit. In the context of CPG PPA data, this unit cost amount is a critical component in calculating the total cost of goods sold and is often used to determine profitability and pricing strategies. This data point is essential for financial analysis and decision-making within the organization.\n\nField denotes the unit cost amount. This is the manufacturing cost of a single unit.'),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'VAT_AMT', 'Source Column from Input/PPA': '', 'Mapping logic': 'hard code', 'Alternative names': 'Vat %'}, page_content="The main parameter mentioned in the explanation is Value Added Tax (VAT). In the context of CPG, VAT is a consumption tax levied on the value added to goods and services at each stage of production and distribution. This VAT amount is crucial for accurate pricing and revenue calculation, making it a 'Must Have' field in the PPA mapping document.\n\nValue Added Tax - consumption tax."),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'PRC_EFF_END_DT', 'Source Column from Input/PPA': 'start date', 'Mapping logic': 'Direct pull from from price matrix', 'Alternative names': 'From Period file of the corresponding retailers'}, page_content='The main parameter mentioned in the explanation is the "effective start date of financials". This data point is crucial in the PPA mapping document as it determines the commencement date of promotional or base pricing for a specific product, influencing revenue calculations and financial reporting. In the context of CPG companies, this date is essential for tracking pricing changes, managing trade promotions, and analyzing sales performance.\n\neffective start date of financials related to promoted/base record'),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'PRC_EFF_STRT_DT', 'Source Column from Input/PPA': 'end date', 'Mapping logic': 'Direct pull from from price matrix', 'Alternative names': 'From Period file of the corresponding retailers'}, page_content='The main parameter mentioned in the explanation is the "effective end date of financials". This data point is crucial in the PPA mapping document as it determines the end date of promotional or base pricing for a specific product, influencing financial calculations and analysis. In the context of CPG companies, this date is essential for tracking pricing strategies and their impact on sales and revenue.\n\neffective end date of financials related to promoted/base record'),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'PRC_TYP_NM', 'Source Column from Input/PPA': 'Promo type', 'Mapping logic': 'calculated', 'Alternative names': 'price_type'}, page_content='The main parameter mentioned in the explanation is the "Promotion or base indicator". This data point is crucial in distinguishing between promotional and non-promotional pricing strategies, enabling CPG companies to analyze the effectiveness of their pricing tactics and make informed decisions. In the context of PPA, this field helps to categorize prices as either regular/base prices or promotional prices, which is essential for accurate price analysis and optimization.\n\nPromotion or base indicator'),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'PROD_ATRBT_1_TYP_NM', 'Source Column from Input/PPA': '', 'Mapping logic': 'hard code', 'Alternative names': ''}, page_content="The main parameter mentioned in the explanation is the product attribute type name, which is a crucial element in defining price matrices for various markets in the CPG industry. This attribute type name is used to categorize products based on characteristics such as SKU, UPC, Flavor, or Promoted Product Group (PPG), allowing for targeted pricing strategies across different sectors. By standardizing this attribute type name, the company can ensure consistency in its pricing approach and facilitate more effective market analysis.\n\nField denotes the product attribute type name based on which the price matrix is defined for different markets. A product attribute can be SKU, UPC, Flavor, Promoted Product Group (PPG), etc. A product attribute can be any level of product hierarchy as received from different price matrix field from different sectors. In case for any market if the attribute value is not present or not applicable this will be populated as  'NA'  or 'UNKNOWN' or 'NOT AVAILABLE'."),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'PROD_ATRBT_1_VAL', 'Source Column from Input/PPA': 'Final PPG Name', 'Mapping logic': 'Direct pull from PGT Naming input file', 'Alternative names': ''}, page_content='The main parameter mentioned in the explanation is PPG (Promo Product Group), which represents the grain of product at which promotions are run. In the context of PPA mapping, PPG is a critical attribute that helps in identifying the specific product configuration (Brand & Size) eligible for promotions. This data point is essential for accurately mapping promotional activities to the corresponding product groups, enabling effective sales and revenue tracking.\n\nPPG is promo product group. This is grain of product at which promotions are run. Concat Brand & Size to get a PPG'),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'PROD_ATRBT_2_TYP_NM', 'Source Column from Input/PPA': '', 'Mapping logic': 'hard code', 'Alternative names': ''}, page_content="The main parameter mentioned in the explanation is the product attribute type name, which is a crucial element in defining price matrices for various markets in the CPG industry. This attribute type name is used to categorize products based on characteristics such as SKU, UPC, Flavor, or Promoted Product Group (PPG), allowing for nuanced pricing strategies across different sectors. By standardizing this attribute type name, the company can ensure consistency in its pricing architecture and facilitate more accurate data analysis.\n\nField denotes the product attribute type name based on which the price matrix is defined for different markets. A product attribute can be SKU, UPC, Flavor, Promoted Product Group (PPG), etc. A product attribute can be any level of product hierarchy as received from different price matrix field from different sectors. In case for any market if the attribute value is not present or not applicable this will be populated as  'NA'  or 'UNKNOWN' or 'NOT AVAILABLE'."),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'PROD_ATRBT_2_VAL', 'Source Column from Input/PPA': '', 'Mapping logic': 'hard code', 'Alternative names': 'L1'}, page_content="The main parameter mentioned in the explanation is the product attribute type value, which is crucial in defining the price matrix for different markets in the CPG industry. This attribute can be any level of product hierarchy, such as SKU, UPC, or Flavor, and is used to determine pricing strategies across various sectors. In the context of PPA mapping, this data is essential for accurately mapping product attributes to their corresponding price matrices, ensuring efficient price management and optimization.\n\nField denotes the product attribute type value based on which the price matrix is defined for different markets. A product attribute can be SKU, UPC, Flavor, Promoted Product Group (PPG), etc. A product attribute can be any level of product hierarchy as received from different price matrix field from different sectors. In case for any market if the attribute value is not present or not applicable this will be populated as  'NA'  or 'UNKNOWN' or 'NOT AVAILABLE'."),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'PROD_CTGY_NM', 'Source Column from Input/PPA': '', 'Mapping logic': 'hard code', 'Alternative names': ''}, page_content='The main parameter mentioned is the Product Category Name, which is a crucial attribute in the CPG industry for categorizing products into distinct groups. This attribute is essential for product classification, inventory management, and sales analysis. In the context of PPA mapping, the Product Category Name is likely used to determine pricing and packaging strategies for different product categories.\n\nProduct Category Name'),

In [49]:
print(contextualized_doc_list[1])

page_content='The main parameter mentioned is the allowance amount approved by the business, specifically the BB_DSCNT_AMT (Bill Back Discount Amount) paid by PepsiCo to the retailer when a promotion is scanned. This data point is crucial in tracking the financial transactions between PepsiCo and its retailers, enabling accurate reimbursement for promotional activities. In the context of PPA mapping, this data helps to reconcile the promotional spend with the actual sales data, ensuring that PepsiCo's trade promotion strategies are effectively executed and measured.

This is the allowance amount approved by the business paid by PepsiCo to the retailer when a promotion is Scanned. The retailer sends an invoice back to PepsiCo as dues to be paid by PepsiCo for only the count of products which triggered the promotion conditions. ' metadata={'Importance': 'Must Have', 'Silver Layer Column': 'BB_DSCNT_AMT', 'Source Column from Input/PPA': 'SCAN', 'Mapping logic': 'Direct pull', 'Alternative names': 'Coupon', 'text': "The main parameter mentioned is the allowance amount approved by the business, specifically the BB_DSCNT_AMT (Bill Back Discount Amount) paid by PepsiCo to the retailer when a promotion is scanned. This data point is crucial in tracking the financial transactions between PepsiCo and its retailers, enabling accurate reimbursement for promotional activities. In the context of PPA mapping, this data helps to reconcile the promotional spend with the actual sales data, ensuring that PepsiCo's trade promotion strategies are effectively executed and measured.\n\nThis is the allowance amount approved by the business paid by PepsiCo to the retailer when a promotion is Scanned. The retailer sends an invoice back to PepsiCo as dues to be paid by PepsiCo for only the count of products which triggered the promotion conditions. "}

Adding these contextualized mapping to Pinecone

In [52]:
import json
vec = PC.from_documents(
        cleaned_contextualized_doc_list,
        index_name=index_name,
        embedding=embeddings,
        namespace="pepsico_side_by_side_mapping")

In [3]:
index.describe_index_stats()

{'dimension': 1536,
 'index_fullness': 0.0,
 'namespaces': {'pepsico_df_retailer_questions': {'vector_count': 4},
                'pepsico_side_by_side_mapping': {'vector_count': 44}},
 'total_vector_count': 48}

In [4]:
pinecone_vector_store = PineconeVectorStore(index=index,embedding=embeddings,namespace="pepsico_side_by_side_mapping")
pinecone_vector_store.similarity_search_with_relevance_scores("trade")

[(Document(metadata={'Alternative names': '', 'Importance': 'Must Have', 'Mapping logic': 'Direct pull', 'Silver Layer Column': 'DSCNT_AMT', 'Source Column from Input/PPA': 'EDLP Trade'}, page_content='The main parameter mentioned in the explanation is EDLP (Everyday Low Price) Trade, a pricing strategy in the CPG industry where a flat discount is offered to certain products, deducted directly from the invoice, unaffected by promotions. This data point is crucial in understanding the pricing architecture of the company, as it influences the final cost of products to customers. In the context of PPA mapping, this data helps in accurately calculating the net sales and revenue, enabling better financial analysis and decision-making.\n\nDefinition - EDLP is a flat discount given to certain PPGs, off invoice regardless of any promotions '),
  0.8827905355),
 (Document(metadata={'Alternative names': '', 'Importance': 'Must Have', 'Mapping logic': 'calculated', 'Silver Layer Column': 'MERCH_DSCNT_AMT', 'Source Column from Input/PPA': 'merch'}, page_content='The main parameter mentioned in the explanation is "Merch", which represents a discount given at a fixed rate payment based on the invoice price. In the context of the PPA mapping document, Merch is a key component of the pricing architecture for CPG companies, allowing them to apply discounts at the PPG (Product Group) level, independent of promotions. This discount is calculated as a percentage of the difference between the Standard Discount Value (SDV) and the sum of scan, bb, PA, and EDLP values, with the percentage varying by banner.\n\nDefinition - Merch is a discount given at a fixed rate payment based on the invoice price applied at the PPG level and off invoice regardless of any promotions\n\nMerch = (SDV - (scan + bb + PA + EDLP)) * 18.125% (Sobeys All banners) \n\nMerch = (SDV - (scan + bb + PA + EDLP)) * X% (BU Provides the % for each Banner in the Input files. (Metro All banners) '),
  0.880422324),
 (Document(metadata={'Alternative names': 'price_type', 'Importance': 'Must Have', 'Mapping logic': 'calculated', 'Silver Layer Column': 'PRC_TYP_NM', 'Source Column from Input/PPA': 'Promo type'}, page_content='The main parameter mentioned in the explanation is the "Promotion or base indicator". This data point is crucial in distinguishing between promotional and non-promotional pricing strategies, enabling CPG companies to analyze the effectiveness of their pricing tactics and make informed decisions. In the context of PPA, this field helps to categorize prices as either regular/base prices or promotional prices, which is essential for accurate price analysis and optimization.\n\nPromotion or base indicator'),
  0.878544152),
 (Document(metadata={'Alternative names': 'Vat %', 'Importance': 'Must Have', 'Mapping logic': 'hard code', 'Silver Layer Column': 'VAT_AMT', 'Source Column from Input/PPA': ''}, page_content="The main parameter mentioned in the explanation is Value Added Tax (VAT). In the context of CPG, VAT is a consumption tax levied on the value added to goods and services at each stage of production and distribution. This VAT amount is crucial for accurate pricing and revenue calculation, making it a 'Must Have' field in the PPA mapping document.\n\nValue Added Tax - consumption tax."),
  0.8783592579999999)]

In [5]:
pinecone_vector_store.similarity_search_with_relevance_scores("BB")

[(Document(metadata={'Alternative names': 'Coupon', 'Importance': 'Must Have', 'Mapping logic': 'Direct pull', 'Silver Layer Column': 'BB_DSCNT_AMT', 'Source Column from Input/PPA': 'SCAN'}, page_content="The main parameter mentioned is the allowance amount approved by the business, specifically the BB_DSCNT_AMT (Bill Back Discount Amount) paid by PepsiCo to the retailer when a promotion is scanned. This data point is crucial in tracking the financial transactions between PepsiCo and its retailers, enabling accurate reimbursement for promotional activities. In the context of PPA mapping, this data helps to reconcile the promotional spend with the actual sales data, ensuring that PepsiCo's trade promotion strategies are effectively executed and measured.\n\nThis is the allowance amount approved by the business paid by PepsiCo to the retailer when a promotion is Scanned. The retailer sends an invoice back to PepsiCo as dues to be paid by PepsiCo for only the count of products which triggered the promotion conditions. "),
  0.8839673699999999),
 (Document(metadata={'Alternative names': '', 'Importance': 'Must Have', 'Mapping logic': 'hard code', 'Silver Layer Column': 'MKT_BNNR_NM', 'Source Column from Input/PPA': 'Sobeys English Conventional or Sobeys IGA QC'}, page_content='The main parameter mentioned in the explanation is "Grouping of stores for promotions". This data point is crucial in the PPA mapping document as it enables the CPG company to categorize stores like Sobeys English Conventional or Sobeys IGA QC under a specific banner (MKT_BNNR_NM) for targeted promotional activities, ensuring effective marketing strategies and improved sales. This grouping also facilitates the analysis of promotional performance across different store types.\n\nGrouping of stores for promotions.'),
  0.876107812),
 (Document(metadata={'Alternative names': 'price_type', 'Importance': 'Must Have', 'Mapping logic': 'calculated', 'Silver Layer Column': 'PRC_TYP_NM', 'Source Column from Input/PPA': 'Promo type'}, page_content='The main parameter mentioned in the explanation is the "Promotion or base indicator". This data point is crucial in distinguishing between promotional and non-promotional pricing strategies, enabling CPG companies to analyze the effectiveness of their pricing tactics and make informed decisions. In the context of PPA, this field helps to categorize prices as either regular/base prices or promotional prices, which is essential for accurate price analysis and optimization.\n\nPromotion or base indicator'),
  0.872738391),
 (Document(metadata={'Alternative names': 'Open Buy Price', 'Importance': 'Good to Have', 'Mapping logic': 'direct pull', 'Silver Layer Column': 'OPN_BUY_AMT', 'Source Column from Input/PPA': 'Open buy'}, page_content='The main parameter mentioned is the "Open Buy amount", which refers to the cost a customer pays for not meeting the required purchase quantity for a promotion. In the context of PPA mapping for CPG companies, this data point is crucial for calculating promotional costs and understanding pricing strategies, particularly in markets like FLNA Kroger where the Open Buy amount may not align with the Everyday Low Price (EDLP) or Suggested Retail Price (SRP). This data helps in accurately modeling promotional scenarios and analyzing pricing dynamics.\n\nCost the customer pays if they do not purchase the required quantity to redeem the promotion. For FLNA Kroger, unlike other Markets, the Open Buy amount is not necessarily the EDLP/SRP. It may be a discounted price still. '),
  0.8697876035000001)]

In [7]:
pinecone_retriever = pinecone_vector_store.as_retriever()

### Adding BM25 for Hybrid Search

In [8]:
if os.path.exists("bm25_retriever.pkl"):
    with open("bm25_retriever.pkl", "rb") as f:
        bm_25_retriever = pickle.load(f)
else:
    bm_25_retriever = BM25Retriever.from_documents(cleaned_contextualized_doc_list)
    with open('bm25_retriever.pkl', 'wb') as f:
        pickle.dump(bm_25_retriever, f)

### Ensemble

In [9]:
# initialize the ensemble retriever
ensemble_retriever = EnsembleRetriever(retrievers=[bm_25_retriever, pinecone_retriever],
                                       weights=[0.5, 0.5])

In [66]:
ensemble_retriever.get_relevant_documents("trade")

[Document(metadata={'Importance': 'Good to Have', 'Silver Layer Column': 'RTLR_MRGN_PER_UNIT_AMT', 'Source Column from Input/PPA': 'retailer margin ', 'Mapping logic': 'calculated', 'Alternative names': 'TM $', 'text': 'The main parameter mentioned in the explanation is the Retailer Margin, which represents the amount earned by the retailer per unit of quantity sold. In the context of PPA mapping, this data point is crucial for calculating the profitability of a product at the retail level, taking into account various trade promotions and discounts. By understanding the retailer margin, CPG companies can optimize their pricing strategies and trade spend to maximize returns.\n\nRetailer margin amount per unit of quantity sold.\n\nRetailer Margin = Promo price per unit – (SDV - (scan + bb + PA + EDLP Trade + Merch))'}, page_content='The main parameter mentioned in the explanation is the Retailer Margin, which represents the amount earned by the retailer per unit of quantity sold. In the context of PPA mapping, this data point is crucial for calculating the profitability of a product at the retail level, taking into account various trade promotions and discounts. By understanding the retailer margin, CPG companies can optimize their pricing strategies and trade spend to maximize returns.\n\nRetailer margin amount per unit of quantity sold.\n\nRetailer Margin = Promo price per unit – (SDV - (scan + bb + PA + EDLP Trade + Merch))'),
 Document(metadata={'Alternative names': '', 'Importance': 'Must Have', 'Mapping logic': 'Direct pull', 'Silver Layer Column': 'DSCNT_AMT', 'Source Column from Input/PPA': 'EDLP Trade'}, page_content='The main parameter mentioned in the explanation is EDLP (Everyday Low Price) Trade, a pricing strategy in the CPG industry where a flat discount is offered to certain products, deducted directly from the invoice, unaffected by promotions. This data point is crucial in understanding the pricing architecture of the company, as it influences the final cost of products to customers. In the context of PPA mapping, this data helps in accurately calculating the net sales and revenue, enabling better financial analysis and decision-making.\n\nDefinition - EDLP is a flat discount given to certain PPGs, off invoice regardless of any promotions '),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'PRC_EFF_END_DT', 'Source Column from Input/PPA': 'start date', 'Mapping logic': 'Direct pull from from price matrix', 'Alternative names': 'From Period file of the corresponding retailers', 'text': 'The main parameter mentioned in the explanation is the "effective start date of financials". This data point is crucial in the PPA mapping document as it determines the commencement date of promotional or base pricing for a specific product, influencing revenue calculations and financial reporting. In the context of CPG companies, this date is essential for tracking pricing changes, managing trade promotions, and analyzing sales performance.\n\neffective start date of financials related to promoted/base record'}, page_content='The main parameter mentioned in the explanation is the "effective start date of financials". This data point is crucial in the PPA mapping document as it determines the commencement date of promotional or base pricing for a specific product, influencing revenue calculations and financial reporting. In the context of CPG companies, this date is essential for tracking pricing changes, managing trade promotions, and analyzing sales performance.\n\neffective start date of financials related to promoted/base record'),
 Document(metadata={'Alternative names': '', 'Importance': 'Must Have', 'Mapping logic': 'calculated', 'Silver Layer Column': 'MERCH_DSCNT_AMT', 'Source Column from Input/PPA': 'merch'}, page_content='The main parameter mentioned in the explanation is "Merch", which represents a discount given at a fixed rate payment based on the invoice price. In the context of the PPA mapping document, Merch is a key component of the pricing architecture for CPG companies, allowing them to apply discounts at the PPG (Product Group) level, independent of promotions. This discount is calculated as a percentage of the difference between the Standard Discount Value (SDV) and the sum of scan, bb, PA, and EDLP values, with the percentage varying by banner.\n\nDefinition - Merch is a discount given at a fixed rate payment based on the invoice price applied at the PPG level and off invoice regardless of any promotions\n\nMerch = (SDV - (scan + bb + PA + EDLP)) * 18.125% (Sobeys All banners) \n\nMerch = (SDV - (scan + bb + PA + EDLP)) * X% (BU Provides the % for each Banner in the Input files. (Metro All banners) '),
 Document(metadata={'Importance': 'Good to Have', 'Silver Layer Column': 'NETREV_PER_UNIT_AMT', 'Source Column from Input/PPA': 'net revenue per unit', 'Mapping logic': 'calculated', 'Alternative names': 'Straight Net Cost,Dead Net Price / NR', 'text': 'The main parameter mentioned in the explanation is the Net Revenue Per Unit Amount (NRPU amt). This metric represents the amount of money PepsiCo receives from a retailer for one unit of product, calculated by subtracting various trade deductions (scan, bb, PA, EDLP Trade, and Merch) from the Standard Distribution Value (SDV). In the context of PPA mapping, this data point is crucial for understanding the revenue generated by each product unit, enabling accurate financial analysis and decision-making.\n\nThe amount of money PepsiCo receives from retailer for one unit of product.\n\nNRPU amt = SDV - (scan + bb + PA + EDLP Trade + Merch)'}, page_content='The main parameter mentioned in the explanation is the Net Revenue Per Unit Amount (NRPU amt). This metric represents the amount of money PepsiCo receives from a retailer for one unit of product, calculated by subtracting various trade deductions (scan, bb, PA, EDLP Trade, and Merch) from the Standard Distribution Value (SDV). In the context of PPA mapping, this data point is crucial for understanding the revenue generated by each product unit, enabling accurate financial analysis and decision-making.\n\nThe amount of money PepsiCo receives from retailer for one unit of product.\n\nNRPU amt = SDV - (scan + bb + PA + EDLP Trade + Merch)'),
 Document(metadata={'Alternative names': 'Vat %', 'Importance': 'Must Have', 'Mapping logic': 'hard code', 'Silver Layer Column': 'VAT_AMT', 'Source Column from Input/PPA': ''}, page_content="The main parameter mentioned in the explanation is Value Added Tax (VAT). In the context of CPG, VAT is a consumption tax levied on the value added to goods and services at each stage of production and distribution. This VAT amount is crucial for accurate pricing and revenue calculation, making it a 'Must Have' field in the PPA mapping document.\n\nValue Added Tax - consumption tax."),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'BB_DSCNT_AMT', 'Source Column from Input/PPA': 'SCAN', 'Mapping logic': 'Direct pull', 'Alternative names': 'Coupon', 'text': "The main parameter mentioned is the allowance amount approved by the business, specifically the BB_DSCNT_AMT (Bill Back Discount Amount) paid by PepsiCo to the retailer when a promotion is scanned. This data point is crucial in tracking the financial transactions between PepsiCo and its retailers, enabling accurate reimbursement for promotional activities. In the context of PPA mapping, this data helps to reconcile the promotional spend with the actual sales data, ensuring that PepsiCo's trade promotion strategies are effectively executed and measured.\n\nThis is the allowance amount approved by the business paid by PepsiCo to the retailer when a promotion is Scanned. The retailer sends an invoice back to PepsiCo as dues to be paid by PepsiCo for only the count of products which triggered the promotion conditions. "}, page_content="The main parameter mentioned is the allowance amount approved by the business, specifically the BB_DSCNT_AMT (Bill Back Discount Amount) paid by PepsiCo to the retailer when a promotion is scanned. This data point is crucial in tracking the financial transactions between PepsiCo and its retailers, enabling accurate reimbursement for promotional activities. In the context of PPA mapping, this data helps to reconcile the promotional spend with the actual sales data, ensuring that PepsiCo's trade promotion strategies are effectively executed and measured.\n\nThis is the allowance amount approved by the business paid by PepsiCo to the retailer when a promotion is Scanned. The retailer sends an invoice back to PepsiCo as dues to be paid by PepsiCo for only the count of products which triggered the promotion conditions. "),
 Document(metadata={'Alternative names': 'price_type', 'Importance': 'Must Have', 'Mapping logic': 'calculated', 'Silver Layer Column': 'PRC_TYP_NM', 'Source Column from Input/PPA': 'Promo type'}, page_content='The main parameter mentioned in the explanation is the "Promotion or base indicator". This data point is crucial in distinguishing between promotional and non-promotional pricing strategies, enabling CPG companies to analyze the effectiveness of their pricing tactics and make informed decisions. In the context of PPA, this field helps to categorize prices as either regular/base prices or promotional prices, which is essential for accurate price analysis and optimization.\n\nPromotion or base indicator')]

In [10]:
ensemble_retriever.get_relevant_documents("BB")

/tmp/ipykernel_1403732/1058653113.py:1: LangChainDeprecationWarning: The method `BaseRetriever.get_relevant_documents` was deprecated in langchain-core 0.1.46 and will be removed in 1.0. Use invoke instead.
  ensemble_retriever.get_relevant_documents("BB")

[Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'PRC_TYP_NM', 'Source Column from Input/PPA': 'Promo type', 'Mapping logic': 'calculated', 'Alternative names': 'price_type', 'text': 'The main parameter mentioned in the explanation is the "Promotion or base indicator". This data point is crucial in distinguishing between promotional and non-promotional pricing strategies, enabling CPG companies to analyze the effectiveness of their pricing tactics and make informed decisions. In the context of PPA, this field helps to categorize prices as either regular/base prices or promotional prices, which is essential for accurate price analysis and optimization.\n\nPromotion or base indicator'}, page_content='The main parameter mentioned in the explanation is the "Promotion or base indicator". This data point is crucial in distinguishing between promotional and non-promotional pricing strategies, enabling CPG companies to analyze the effectiveness of their pricing tactics and make informed decisions. In the context of PPA, this field helps to categorize prices as either regular/base prices or promotional prices, which is essential for accurate price analysis and optimization.\n\nPromotion or base indicator'),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'MERCH_DSCNT_AMT', 'Source Column from Input/PPA': 'merch', 'Mapping logic': 'calculated', 'Alternative names': '', 'text': 'The main parameter mentioned in the explanation is "Merch", which represents a discount given at a fixed rate payment based on the invoice price. In the context of the PPA mapping document, Merch is a key component of the pricing architecture for CPG companies, allowing them to apply discounts at the PPG (Product Group) level, independent of promotions. This discount is calculated as a percentage of the difference between the Standard Discount Value (SDV) and the sum of scan, bb, PA, and EDLP values, with the percentage varying by banner.\n\nDefinition - Merch is a discount given at a fixed rate payment based on the invoice price applied at the PPG level and off invoice regardless of any promotions\n\nMerch = (SDV - (scan + bb + PA + EDLP)) * 18.125% (Sobeys All banners) \n\nMerch = (SDV - (scan + bb + PA + EDLP)) * X% (BU Provides the % for each Banner in the Input files. (Metro All banners) '}, page_content='The main parameter mentioned in the explanation is "Merch", which represents a discount given at a fixed rate payment based on the invoice price. In the context of the PPA mapping document, Merch is a key component of the pricing architecture for CPG companies, allowing them to apply discounts at the PPG (Product Group) level, independent of promotions. This discount is calculated as a percentage of the difference between the Standard Discount Value (SDV) and the sum of scan, bb, PA, and EDLP values, with the percentage varying by banner.\n\nDefinition - Merch is a discount given at a fixed rate payment based on the invoice price applied at the PPG level and off invoice regardless of any promotions\n\nMerch = (SDV - (scan + bb + PA + EDLP)) * 18.125% (Sobeys All banners) \n\nMerch = (SDV - (scan + bb + PA + EDLP)) * X% (BU Provides the % for each Banner in the Input files. (Metro All banners) '),
 Document(metadata={'Alternative names': 'Coupon', 'Importance': 'Must Have', 'Mapping logic': 'Direct pull', 'Silver Layer Column': 'BB_DSCNT_AMT', 'Source Column from Input/PPA': 'SCAN'}, page_content="The main parameter mentioned is the allowance amount approved by the business, specifically the BB_DSCNT_AMT (Bill Back Discount Amount) paid by PepsiCo to the retailer when a promotion is scanned. This data point is crucial in tracking the financial transactions between PepsiCo and its retailers, enabling accurate reimbursement for promotional activities. In the context of PPA mapping, this data helps to reconcile the promotional spend with the actual sales data, ensuring that PepsiCo's trade promotion strategies are effectively executed and measured.\n\nThis is the allowance amount approved by the business paid by PepsiCo to the retailer when a promotion is Scanned. The retailer sends an invoice back to PepsiCo as dues to be paid by PepsiCo for only the count of products which triggered the promotion conditions. "),
 Document(metadata={'Importance': 'Good to Have', 'Silver Layer Column': 'SPCL_PRC_AMT', 'Source Column from Input/PPA': '', 'Mapping logic': 'hard code', 'Alternative names': '', 'text': "This data pertains to the 'SPCL_PRC_AMT' column, which is likely a special pricing amount field in the CPG company's PPA data. The 'Good to Have' importance level suggests that this field is not critical but still valuable for analysis or reporting purposes. The 'hard code' mapping logic indicates that this field is populated through a predefined, non-dynamic rule or formula.\n\nnan"}, page_content="This data pertains to the 'SPCL_PRC_AMT' column, which is likely a special pricing amount field in the CPG company's PPA data. The 'Good to Have' importance level suggests that this field is not critical but still valuable for analysis or reporting purposes. The 'hard code' mapping logic indicates that this field is populated through a predefined, non-dynamic rule or formula.\n\nnan"),
 Document(metadata={'Alternative names': '', 'Importance': 'Must Have', 'Mapping logic': 'hard code', 'Silver Layer Column': 'MKT_BNNR_NM', 'Source Column from Input/PPA': 'Sobeys English Conventional or Sobeys IGA QC'}, page_content='The main parameter mentioned in the explanation is "Grouping of stores for promotions". This data point is crucial in the PPA mapping document as it enables the CPG company to categorize stores like Sobeys English Conventional or Sobeys IGA QC under a specific banner (MKT_BNNR_NM) for targeted promotional activities, ensuring effective marketing strategies and improved sales. This grouping also facilitates the analysis of promotional performance across different store types.\n\nGrouping of stores for promotions.'),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'PRC_EFF_STRT_DT', 'Source Column from Input/PPA': 'end date', 'Mapping logic': 'Direct pull from from price matrix', 'Alternative names': 'From Period file of the corresponding retailers', 'text': 'The main parameter mentioned in the explanation is the "effective end date of financials". This data point is crucial in the PPA mapping document as it determines the end date of promotional or base pricing for a specific product, influencing financial calculations and analysis. In the context of CPG companies, this date is essential for tracking pricing strategies and their impact on sales and revenue.\n\neffective end date of financials related to promoted/base record'}, page_content='The main parameter mentioned in the explanation is the "effective end date of financials". This data point is crucial in the PPA mapping document as it determines the end date of promotional or base pricing for a specific product, influencing financial calculations and analysis. In the context of CPG companies, this date is essential for tracking pricing strategies and their impact on sales and revenue.\n\neffective end date of financials related to promoted/base record'),
 Document(metadata={'Alternative names': 'Open Buy Price', 'Importance': 'Good to Have', 'Mapping logic': 'direct pull', 'Silver Layer Column': 'OPN_BUY_AMT', 'Source Column from Input/PPA': 'Open buy'}, page_content='The main parameter mentioned is the "Open Buy amount", which refers to the cost a customer pays for not meeting the required purchase quantity for a promotion. In the context of PPA mapping for CPG companies, this data point is crucial for calculating promotional costs and understanding pricing strategies, particularly in markets like FLNA Kroger where the Open Buy amount may not align with the Everyday Low Price (EDLP) or Suggested Retail Price (SRP). This data helps in accurately modeling promotional scenarios and analyzing pricing dynamics.\n\nCost the customer pays if they do not purchase the required quantity to redeem the promotion. For FLNA Kroger, unlike other Markets, the Open Buy amount is not necessarily the EDLP/SRP. It may be a discounted price still. ')]

In [12]:
ensemble_retriever.invoke("BB")

[Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'PRC_TYP_NM', 'Source Column from Input/PPA': 'Promo type', 'Mapping logic': 'calculated', 'Alternative names': 'price_type', 'text': 'The main parameter mentioned in the explanation is the "Promotion or base indicator". This data point is crucial in distinguishing between promotional and non-promotional pricing strategies, enabling CPG companies to analyze the effectiveness of their pricing tactics and make informed decisions. In the context of PPA, this field helps to categorize prices as either regular/base prices or promotional prices, which is essential for accurate price analysis and optimization.\n\nPromotion or base indicator'}, page_content='The main parameter mentioned in the explanation is the "Promotion or base indicator". This data point is crucial in distinguishing between promotional and non-promotional pricing strategies, enabling CPG companies to analyze the effectiveness of their pricing tactics and make informed decisions. In the context of PPA, this field helps to categorize prices as either regular/base prices or promotional prices, which is essential for accurate price analysis and optimization.\n\nPromotion or base indicator'),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'MERCH_DSCNT_AMT', 'Source Column from Input/PPA': 'merch', 'Mapping logic': 'calculated', 'Alternative names': '', 'text': 'The main parameter mentioned in the explanation is "Merch", which represents a discount given at a fixed rate payment based on the invoice price. In the context of the PPA mapping document, Merch is a key component of the pricing architecture for CPG companies, allowing them to apply discounts at the PPG (Product Group) level, independent of promotions. This discount is calculated as a percentage of the difference between the Standard Discount Value (SDV) and the sum of scan, bb, PA, and EDLP values, with the percentage varying by banner.\n\nDefinition - Merch is a discount given at a fixed rate payment based on the invoice price applied at the PPG level and off invoice regardless of any promotions\n\nMerch = (SDV - (scan + bb + PA + EDLP)) * 18.125% (Sobeys All banners) \n\nMerch = (SDV - (scan + bb + PA + EDLP)) * X% (BU Provides the % for each Banner in the Input files. (Metro All banners) '}, page_content='The main parameter mentioned in the explanation is "Merch", which represents a discount given at a fixed rate payment based on the invoice price. In the context of the PPA mapping document, Merch is a key component of the pricing architecture for CPG companies, allowing them to apply discounts at the PPG (Product Group) level, independent of promotions. This discount is calculated as a percentage of the difference between the Standard Discount Value (SDV) and the sum of scan, bb, PA, and EDLP values, with the percentage varying by banner.\n\nDefinition - Merch is a discount given at a fixed rate payment based on the invoice price applied at the PPG level and off invoice regardless of any promotions\n\nMerch = (SDV - (scan + bb + PA + EDLP)) * 18.125% (Sobeys All banners) \n\nMerch = (SDV - (scan + bb + PA + EDLP)) * X% (BU Provides the % for each Banner in the Input files. (Metro All banners) '),
 Document(metadata={'Alternative names': 'Coupon', 'Importance': 'Must Have', 'Mapping logic': 'Direct pull', 'Silver Layer Column': 'BB_DSCNT_AMT', 'Source Column from Input/PPA': 'SCAN'}, page_content="The main parameter mentioned is the allowance amount approved by the business, specifically the BB_DSCNT_AMT (Bill Back Discount Amount) paid by PepsiCo to the retailer when a promotion is scanned. This data point is crucial in tracking the financial transactions between PepsiCo and its retailers, enabling accurate reimbursement for promotional activities. In the context of PPA mapping, this data helps to reconcile the promotional spend with the actual sales data, ensuring that PepsiCo's trade promotion strategies are effectively executed and measured.\n\nThis is the allowance amount approved by the business paid by PepsiCo to the retailer when a promotion is Scanned. The retailer sends an invoice back to PepsiCo as dues to be paid by PepsiCo for only the count of products which triggered the promotion conditions. "),
 Document(metadata={'Importance': 'Good to Have', 'Silver Layer Column': 'SPCL_PRC_AMT', 'Source Column from Input/PPA': '', 'Mapping logic': 'hard code', 'Alternative names': '', 'text': "This data pertains to the 'SPCL_PRC_AMT' column, which is likely a special pricing amount field in the CPG company's PPA data. The 'Good to Have' importance level suggests that this field is not critical but still valuable for analysis or reporting purposes. The 'hard code' mapping logic indicates that this field is populated through a predefined, non-dynamic rule or formula.\n\nnan"}, page_content="This data pertains to the 'SPCL_PRC_AMT' column, which is likely a special pricing amount field in the CPG company's PPA data. The 'Good to Have' importance level suggests that this field is not critical but still valuable for analysis or reporting purposes. The 'hard code' mapping logic indicates that this field is populated through a predefined, non-dynamic rule or formula.\n\nnan"),
 Document(metadata={'Alternative names': '', 'Importance': 'Must Have', 'Mapping logic': 'hard code', 'Silver Layer Column': 'MKT_BNNR_NM', 'Source Column from Input/PPA': 'Sobeys English Conventional or Sobeys IGA QC'}, page_content='The main parameter mentioned in the explanation is "Grouping of stores for promotions". This data point is crucial in the PPA mapping document as it enables the CPG company to categorize stores like Sobeys English Conventional or Sobeys IGA QC under a specific banner (MKT_BNNR_NM) for targeted promotional activities, ensuring effective marketing strategies and improved sales. This grouping also facilitates the analysis of promotional performance across different store types.\n\nGrouping of stores for promotions.'),
 Document(metadata={'Importance': 'Must Have', 'Silver Layer Column': 'PRC_EFF_STRT_DT', 'Source Column from Input/PPA': 'end date', 'Mapping logic': 'Direct pull from from price matrix', 'Alternative names': 'From Period file of the corresponding retailers', 'text': 'The main parameter mentioned in the explanation is the "effective end date of financials". This data point is crucial in the PPA mapping document as it determines the end date of promotional or base pricing for a specific product, influencing financial calculations and analysis. In the context of CPG companies, this date is essential for tracking pricing strategies and their impact on sales and revenue.\n\neffective end date of financials related to promoted/base record'}, page_content='The main parameter mentioned in the explanation is the "effective end date of financials". This data point is crucial in the PPA mapping document as it determines the end date of promotional or base pricing for a specific product, influencing financial calculations and analysis. In the context of CPG companies, this date is essential for tracking pricing strategies and their impact on sales and revenue.\n\neffective end date of financials related to promoted/base record'),
 Document(metadata={'Alternative names': 'Open Buy Price', 'Importance': 'Good to Have', 'Mapping logic': 'direct pull', 'Silver Layer Column': 'OPN_BUY_AMT', 'Source Column from Input/PPA': 'Open buy'}, page_content='The main parameter mentioned is the "Open Buy amount", which refers to the cost a customer pays for not meeting the required purchase quantity for a promotion. In the context of PPA mapping for CPG companies, this data point is crucial for calculating promotional costs and understanding pricing strategies, particularly in markets like FLNA Kroger where the Open Buy amount may not align with the Everyday Low Price (EDLP) or Suggested Retail Price (SRP). This data helps in accurately modeling promotional scenarios and analyzing pricing dynamics.\n\nCost the customer pays if they do not purchase the required quantity to redeem the promotion. For FLNA Kroger, unlike other Markets, the Open Buy amount is not necessarily the EDLP/SRP. It may be a discounted price still. ')]

In [ ]:
docs = [
    Document(
        page_content="Complex, layered, rich red with dark fruit flavors",
        metadata={"name":"Opus One", "year": 2018, "rating": 96, "grape": "Cabernet Sauvignon", "color":"red", "country":"USA"},
    ),
    Document(
        page_content="Luxurious, sweet wine with flavors of honey, apricot, and peach",
        metadata={"name":"Château d'Yquem", "year": 2015, "rating": 98, "grape": "Sémillon", "color":"white", "country":"France"},
    ),
    Document(
        page_content="Full-bodied red with notes of black fruit and spice",
        metadata={"name":"Penfolds Grange", "year": 2017, "rating": 97, "grape": "Shiraz", "color":"red", "country":"Australia"},
    ),
    Document(
        page_content="Elegant, balanced red with herbal and berry nuances",
        metadata={"name":"Sassicaia", "year": 2016, "rating": 95, "grape": "Cabernet Franc", "color":"red", "country":"Italy"},
    ),
    Document(
        page_content="Highly sought-after Pinot Noir with red fruit and earthy notes",
        metadata={"name":"Domaine de la Romanée-Conti", "year": 2018, "rating": 100, "grape": "Pinot Noir", "color":"red", "country":"France"},
    ),
    Document(
        page_content="Crisp white with tropical fruit and citrus flavors",
        metadata={"name":"Cloudy Bay", "year": 2021, "rating": 92, "grape": "Sauvignon Blanc", "color":"white", "country":"New Zealand"},
    ),
    Document(
        page_content="Rich, complex Champagne with notes of brioche and citrus",
        metadata={"name":"Krug Grande Cuvée", "year": 2010, "rating": 93, "grape": "Chardonnay blend", "color":"sparkling", "country":"New Zealand"},
    ),
    Document(
        page_content="Intense, dark fruit flavors with hints of chocolate",
        metadata={"name":"Caymus Special Selection", "year": 2018, "rating": 96, "grape": "Cabernet Sauvignon", "color":"red", "country":"USA"},
    ),
    Document(
        page_content="Exotic, aromatic white with stone fruit and floral notes",
        metadata={"name":"Jermann Vintage Tunina", "year": 2020, "rating": 91, "grape": "Sauvignon Blanc blend", "color":"white", "country":"Italy"},
    ),
]
vectorstore = Chroma.from_documents(docs, embeddings)

## Creating our self-querying retriever

In [ ]:
from langchain.llms import OpenAI
from langchain.retrievers.self_query.base import SelfQueryRetriever
from langchain.chains.query_constructor.base import AttributeInfo

metadata_field_info = [
    AttributeInfo(
        name="grape",
        description="The grape used to make the wine",
        type="string or list[string]",
    ),
    AttributeInfo(
        name="name",
        description="The name of the wine",
        type="string or list[string]",
    ),
    AttributeInfo(
        name="color",
        description="The color of the wine",
        type="string or list[string]",
    ),
    AttributeInfo(
        name="year",
        description="The year the wine was released",
        type="integer",
    ),
    AttributeInfo(
        name="country",
        description="The name of the country the wine comes from",
        type="string",
    ),
    AttributeInfo(
        name="rating", description="The Robert Parker rating for the wine 0-100", type="integer" #float
    ),
]
document_content_description = "Brief description of the wine"

In [ ]:
llm = OpenAI(temperature=0)

retriever = SelfQueryRetriever.from_llm(
    llm,
    vectorstore,
    document_content_description,
    metadata_field_info,
    verbose=True
)

In [ ]:
# This example only specifies a relevant query
retriever.get_relevant_documents("What are some red wines")

/usr/local/lib/python3.10/dist-packages/langchain/chains/llm.py:280: UserWarning: The predict_and_parse method is deprecated, instead pass an output parser directly to LLMChain.
  warnings.warn(

query=' ' filter=Comparison(comparator=<Comparator.EQ: 'eq'>, attribute='color', value='red') limit=None

[Document(page_content='Elegant, balanced red with herbal and berry nuances', metadata={'color': 'red', 'country': 'Italy', 'grape': 'Cabernet Franc', 'name': 'Sassicaia', 'rating': 95, 'year': 2016}),
 Document(page_content='Complex, layered, rich red with dark fruit flavors', metadata={'color': 'red', 'country': 'USA', 'grape': 'Cabernet Sauvignon', 'name': 'Opus One', 'rating': 96, 'year': 2018}),
 Document(page_content='Highly sought-after Pinot Noir with red fruit and earthy notes', metadata={'color': 'red', 'country': 'France', 'grape': 'Pinot Noir', 'name': 'Domaine de la Romanée-Conti', 'rating': 100, 'year': 2018}),
 Document(page_content='Intense, dark fruit flavors with hints of chocolate', metadata={'color': 'red', 'country': 'USA', 'grape': 'Cabernet Sauvignon', 'name': 'Caymus Special Selection', 'rating': 96, 'year': 2018})]

In [ ]:

retriever.get_relevant_documents("I want a wine that has fruity nodes")

query='fruity notes' filter=None limit=None

[Document(page_content='Crisp white with tropical fruit and citrus flavors', metadata={'color': 'white', 'country': 'New Zealand', 'grape': 'Sauvignon Blanc', 'name': 'Cloudy Bay', 'rating': 92, 'year': 2021}),
 Document(page_content='Exotic, aromatic white with stone fruit and floral notes', metadata={'color': 'white', 'country': 'Italy', 'grape': 'Sauvignon Blanc blend', 'name': 'Jermann Vintage Tunina', 'rating': 91, 'year': 2020}),
 Document(page_content='Intense, dark fruit flavors with hints of chocolate', metadata={'color': 'red', 'country': 'USA', 'grape': 'Cabernet Sauvignon', 'name': 'Caymus Special Selection', 'rating': 96, 'year': 2018}),
 Document(page_content='Full-bodied red with notes of black fruit and spice', metadata={'color': 'red', 'country': 'Australia', 'grape': 'Shiraz', 'name': 'Penfolds Grange', 'rating': 97, 'year': 2017})]

In [ ]:
# This example specifies a query and a filter
retriever.get_relevant_documents("I want a wine that has fruity nodes and has a rating above 97")

query='fruity' filter=Comparison(comparator=<Comparator.GT: 'gt'>, attribute='rating', value=97) limit=None

[Document(page_content='Luxurious, sweet wine with flavors of honey, apricot, and peach', metadata={'color': 'white', 'country': 'France', 'grape': 'Sémillon', 'name': "Château d'Yquem", 'rating': 98, 'year': 2015}),
 Document(page_content='Highly sought-after Pinot Noir with red fruit and earthy notes', metadata={'color': 'red', 'country': 'France', 'grape': 'Pinot Noir', 'name': 'Domaine de la Romanée-Conti', 'rating': 100, 'year': 2018})]

In [ ]:

retriever.get_relevant_documents(
    "What wines come from Italy?"
)

query=' ' filter=Comparison(comparator=<Comparator.EQ: 'eq'>, attribute='country', value='Italy') limit=None

[Document(page_content='Elegant, balanced red with herbal and berry nuances', metadata={'color': 'red', 'country': 'Italy', 'grape': 'Cabernet Franc', 'name': 'Sassicaia', 'rating': 95, 'year': 2016}),
 Document(page_content='Exotic, aromatic white with stone fruit and floral notes', metadata={'color': 'white', 'country': 'Italy', 'grape': 'Sauvignon Blanc blend', 'name': 'Jermann Vintage Tunina', 'rating': 91, 'year': 2020})]

In [ ]:
# This example specifies a query and composite filter
retriever.get_relevant_documents(
    "What's a wine after 2015 but before 2020 that's all earthy"
)

query='earthy' filter=Operation(operator=<Operator.AND: 'and'>, arguments=[Comparison(comparator=<Comparator.GT: 'gt'>, attribute='year', value=2015), Comparison(comparator=<Comparator.LT: 'lt'>, attribute='year', value=2020)]) limit=None

[Document(page_content='Elegant, balanced red with herbal and berry nuances', metadata={'color': 'red', 'country': 'Italy', 'grape': 'Cabernet Franc', 'name': 'Sassicaia', 'rating': 95, 'year': 2016}),
 Document(page_content='Highly sought-after Pinot Noir with red fruit and earthy notes', metadata={'color': 'red', 'country': 'France', 'grape': 'Pinot Noir', 'name': 'Domaine de la Romanée-Conti', 'rating': 100, 'year': 2018}),
 Document(page_content='Full-bodied red with notes of black fruit and spice', metadata={'color': 'red', 'country': 'Australia', 'grape': 'Shiraz', 'name': 'Penfolds Grange', 'rating': 97, 'year': 2017}),
 Document(page_content='Complex, layered, rich red with dark fruit flavors', metadata={'color': 'red', 'country': 'USA', 'grape': 'Cabernet Sauvignon', 'name': 'Opus One', 'rating': 96, 'year': 2018})]

## Filter K

We can also use the self query retriever to specify k: the number of documents to fetch.

We can do this by passing enable_limit=True to the constructor.

In [ ]:
retriever = SelfQueryRetriever.from_llm(
    llm,
    vectorstore,
    document_content_description,
    metadata_field_info,
    enable_limit=True,
    verbose=True,
)

In [ ]:
# This example only specifies a relevant query - k= 2
retriever.get_relevant_documents("what are two that have a rating above 97")

query=' ' filter=Comparison(comparator=<Comparator.GT: 'gt'>, attribute='rating', value=97) limit=2

[Document(page_content='Luxurious, sweet wine with flavors of honey, apricot, and peach', metadata={'color': 'white', 'country': 'France', 'grape': 'Sémillon', 'name': "Château d'Yquem", 'rating': 98, 'year': 2015}),
 Document(page_content='Highly sought-after Pinot Noir with red fruit and earthy notes', metadata={'color': 'red', 'country': 'France', 'grape': 'Pinot Noir', 'name': 'Domaine de la Romanée-Conti', 'rating': 100, 'year': 2018})]

In [ ]:
retriever.get_relevant_documents("what are two wines that come from australia or New zealand")

query=' ' filter=Operation(operator=<Operator.OR: 'or'>, arguments=[Comparison(comparator=<Comparator.EQ: 'eq'>, attribute='country', value='Australia'), Comparison(comparator=<Comparator.EQ: 'eq'>, attribute='country', value='New Zealand')]) limit=2

[Document(page_content='Crisp white with tropical fruit and citrus flavors', metadata={'color': 'white', 'country': 'New Zealand', 'grape': 'Sauvignon Blanc', 'name': 'Cloudy Bay', 'rating': 92, 'year': 2021}),
 Document(page_content='Full-bodied red with notes of black fruit and spice', metadata={'color': 'red', 'country': 'Australia', 'grape': 'Shiraz', 'name': 'Penfolds Grange', 'rating': 97, 'year': 2017})]

In [14]:
definition_set = [{'CUST_HASH_CMPST_KEY': {'definition': 'Represents the Customer Hash Composite Key, a unique identifier for customer records created using a hash function to ensure integrity across systems.',
   'Type': 'Bigint',
   'Table': 'dim_customer'}},
 {'MU': {'definition': 'The Business Unit break-down within a Cluster',
   'Type': 'String',
   'Table': 'dim_customer'}},
 {'BU': {'definition': 'The Market Unit break-down within a Business Unit',
   'Type': 'String',
   'Table': 'dim_customer'}},
 {'datetime': {'definition': 'Represents the Timestamp, marking when the record was created or last modified.',
   'Type': 'Timestamp',
   'Table': 'dim_customer'}},
 {'SLS_GEO_HASH_CMPST_KEY': {'definition': 'Represents a unique hashed composite key that identifies specific sales geographies, combining multiple attributes for efficient indexing and lookup.',
   'Type': 'Bigint',
   'Table': 'dim_salesgeo'}},
 {'LFL_FLG': {'definition': 'The Like for Like flag. Like for Like refers to the method of financial comparison by eliminating transactions from prior periods that no longer apply to the current time period.',
   'Type': 'String',
   'Table': 'dim_salesgeo'}},
 {'RGN': {'definition': 'Strategic Cluster. It classifies for Beverages, the markets depending on the Share versus Coke',
   'Type': 'String',
   'Table': 'dim_salesgeo'}},
 {'CLSTR': {'definition': 'The Cluster break-down within a Sector',
   'Type': 'String',
   'Table': 'dim_salesgeo'}},
 {'SCTR': {'definition': 'The highest level functional organizational structure of PepsiCo, which will be broken down further by Business Unit, then Market Unit.',
   'Type': 'String',
   'Table': 'dim_salesgeo'}},
 {'datetime': {'definition': 'Represents the Timestamp, marking when the record was created or last modified.',
   'Type': 'Timestamp',
   'Table': 'dim_salesgeo'}},
 {'TME_HASH_CMPST_KEY': {'definition': 'Represents a unique hashed composite key for identifying specific time-related dimensions, combining multiple time attributes for efficient querying',
   'Type': 'Bigint',
   'Table': 'dim_time'}},
 {'QRTR': {'definition': 'The calendar Quarter within a Year, Q1 through Q4.',
   'Type': 'String',
   'Table': 'dim_time'}},
 {'PRD': {'definition': 'The numeric portion of the 4 week time Periods that PepsiCo breaks down their financials into. The periods are P1 through P13, and this fields contains the numeric portion of those values.',
   'Type': 'Int',
   'Table': 'dim_time'}},
 {'FCST_MNTH': {'definition': 'In general terms, this refers to the Period that the Forecast begins in and then continues through the rest of the Periods through the end of the Year. For example, a Forecast Month of "2" means Period 1 and 2 as Actuals, and P3 through Period 13 Forecasts. There are many special conditions for this column that must be considered.',
   'Type': 'Int',
   'Table': 'dim_time'}},
 {'datetime': {'definition': 'Represents the Timestamp, marking when the record was created or last modified.',
   'Type': 'Timestamp',
   'Table': 'dim_time'}},
 {'FINC_HASH_CMPST_KEY': {'definition': 'Stands for Finance Hash Composite Key, a hashed unique identifier for financial data records, enabling efficient data linkage and retrieval.',
   'Type': 'Bigint',
   'Table': 'dim_finance'}},
 {'BU_ACCT_LVL_1': {'definition': 'The highest level in the Account Hierarchy, this generally correlates to the actual P&L Metric that the transaction is related to.',
   'Type': 'String',
   'Table': 'dim_finance'}},
 {'BU_ACCT_LVL_2': {'definition': 'The subtype of the Account Level 1 that further breaks down the account hierarchy.',
   'Type': 'String',
   'Table': 'dim_finance'}},
 {'BU_ACCT_LVL_3': {'definition': 'The subtype of the Account Level 2 that further breaks down the account hierarchy',
   'Type': 'String',
   'Table': 'dim_finance'}},
 {'ACCT_TYP': {'definition': 'The classification that designates the source of the transaction. This can be from the Income Statement, Cash Flow, Brand P&L, Cause of Change records or other type designations.',
   'Type': 'String',
   'Table': 'dim_finance'}},
 {'datetime': {'definition': 'Represents the Timestamp, marking when the record was created or last modified.',
   'Type': 'Timestamp',
   'Table': 'dim_finance'}},
 {'GTM_HASH_CMPST_KEY': {'definition': 'Refers to the Go-To-Market Hash Composite Key, uniquely identifying go-to-market strategies or operations within the data.',
   'Type': 'Bigint',
   'Table': 'dim_gotomarket'}},
 {'datetime': {'definition': 'Represents the Timestamp, marking when the record was created or last modified.',
   'Type': 'Timestamp',
   'Table': 'dim_gotomarket'}},
 {'PRDT_HASH_CMPST_KEY': {'definition': 'Represents the Product Hash Composite Key, a unique identifier for the product record. This hashed key helps ensure data integrity and simplifies the process of identifying and linking products across systems.',
   'Type': 'Bigint',
   'Table': 'dim_product'}},
 {'datetime': {'definition': 'Represents the Timestamp, marking when the record was created or last modified.',
   'Type': 'Timestamp',
   'Table': 'dim_product'}},
 {'LOCL_ORG_HASH_CMPST_KEY': {'definition': 'Represents a unique hashed composite key to identify specific local organizational entities, combining multiple attributes for efficient lookups.',
   'Type': 'Bigint',
   'Table': 'dim_localorg'}},
 {'datetime': {'definition': 'Represents the Timestamp, marking when the record was created or last modified.',
   'Type': 'Timestamp',
   'Table': 'dim_localorg'}}]
column = "CUST_HASH_CMPST_KEY"
for i in definition_set:
    if column in i.keys():
        table = i[column]["Table"]

filtered_definition_set = []
for i in definition_set:
    values = list(i.values())
    # print(values)
    if values[0]["Table"] == table:
        filtered_definition_set.append(i)

print(filtered_definition_set)

[{'CUST_HASH_CMPST_KEY': {'definition': 'Represents the Customer Hash Composite Key, a unique identifier for customer records created using a hash function to ensure integrity across systems.', 'Type': 'Bigint', 'Table': 'dim_customer'}}, {'MU': {'definition': 'The Business Unit break-down within a Cluster', 'Type': 'String', 'Table': 'dim_customer'}}, {'BU': {'definition': 'The Market Unit break-down within a Business Unit', 'Type': 'String', 'Table': 'dim_customer'}}, {'datetime': {'definition': 'Represents the Timestamp, marking when the record was created or last modified.', 'Type': 'Timestamp', 'Table': 'dim_customer'}}]

In [15]:
len(filtered_definition_set)

4