In [1]:
import pandas as pd

In [8]:
acceptions = pd.read_csv("/home/ec2-user/Pepsico_Hackathon/Pepsico_Main_Hackathon/Pepsico_demo_new_gen_mapping_approach/accepted_list.csv")
acceptions["Silver Layer Column"].to_list()

['COGS_AMOUNT',
 'DSCNT_AMT',
 'PRMTN_ALWNC_DSCNT_AMT',
 'BB_DSCNT_AMT',
 'MCHNC_PRC_AMT',
 'PROD_ATRBT_1_VAL']

In [12]:
accepted_list = acceptions["accepted_match"].to_list()
accepted_list
# [x.split(", ") for x in ]

[nan, nan, nan, nan, nan, 'PPG, Event_Timeline']

In [19]:
accepted_list = ['PPG_er','PPG, Event_Timeline']
accepted_list_exploded = []
for i in [x.split(", ") for x in accepted_list]:
    accepted_list_exploded.extend(i)
list(set(accepted_list_exploded))

['Event_Timeline', 'PPG', 'PPG_er']

In [3]:
a = [1, 2, 3, 4, 5]
b = [9, 8, 7, 6, 5]
set(a) & set(b)

{5}

In [5]:
set(a).difference(set(b))

{1, 2, 3, 4}

In [4]:
list(set(a).intersection(set(b)))

[5]

In [21]:
import os
os.stat("/home/ec2-user/Pepsico_Hackathon/Pepsico_Main_Hackathon/Pepsico_demo_new_gen_mapping_approach/accepted_list.csv")

os.stat_result(st_mode=33204, st_ino=101461701, st_dev=51713, st_nlink=1, st_uid=1000, st_gid=1000, st_size=1, st_atime=1732530109, st_mtime=1732530109, st_ctime=1732530109)

In [24]:
rejections = pd.read_csv("/home/ec2-user/Pepsico_Hackathon/Pepsico_Main_Hackathon/Pepsico_demo_new_gen_mapping_approach/rejected_list.csv")
rejections_filtered = rejections[rejections["Silver Layer Column"] == "BB_DSCNT_AMT"]
rejections_filtered["rejected_match"].values[0].split(", ")

['PA', 'Random']

In [2]:
import sqlite3, pandas as pd
conn = sqlite3.connect("/home/ec2-user/Pepsico_Hackathon/Pepsico_Main_Hackathon/Pepsico_demo_new_gen_mapping_approach/pepsico_master.db")
cur=conn.cursor()
#st.write(tables[1][0])
table_name = "Retailer_Schema_Questions"
retailer = "DG"
sector = "PBNA"
cur.execute(f"SELECT * FROM {table_name} WHERE Retailer=? COLLATE NOCASE AND Sector=? COLLATE NOCASE ORDER BY Count DESC LIMIT 5", (retailer, sector))
op_5_question_list = cur.fetchall()
column = [col[0] for col in cur.description]
pd.DataFrame(op_5_question_list, columns=column)

,Id,Session_Id,Header_Row,Dividers,Anchors,Comments_or_other_data,Reoccurring_Similar_header_row,Repetitive_horizontal_tables,Question,Sector,Retailer,Count,Created_By,Created_Date
0,5,PBNA_DG_b9321724-39d4-4258-9d7b-ca321607d303,YES,YES,NO,YES,YES,NO,"Rename Category column to ""Event_Timeline""",PBNA,DG,9,Admin,11/4/2024 14:32
1,1,PBNA_DG_b9321724-39d4-4258-9d7b-ca321607d303,YES,YES,NO,YES,YES,NO,"Rename ""Sheet_name"" column to ""PPG""",PBNA,DG,3,Admin,11/4/2024 14:31
2,4,PBNA_DG_b9321724-39d4-4258-9d7b-ca321607d303,YES,YES,NO,YES,YES,NO,Rename '2024 EVENT ? PROMO' column to 'Offer',PBNA,DG,23,Admin,11/4/2024 14:30
3,6,PBNA_DG_b9321724-39d4-4258-9d7b-ca321607d303,YES,YES,NO,YES,YES,NO,"Drop ""Event_Timeline"" Column",PBNA,DG,1,Admin,11/4/2024 14:36

In [36]:
cur.execute("DELETE FROM Retailer_Schema_Questions WHERE session_id = 'PBNA_Target_0648c8eb-ee0b-4f18-a7be-7fec68d1ef1e';")
conn.commit()

In [16]:
cur.description

(('Id', None, None, None, None, None, None),
 ('Session_Id', None, None, None, None, None, None),
 ('Header_Row', None, None, None, None, None, None),
 ('Dividers', None, None, None, None, None, None),
 ('Anchors', None, None, None, None, None, None),
 ('Comments_or_other_data', None, None, None, None, None, None),
 ('Reoccurring_Similar_header_row', None, None, None, None, None, None),
 ('Repetitive_horizontal_tables', None, None, None, None, None, None),
 ('Question', None, None, None, None, None, None),
 ('Sector', None, None, None, None, None, None),
 ('Retailer', None, None, None, None, None, None),
 ('Count', None, None, None, None, None, None),
 ('Created_By', None, None, None, None, None, None),
 ('Created_Date', None, None, None, None, None, None))

In [22]:
import json
from datetime import datetime
import uuid

schema_list = [{
  "Column List": [
    "2023 TARGET CSD PROMO PRICING CALENDAR",
    "2023",
    "2023",
    "2023",
    "2023",
    "MM = Mandated Multiple (Must Buy)",
    "PEP 12pk cans",
    "Dr Pepper 12pk cans",
    "CSD 6pk PET",
    "CSD 2L bottles",
    "CSD 24pk cans",
    "CSD 10pk mini cans",
    "Bundaberg 4pk bottles",
    "20oz PET"
  ],
  "Header Row": {
    "is_present": "YES"
  },
  "Dividers": {
    "is_present": "NO"
  },
  "Anchors": {
    "is_present": "NO"
  },
  "Comments or other data": {
    "is_present": "YES"
  },
  "Reccuring/Similar header row": {
    "is_present": "NO"
  },
  "Repetitive horizontal tables": {
    "is_present": "NO"
  }
}]
for schema in schema_list:
    del schema["Column List"]
unique_schema_dicts = {json.dumps(d, sort_keys=True) for d in schema_list}

unique_schema_list = [json.loads(j) for j in unique_schema_dicts]

# print(unique_schema_list)
for schema in unique_schema_list:

    schema_temp = {key.replace(" ","_").replace("/","_").replace("Reccuring_Similar_header_row","Reoccurring_Similar_header_row"): schema[key] for key in schema}
    schema_temp["Question"] = 'Rename "2023\nTGT WK" column to "Target Week"'
    schema_temp["Retailer"] = retailer
    schema_temp["Sector"] = sector
    schema_temp["Count"] = 1
    schema_temp["Created_By"] = "Admin"
    schema_temp["Created_Date"] = datetime.now().strftime('%Y/%m/%d %H:%M:%S')
    schema_temp["Session_Id"] = f"{sector}_{retailer}_{str(uuid.uuid4())}"

    print(schema_temp)
    column_values = ", ".join([f'"{key}"' for key in schema_temp.keys()])
    actual_values = ", ".join([f"""'{value["is_present"]}'""" if type(value) == dict else f"'{value}'" for value in schema_temp.values()])

    insert_query = f"INSERT INTO Retailer_Schema_Questions ({column_values}) VALUES ({actual_values});"
    print(insert_query)
    cur.execute(insert_query)
    conn.commit()

{'Anchors': {'is_present': 'NO'}, 'Comments_or_other_data': {'is_present': 'YES'}, 'Dividers': {'is_present': 'NO'}, 'Header_Row': {'is_present': 'YES'}, 'Reoccurring_Similar_header_row': {'is_present': 'NO'}, 'Repetitive_horizontal_tables': {'is_present': 'NO'}, 'Question': 'Rename "2023\nTGT WK" column to "Target Week"', 'Retailer': 'DG', 'Sector': 'PBNA', 'Count': 1, 'Created_By': 'Admin', 'Created_Date': '2024/11/26 11:19:21', 'Session_Id': 'PBNA_DG_b4b935a1-f52e-4803-b2a5-1ade943430ce'}
INSERT INTO Retailer_Schema_Questions ("Anchors", "Comments_or_other_data", "Dividers", "Header_Row", "Reoccurring_Similar_header_row", "Repetitive_horizontal_tables", "Question", "Retailer", "Sector", "Count", "Created_By", "Created_Date", "Session_Id") VALUES ('NO', 'YES', 'NO', 'YES', 'NO', 'NO', 'Rename "2023
TGT WK" column to "Target Week"', 'DG', 'PBNA', '1', 'Admin', '2024/11/26 11:19:21', 'PBNA_DG_b4b935a1-f52e-4803-b2a5-1ade943430ce');

In [33]:
if "False" in """False

The sentence is referring to renaming a column, not combining dataframes or providing logic for a merge process.""":
    print("HELLO")

HELLO

In [2]:
if "" and "":
    print("TRUE")

### Data Combination Fine-Tuning

In [1]:
from langchain_databricks import ChatDatabricks
import os
os.environ["DATABRICKS_HOST"] = "https://adb-6926527074777965.5.azuredatabricks.net"
os.environ["DATABRICKS_TOKEN"] = "dapi477662799536f4c6227fc9ba317d49f8-3"

llm_pa= ChatDatabricks(
        endpoint = "databricks-meta-llama-3-1-70b-instruct",
        max_tokens=8192,
        temperature=0,
    )

questions_list = ['Do an outer join and provide the final dataframe','just provide the merged dataframe',"Pivot the columns PEP 12pk cans,Dr Pepper 12pk cans,CSD 6pk PET,CSD 2L bottles,CSD 24pk cans,CSD 10pk mini cans,Bundaberg 4pk bottles,20oz PET into rows under a single column named 'Product'"]

is_combination = llm_pa.invoke(f"""
                <|begin_of_text|><|start_header_id|>system<|end_header_id|>
                You are an AI assistant data engineer who is expert at interpreting the semantic meaning of the provided sentence and identifying data merge instructions.
                Respond True only if either one of the below points is satisfied, otherwise False.
                1) Given sentence is referring to combining multiple dataframes or
                2) if it is in any way providing some logic on how that data merge process accross multiple dataframes should take place and not within the dataframe itself or
                3) if it is not providing any logic and just asking for the final dataframe.
                (Answer in either True or False)
                |eot_id|><|start_header_id|>user<|end_header_id|>
                Sentence: {questions_list[-1]}
                <|eot_id|><|start_header_id|>assistant<|end_header_id|>
                """).content
print(is_combination)

False

The sentence is referring to transforming or pivoting data within a single dataframe, not merging multiple dataframes.

### Pandas AI Agent without description

In [ ]:
from pandasai import Agent
import pandas as pd
df = pd.read_csv("/home/ec2-user/Pepsico_Hackathon/Pepsico_Main_Hackathon/Pepsico_demo_new_gen_mapping_approach/modified_files/2023 CSD Target Activity CalendarCSD Promo Activity 2023_header.csv")
pandas_ai_agent_with_new_df = Agent(df,config={"llm": llm_pa, "enforce_privacy": True, "verbose": True, "enable_cache":False, "max_retries": 10})
response = pandas_ai_agent_with_new_df.chat("Pivot the columns PEP 12pk cans,Dr Pepper 12pk cans,CSD 6pk PET,CSD 2L bottles,CSD 24pk cans,CSD 10pk mini cans,Bundaberg 4pk bottles,20oz PET into rows under a single column named 'Product'", output_type="dataframe")
response

2024-11-27 11:45:50 [INFO] Question: Pivot the columns PEP 12pk cans,Dr Pepper 12pk cans,CSD 6pk PET,CSD 2L bottles,CSD 24pk cans,CSD 10pk mini cans,Bundaberg 4pk bottles,20oz PET into rows under a single column named 'Product'
2024-11-27 11:45:50 [INFO] Running PandasAI with langchain_chat-databricks LLM...
2024-11-27 11:45:50 [INFO] Prompt ID: e0332360-24e0-4504-b076-4bbbe80a525b
2024-11-27 11:45:50 [INFO] Executing Pipeline: GenerateChatPipeline
2024-11-27 11:45:50 [INFO] Executing Step 0: ValidatePipelineInput
2024-11-27 11:45:50 [INFO] Executing Step 1: CacheLookup
2024-11-27 11:45:50 [INFO] Executing Step 2: PromptGeneration
2024-11-27 11:45:50 [INFO] Using prompt: <dataframe>
dfs[0]:57x14
"2023
PEP Period","2023
PEP WK","2023
TGT WK","2023
Sunday Start",TPM Pending Close,"2023
CSD AD",PEP 12pk cans,Dr Pepper 12pk cans,CSD 6pk PET,CSD 2L bottles,CSD 24pk cans,CSD 10pk mini cans,Bundaberg 4pk bottles,20oz PET
P2W4,44,Mar wk2,2023-11-19 00:00:00,2023-07-01 00:00:00,KO 12pks feature 3/$18 MM (KDP/PEP included),2/$11; 20% TC 387743,"Buy 3, save 50%","2/$8 TPC
344906726",4/$9 TPC,"TC 15% Off 389145
",3/$15,"$5.89 TPC
216211993",EDV
P6W2,21,May wk4,2023-02-26 00:00:00,2023-04-22 00:00:00,"6/25 - 7/4 Tri-Man  - 3/$15 +25% Circle
737244662",3/$15 + 25% TC,3/$18,EDV,3/$6 TPC,EDV,2/$11 TPC,EDV,EDV
P10W1,32,May wk3,2023-06-18 00:00:00,2023-12-30 00:00:00,PEP/KDP 3/$15 MB +25% TC Digital,"25% Circle
393947","Spend $15, Save $3",4/$14 TPC,"3/$6 TPC
362894325","TC 15% Off 395643
",EDV,$5.89 TPC,EDV
</dataframe>




Update this initial code:
```python
# TODO: import the required dependencies
import pandas as pd

# Write code here

# Declare result var:
type (must be "dataframe"), value must be pd.DataFrame or pd.Series. Example: { "type": "dataframe", "value": pd.DataFrame({...}) }

```



### QUERY
 Pivot the columns PEP 12pk cans,Dr Pepper 12pk cans,CSD 6pk PET,CSD 2L bottles,CSD 24pk cans,CSD 10pk mini cans,Bundaberg 4pk bottles,20oz PET into rows under a single column named 'Product'

Variable `dfs: list[pd.DataFrame]` is already declared.

At the end, declare "result" variable as a dictionary of type and value.

If you are asked to plot a chart, use "matplotlib" for charts, save as png.


Generate python code and return full updated code:
2024-11-27 11:45:50 [INFO] Executing Step 3: CodeGenerator
2024-11-27 11:45:55 [INFO] Prompt used:

<dataframe>
dfs[0]:57x14
"2023
PEP Period","2023
PEP WK","2023
TGT WK","2023
Sunday Start",TPM Pending Close,"2023
CSD AD",PEP 12pk cans,Dr Pepper 12pk cans,CSD 6pk PET,CSD 2L bottles,CSD 24pk cans,CSD 10pk mini cans,Bundaberg 4pk bottles,20oz PET
P2W4,44,Mar wk2,2023-11-19 00:00:00,2023-07-01 00:00:00,KO 12pks feature 3/$18 MM (KDP/PEP included),2/$11; 20% TC 387743,"Buy 3, save 50%","2/$8 TPC
344906726",4/$9 TPC,"TC 15% Off 389145
",3/$15,"$5.89 TPC
216211993",EDV
P6W2,21,May wk4,2023-02-26 00:00:00,2023-04-22 00:00:00,"6/25 - 7/4 Tri-Man  - 3/$15 +25% Circle
737244662",3/$15 + 25% TC,3/$18,EDV,3/$6 TPC,EDV,2/$11 TPC,EDV,EDV
P10W1,32,May wk3,2023-06-18 00:00:00,2023-12-30 00:00:00,PEP/KDP 3/$15 MB +25% TC Digital,"25% Circle
393947","Spend $15, Save $3",4/$14 TPC,"3/$6 TPC
362894325","TC 15% Off 395643
",EDV,$5.89 TPC,EDV
</dataframe>




Update this initial code:
```python
# TODO: import the required dependencies
import pandas as pd

# Write code here

# Declare result var:
type (must be "dataframe"), value must be pd.DataFrame or pd.Series. Example: { "type": "dataframe", "value": pd.DataFrame({...}) }

```



### QUERY
 Pivot the columns PEP 12pk cans,Dr Pepper 12pk cans,CSD 6pk PET,CSD 2L bottles,CSD 24pk cans,CSD 10pk mini cans,Bundaberg 4pk bottles,20oz PET into rows under a single column named 'Product'

Variable `dfs: list[pd.DataFrame]` is already declared.

At the end, declare "result" variable as a dictionary of type and value.

If you are asked to plot a chart, use "matplotlib" for charts, save as png.


Generate python code and return full updated code:

2024-11-27 11:45:55 [INFO] Code generated:
            ```
            # TODO: import the required dependencies
import pandas as pd

# Write code here
# Assuming dfs is a list of dataframes
df = dfs[0]  # Select the first dataframe from the list

# Melt the dataframe to pivot the columns into rows
df_melted = pd.melt(df, id_vars=['2023 PEP Period', '2023 PEP WK', '2023 TGT WK', '2023 Sunday Start', 'TPM Pending Close', '2023 CSD AD'],
                    value_vars=['PEP 12pk cans', 'Dr Pepper 12pk cans', 'CSD 6pk PET', 'CSD 2L bottles', 'CSD 24pk cans', 'CSD 10pk mini cans', 'Bundaberg 4pk bottles', '20oz PET'],
                    var_name='Product', value_name='Value')

# Declare result var:
result = { "type": "dataframe", "value": df_melted }
            ```

2024-11-27 11:45:55 [INFO] Executing Step 4: CachePopulation
2024-11-27 11:45:55 [INFO] Executing Step 5: CodeCleaning
2024-11-27 11:45:55 [INFO]
Code running:
```
df = dfs[0]
df_melted = pd.melt(df, id_vars=['2023 PEP Period', '2023 PEP WK', '2023 TGT WK', '2023 Sunday Start', 'TPM Pending Close', '2023 CSD AD'], value_vars=['PEP 12pk cans', 'Dr Pepper 12pk cans', 'CSD 6pk PET', 'CSD 2L bottles', 'CSD 24pk cans', 'CSD 10pk mini cans', 'Bundaberg 4pk bottles', '20oz PET'], var_name='Product', value_name='Value')
result = {'type': 'dataframe', 'value': df_melted}
        ```
2024-11-27 11:45:55 [INFO] Executing Step 6: CodeExecution
2024-11-27 11:45:55 [ERROR] Failed with error: Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandasai/pipelines/chat/code_execution.py", line 85, in execute
    result = self.execute_code(code_to_run, code_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandasai/pipelines/chat/code_execution.py", line 171, in execute_code
    exec(code, environment)
  File "<string>", line 2, in <module>
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandas/core/reshape/melt.py", line 77, in melt
    raise KeyError(
KeyError: "The following 'id_vars' are not present in the DataFrame: ['2023 CSD AD', '2023 PEP Period', '2023 PEP WK', '2023 Sunday Start', '2023 TGT WK']"

2024-11-27 11:45:55 [WARNING] Failed to execute code retrying with a correction framework [retry number: 1]
2024-11-27 11:45:55 [INFO] Executing Pipeline: ErrorCorrectionPipeline
2024-11-27 11:45:55 [INFO] Executing Step 0: ErrorPromptGeneration
2024-11-27 11:45:55 [INFO] Using prompt: <dataframe>
dfs[0]:57x14
"2023
PEP Period","2023
PEP WK","2023
TGT WK","2023
Sunday Start",TPM Pending Close,"2023
CSD AD",PEP 12pk cans,Dr Pepper 12pk cans,CSD 6pk PET,CSD 2L bottles,CSD 24pk cans,CSD 10pk mini cans,Bundaberg 4pk bottles,20oz PET
P2W4,44,Mar wk2,2023-11-19 00:00:00,2023-07-01 00:00:00,KO 12pks feature 3/$18 MM (KDP/PEP included),2/$11; 20% TC 387743,"Buy 3, save 50%","2/$8 TPC
344906726",4/$9 TPC,"TC 15% Off 389145
",3/$15,"$5.89 TPC
216211993",EDV
P6W2,21,May wk4,2023-02-26 00:00:00,2023-04-22 00:00:00,"6/25 - 7/4 Tri-Man  - 3/$15 +25% Circle
737244662",3/$15 + 25% TC,3/$18,EDV,3/$6 TPC,EDV,2/$11 TPC,EDV,EDV
P10W1,32,May wk3,2023-06-18 00:00:00,2023-12-30 00:00:00,PEP/KDP 3/$15 MB +25% TC Digital,"25% Circle
393947","Spend $15, Save $3",4/$14 TPC,"3/$6 TPC
362894325","TC 15% Off 395643
",EDV,$5.89 TPC,EDV
</dataframe>


The user asked the following question:
### QUERY
 Pivot the columns PEP 12pk cans,Dr Pepper 12pk cans,CSD 6pk PET,CSD 2L bottles,CSD 24pk cans,CSD 10pk mini cans,Bundaberg 4pk bottles,20oz PET into rows under a single column named 'Product'

You generated this python code:
df = dfs[0]
df_melted = pd.melt(df, id_vars=['2023 PEP Period', '2023 PEP WK', '2023 TGT WK', '2023 Sunday Start', 'TPM Pending Close', '2023 CSD AD'], value_vars=['PEP 12pk cans', 'Dr Pepper 12pk cans', 'CSD 6pk PET', 'CSD 2L bottles', 'CSD 24pk cans', 'CSD 10pk mini cans', 'Bundaberg 4pk bottles', '20oz PET'], var_name='Product', value_name='Value')
result = {'type': 'dataframe', 'value': df_melted}

It fails with the following error:
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandasai/pipelines/chat/code_execution.py", line 85, in execute
    result = self.execute_code(code_to_run, code_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandasai/pipelines/chat/code_execution.py", line 171, in execute_code
    exec(code, environment)
  File "<string>", line 2, in <module>
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandas/core/reshape/melt.py", line 77, in melt
    raise KeyError(
KeyError: "The following 'id_vars' are not present in the DataFrame: ['2023 CSD AD', '2023 PEP Period', '2023 PEP WK', '2023 Sunday Start', '2023 TGT WK']"


Fix the python code above and return the new python code:
2024-11-27 11:45:55 [INFO] Executing Step 1: CodeGenerator
2024-11-27 11:46:00 [INFO] Prompt used:

<dataframe>
dfs[0]:57x14
"2023
PEP Period","2023
PEP WK","2023
TGT WK","2023
Sunday Start",TPM Pending Close,"2023
CSD AD",PEP 12pk cans,Dr Pepper 12pk cans,CSD 6pk PET,CSD 2L bottles,CSD 24pk cans,CSD 10pk mini cans,Bundaberg 4pk bottles,20oz PET
P2W4,44,Mar wk2,2023-11-19 00:00:00,2023-07-01 00:00:00,KO 12pks feature 3/$18 MM (KDP/PEP included),2/$11; 20% TC 387743,"Buy 3, save 50%","2/$8 TPC
344906726",4/$9 TPC,"TC 15% Off 389145
",3/$15,"$5.89 TPC
216211993",EDV
P6W2,21,May wk4,2023-02-26 00:00:00,2023-04-22 00:00:00,"6/25 - 7/4 Tri-Man  - 3/$15 +25% Circle
737244662",3/$15 + 25% TC,3/$18,EDV,3/$6 TPC,EDV,2/$11 TPC,EDV,EDV
P10W1,32,May wk3,2023-06-18 00:00:00,2023-12-30 00:00:00,PEP/KDP 3/$15 MB +25% TC Digital,"25% Circle
393947","Spend $15, Save $3",4/$14 TPC,"3/$6 TPC
362894325","TC 15% Off 395643
",EDV,$5.89 TPC,EDV
</dataframe>


The user asked the following question:
### QUERY
 Pivot the columns PEP 12pk cans,Dr Pepper 12pk cans,CSD 6pk PET,CSD 2L bottles,CSD 24pk cans,CSD 10pk mini cans,Bundaberg 4pk bottles,20oz PET into rows under a single column named 'Product'

You generated this python code:
df = dfs[0]
df_melted = pd.melt(df, id_vars=['2023 PEP Period', '2023 PEP WK', '2023 TGT WK', '2023 Sunday Start', 'TPM Pending Close', '2023 CSD AD'], value_vars=['PEP 12pk cans', 'Dr Pepper 12pk cans', 'CSD 6pk PET', 'CSD 2L bottles', 'CSD 24pk cans', 'CSD 10pk mini cans', 'Bundaberg 4pk bottles', '20oz PET'], var_name='Product', value_name='Value')
result = {'type': 'dataframe', 'value': df_melted}

It fails with the following error:
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandasai/pipelines/chat/code_execution.py", line 85, in execute
    result = self.execute_code(code_to_run, code_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandasai/pipelines/chat/code_execution.py", line 171, in execute_code
    exec(code, environment)
  File "<string>", line 2, in <module>
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandas/core/reshape/melt.py", line 77, in melt
    raise KeyError(
KeyError: "The following 'id_vars' are not present in the DataFrame: ['2023 CSD AD', '2023 PEP Period', '2023 PEP WK', '2023 Sunday Start', '2023 TGT WK']"


Fix the python code above and return the new python code:

2024-11-27 11:46:00 [INFO] Code generated:
            ```
            df = dfs[0]
df.columns = df.columns.str.strip()  # Remove leading and trailing whitespace from column names
df_melted = pd.melt(df, id_vars=['2023 PEP Period', '2023 PEP WK', '2023 TGT WK', '2023 Sunday Start', 'TPM Pending Close', '2023 CSD AD'],
                     value_vars=['PEP 12pk cans', 'Dr Pepper 12pk cans', 'CSD 6pk PET', 'CSD 2L bottles', 'CSD 24pk cans', 'CSD 10pk mini cans', 'Bundaberg 4pk bottles', '20oz PET'],
                     var_name='Product', value_name='Value')
result = {'type': 'dataframe', 'value': df_melted}
            ```

2024-11-27 11:46:00 [INFO] Executing Step 2: CodeCleaning
2024-11-27 11:46:00 [INFO]
Code running:
```
df = dfs[0]
df.columns = df.columns.str.strip()
df_melted = pd.melt(df, id_vars=['2023 PEP Period', '2023 PEP WK', '2023 TGT WK', '2023 Sunday Start', 'TPM Pending Close', '2023 CSD AD'], value_vars=['PEP 12pk cans', 'Dr Pepper 12pk cans', 'CSD 6pk PET', 'CSD 2L bottles', 'CSD 24pk cans', 'CSD 10pk mini cans', 'Bundaberg 4pk bottles', '20oz PET'], var_name='Product', value_name='Value')
result = {'type': 'dataframe', 'value': df_melted}
        ```
2024-11-27 11:46:01 [ERROR] Failed with error: Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandasai/pipelines/chat/code_execution.py", line 85, in execute
    result = self.execute_code(code_to_run, code_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandasai/pipelines/chat/code_execution.py", line 171, in execute_code
    exec(code, environment)
  File "<string>", line 3, in <module>
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandas/core/reshape/melt.py", line 77, in melt
    raise KeyError(
KeyError: "The following 'id_vars' are not present in the DataFrame: ['2023 CSD AD', '2023 PEP Period', '2023 PEP WK', '2023 Sunday Start', '2023 TGT WK']"

2024-11-27 11:46:01 [WARNING] Failed to execute code retrying with a correction framework [retry number: 2]
2024-11-27 11:46:01 [INFO] Executing Pipeline: ErrorCorrectionPipeline
2024-11-27 11:46:01 [INFO] Executing Step 0: ErrorPromptGeneration
2024-11-27 11:46:01 [INFO] Using prompt: <dataframe>
dfs[0]:57x14
"2023
PEP Period","2023
PEP WK","2023
TGT WK","2023
Sunday Start",TPM Pending Close,"2023
CSD AD",PEP 12pk cans,Dr Pepper 12pk cans,CSD 6pk PET,CSD 2L bottles,CSD 24pk cans,CSD 10pk mini cans,Bundaberg 4pk bottles,20oz PET
P2W4,44,Mar wk2,2023-11-19 00:00:00,2023-07-01 00:00:00,KO 12pks feature 3/$18 MM (KDP/PEP included),2/$11; 20% TC 387743,"Buy 3, save 50%","2/$8 TPC
344906726",4/$9 TPC,"TC 15% Off 389145
",3/$15,"$5.89 TPC
216211993",EDV
P6W2,21,May wk4,2023-02-26 00:00:00,2023-04-22 00:00:00,"6/25 - 7/4 Tri-Man  - 3/$15 +25% Circle
737244662",3/$15 + 25% TC,3/$18,EDV,3/$6 TPC,EDV,2/$11 TPC,EDV,EDV
P10W1,32,May wk3,2023-06-18 00:00:00,2023-12-30 00:00:00,PEP/KDP 3/$15 MB +25% TC Digital,"25% Circle
393947","Spend $15, Save $3",4/$14 TPC,"3/$6 TPC
362894325","TC 15% Off 395643
",EDV,$5.89 TPC,EDV
</dataframe>


The user asked the following question:
### QUERY
 Pivot the columns PEP 12pk cans,Dr Pepper 12pk cans,CSD 6pk PET,CSD 2L bottles,CSD 24pk cans,CSD 10pk mini cans,Bundaberg 4pk bottles,20oz PET into rows under a single column named 'Product'

You generated this python code:
df = dfs[0]
df.columns = df.columns.str.strip()
df_melted = pd.melt(df, id_vars=['2023 PEP Period', '2023 PEP WK', '2023 TGT WK', '2023 Sunday Start', 'TPM Pending Close', '2023 CSD AD'], value_vars=['PEP 12pk cans', 'Dr Pepper 12pk cans', 'CSD 6pk PET', 'CSD 2L bottles', 'CSD 24pk cans', 'CSD 10pk mini cans', 'Bundaberg 4pk bottles', '20oz PET'], var_name='Product', value_name='Value')
result = {'type': 'dataframe', 'value': df_melted}

It fails with the following error:
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandasai/pipelines/chat/code_execution.py", line 85, in execute
    result = self.execute_code(code_to_run, code_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandasai/pipelines/chat/code_execution.py", line 171, in execute_code
    exec(code, environment)
  File "<string>", line 3, in <module>
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandas/core/reshape/melt.py", line 77, in melt
    raise KeyError(
KeyError: "The following 'id_vars' are not present in the DataFrame: ['2023 CSD AD', '2023 PEP Period', '2023 PEP WK', '2023 Sunday Start', '2023 TGT WK']"


Fix the python code above and return the new python code:
2024-11-27 11:46:01 [INFO] Executing Step 1: CodeGenerator
2024-11-27 11:46:05 [INFO] Prompt used:

<dataframe>
dfs[0]:57x14
"2023
PEP Period","2023
PEP WK","2023
TGT WK","2023
Sunday Start",TPM Pending Close,"2023
CSD AD",PEP 12pk cans,Dr Pepper 12pk cans,CSD 6pk PET,CSD 2L bottles,CSD 24pk cans,CSD 10pk mini cans,Bundaberg 4pk bottles,20oz PET
P2W4,44,Mar wk2,2023-11-19 00:00:00,2023-07-01 00:00:00,KO 12pks feature 3/$18 MM (KDP/PEP included),2/$11; 20% TC 387743,"Buy 3, save 50%","2/$8 TPC
344906726",4/$9 TPC,"TC 15% Off 389145
",3/$15,"$5.89 TPC
216211993",EDV
P6W2,21,May wk4,2023-02-26 00:00:00,2023-04-22 00:00:00,"6/25 - 7/4 Tri-Man  - 3/$15 +25% Circle
737244662",3/$15 + 25% TC,3/$18,EDV,3/$6 TPC,EDV,2/$11 TPC,EDV,EDV
P10W1,32,May wk3,2023-06-18 00:00:00,2023-12-30 00:00:00,PEP/KDP 3/$15 MB +25% TC Digital,"25% Circle
393947","Spend $15, Save $3",4/$14 TPC,"3/$6 TPC
362894325","TC 15% Off 395643
",EDV,$5.89 TPC,EDV
</dataframe>


The user asked the following question:
### QUERY
 Pivot the columns PEP 12pk cans,Dr Pepper 12pk cans,CSD 6pk PET,CSD 2L bottles,CSD 24pk cans,CSD 10pk mini cans,Bundaberg 4pk bottles,20oz PET into rows under a single column named 'Product'

You generated this python code:
df = dfs[0]
df.columns = df.columns.str.strip()
df_melted = pd.melt(df, id_vars=['2023 PEP Period', '2023 PEP WK', '2023 TGT WK', '2023 Sunday Start', 'TPM Pending Close', '2023 CSD AD'], value_vars=['PEP 12pk cans', 'Dr Pepper 12pk cans', 'CSD 6pk PET', 'CSD 2L bottles', 'CSD 24pk cans', 'CSD 10pk mini cans', 'Bundaberg 4pk bottles', '20oz PET'], var_name='Product', value_name='Value')
result = {'type': 'dataframe', 'value': df_melted}

It fails with the following error:
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandasai/pipelines/chat/code_execution.py", line 85, in execute
    result = self.execute_code(code_to_run, code_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandasai/pipelines/chat/code_execution.py", line 171, in execute_code
    exec(code, environment)
  File "<string>", line 3, in <module>
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandas/core/reshape/melt.py", line 77, in melt
    raise KeyError(
KeyError: "The following 'id_vars' are not present in the DataFrame: ['2023 CSD AD', '2023 PEP Period', '2023 PEP WK', '2023 Sunday Start', '2023 TGT WK']"


Fix the python code above and return the new python code:

2024-11-27 11:46:05 [INFO] Code generated:
            ```
            df = dfs[0]
df.columns = df.columns.str.strip()
df_melted = pd.melt(df, id_vars=['PEP Period', 'PEP WK', 'TGT WK', 'Sunday Start', 'TPM Pending Close', 'CSD AD'], value_vars=['PEP 12pk cans', 'Dr Pepper 12pk cans', 'CSD 6pk PET', 'CSD 2L bottles', 'CSD 24pk cans', 'CSD 10pk mini cans', 'Bundaberg 4pk bottles', '20oz PET'], var_name='Product', value_name='Value')
result = {'type': 'dataframe', 'value': df_melted}
            ```

2024-11-27 11:46:05 [INFO] Executing Step 2: CodeCleaning
2024-11-27 11:46:05 [INFO]
Code running:
```
df = dfs[0]
df.columns = df.columns.str.strip()
df_melted = pd.melt(df, id_vars=['PEP Period', 'PEP WK', 'TGT WK', 'Sunday Start', 'TPM Pending Close', 'CSD AD'], value_vars=['PEP 12pk cans', 'Dr Pepper 12pk cans', 'CSD 6pk PET', 'CSD 2L bottles', 'CSD 24pk cans', 'CSD 10pk mini cans', 'Bundaberg 4pk bottles', '20oz PET'], var_name='Product', value_name='Value')
result = {'type': 'dataframe', 'value': df_melted}
        ```

,2023\nPEP Period,2023\nPEP WK,2023\nTGT WK,2023\nSunday Start,TPM Pending Close,2023\nCSD AD,Product,Value
0,P13W5,53,Dec wk5,2022-12-25 00:00:00,2022-12-31 00:00:00,3/$15 MB Tri Man + 25% Circle 383275,PEP 12pk cans,3/$15 +25% TC\n383275
1,P1W1,1,Jan wk1,2023-01-01 00:00:00,2023-01-07 00:00:00,"Tri-Man Spend $15, Save $3 + 20% Circle 383273",PEP 12pk cans,"Spend $15, Save $3 TC + 20% TC\n383273"
2,P1W2,2,Jan wk2,2023-01-08 00:00:00,2023-01-14 00:00:00,KDP + Pepper 12pk cans 3/$15 + PEP 20% Circle ...,PEP 12pk cans,20% Circle\n383273
3,P1W3,3,Jan wk3,2023-01-15 00:00:00,2023-01-21 00:00:00,PEP/KDP 3/$15 MB,PEP 12pk cans,3/$15
4,P1W4,4,Jan wk4,2023-01-22 00:00:00,2023-01-28 00:00:00,PEP/KDP 3/$15 MB +25% TC Digital,PEP 12pk cans,3/$15 + 25% TC
...,...,...,...,...,...,...,...,...
451,P13W4,52,Dec wk5,2023-12-24 00:00:00,2023-12-30 00:00:00,"Buy three 12pk sodas, save 40% via Target Circ...",20oz PET,EDV
452,P1W1,1,Jan wk1,2023-12-31 00:00:00,2024-01-06 00:00:00,"Tri-Man Circle Buy 3, Save 20% off",20oz PET,EDV
453,P1W2,2,Jan wk2,2024-01-07 00:00:00,2024-01-13 00:00:00,PEP 3/$16 MB all mkts except R300 (R300 B2G1 F...,20oz PET,EDV
454,P1W3,3,Jan wk3,2024-01-14 00:00:00,2024-01-20 00:00:00,PEP 3/$16 MB all mkts except R300 (R300 B2G1 F...,20oz PET,EDV
455,P1W4,4,Jan wk4,2024-01-21 00:00:00,2024-01-27 00:00:00,PEP 3/$16 MB all mkts except R300 (R300 B2G1 F...,20oz PET,EDV

In [ ]:
print(pandas_ai_agent_with_new_df.last_code_generated)

df = dfs[0]
df.columns = df.columns.str.strip()
df_melted = pd.melt(df, id_vars=['2023\nPEP Period', '2023\nPEP WK', '2023\nTGT WK', '2023\nSunday Start', 'TPM Pending Close', '2023\nCSD AD'], value_vars=['PEP 12pk cans', 'Dr Pepper 12pk cans', 'CSD 6pk PET', 'CSD 2L bottles', 'CSD 24pk cans', 'CSD 10pk mini cans', 'Bundaberg 4pk bottles', '20oz PET'], var_name='Product', value_name='Value')
result = {'type': 'dataframe', 'value': df_melted}

### Pandas AI Agent with description

In [3]:
from pandasai import Agent
import pandas as pd
df = pd.read_csv("/home/ec2-user/Pepsico_Hackathon/Pepsico_Main_Hackathon/Pepsico_demo_new_gen_mapping_approach/modified_files/2023 CSD Target Activity CalendarCSD Promo Activity 2023_header.csv")
pandas_ai_agent_with_new_df = Agent(df, description = "You are an expert Data engineer whose sole responsibility is to generate the most efficient and accurate python code that will handle the given query",config={"llm": llm_pa, "enforce_privacy": True, "verbose": True, "enable_cache":False, "max_retries": 10})
response = pandas_ai_agent_with_new_df.chat("Pivot the columns PEP 12pk cans,Dr Pepper 12pk cans,CSD 6pk PET,CSD 2L bottles,CSD 24pk cans,CSD 10pk mini cans,Bundaberg 4pk bottles,20oz PET into rows under a single column named 'Product'", output_type="dataframe")
response

2024-11-27 13:54:22 [INFO] Question: Pivot the columns PEP 12pk cans,Dr Pepper 12pk cans,CSD 6pk PET,CSD 2L bottles,CSD 24pk cans,CSD 10pk mini cans,Bundaberg 4pk bottles,20oz PET into rows under a single column named 'Product'
2024-11-27 13:54:22 [INFO] Running PandasAI with langchain_chat-databricks LLM...
2024-11-27 13:54:22 [INFO] Prompt ID: c67ce4ea-61c6-4def-82f9-1a19c748347b
2024-11-27 13:54:22 [INFO] Executing Pipeline: GenerateChatPipeline
2024-11-27 13:54:22 [INFO] Executing Step 0: ValidatePipelineInput
2024-11-27 13:54:22 [INFO] Executing Step 1: CacheLookup
2024-11-27 13:54:22 [INFO] Executing Step 2: PromptGeneration
2024-11-27 13:54:22 [INFO] Using prompt: <dataframe>
dfs[0]:57x14
"2023
PEP Period","2023
PEP WK","2023
TGT WK","2023
Sunday Start",TPM Pending Close,"2023
CSD AD",PEP 12pk cans,Dr Pepper 12pk cans,CSD 6pk PET,CSD 2L bottles,CSD 24pk cans,CSD 10pk mini cans,Bundaberg 4pk bottles,20oz PET
P5W3,46,Dec wk1,2023-05-07 00:00:00,2023-03-04 00:00:00,"Tri-Man Spend $15, Save $3 + 20% Circle 383273","Spend $15, Save $3 TC","Spend $15, Save $3 TC",EDV,4/$9 TPC,"TC 15% Off #811031806
",3/$15,"$5.89 TPC
557014486",EDV
P5W1,28,July wk1,2023-10-29 00:00:00,2023-06-17 00:00:00,"Pepsi 12pks 3/$15 MM (show 2) Does not include Dr. Pepper (25% Circle - Sun only, but entered for the full week)","Spend $18, Save $3 TC","Buy 3, Save 40% TC",4/$14 TPC,"3/$6 TPC
591941695","TC 15% Off 389145
",2/$11 AD,EDV,EDV
P9W1,19,Mar wk2,2023-02-05 00:00:00,2023-03-11 00:00:00,"PEP 2/$12 MB
560984498","Buy 3, get 20% off TC",EDV,"2/$8 TPC
344906726",3/$6 TPC,"TC 15% Off 395643
",2/$11 TPC,$5.89 TPC,EDV
</dataframe>




Update this initial code:
```python
# TODO: import the required dependencies
import pandas as pd

# Write code here

# Declare result var:
type (must be "dataframe"), value must be pd.DataFrame or pd.Series. Example: { "type": "dataframe", "value": pd.DataFrame({...}) }

```



### QUERY
 Pivot the columns PEP 12pk cans,Dr Pepper 12pk cans,CSD 6pk PET,CSD 2L bottles,CSD 24pk cans,CSD 10pk mini cans,Bundaberg 4pk bottles,20oz PET into rows under a single column named 'Product'

Variable `dfs: list[pd.DataFrame]` is already declared.

At the end, declare "result" variable as a dictionary of type and value.

If you are asked to plot a chart, use "matplotlib" for charts, save as png.


Generate python code and return full updated code:
2024-11-27 13:54:22 [INFO] Executing Step 3: CodeGenerator
2024-11-27 13:54:47 [INFO] Prompt used:
             You are an expert Data engineer whose sole responsibility is to generate the most efficient and accurate python code that will handle the given query
<dataframe>
dfs[0]:57x14
"2023
PEP Period","2023
PEP WK","2023
TGT WK","2023
Sunday Start",TPM Pending Close,"2023
CSD AD",PEP 12pk cans,Dr Pepper 12pk cans,CSD 6pk PET,CSD 2L bottles,CSD 24pk cans,CSD 10pk mini cans,Bundaberg 4pk bottles,20oz PET
P5W3,46,Dec wk1,2023-05-07 00:00:00,2023-03-04 00:00:00,"Tri-Man Spend $15, Save $3 + 20% Circle 383273","Spend $15, Save $3 TC","Spend $15, Save $3 TC",EDV,4/$9 TPC,"TC 15% Off #811031806
",3/$15,"$5.89 TPC
557014486",EDV
P5W1,28,July wk1,2023-10-29 00:00:00,2023-06-17 00:00:00,"Pepsi 12pks 3/$15 MM (show 2) Does not include Dr. Pepper (25% Circle - Sun only, but entered for the full week)","Spend $18, Save $3 TC","Buy 3, Save 40% TC",4/$14 TPC,"3/$6 TPC
591941695","TC 15% Off 389145
",2/$11 AD,EDV,EDV
P9W1,19,Mar wk2,2023-02-05 00:00:00,2023-03-11 00:00:00,"PEP 2/$12 MB
560984498","Buy 3, get 20% off TC",EDV,"2/$8 TPC
344906726",3/$6 TPC,"TC 15% Off 395643
",2/$11 TPC,$5.89 TPC,EDV
</dataframe>




Update this initial code:
```python
# TODO: import the required dependencies
import pandas as pd

# Write code here

# Declare result var:
type (must be "dataframe"), value must be pd.DataFrame or pd.Series. Example: { "type": "dataframe", "value": pd.DataFrame({...}) }

```



### QUERY
 Pivot the columns PEP 12pk cans,Dr Pepper 12pk cans,CSD 6pk PET,CSD 2L bottles,CSD 24pk cans,CSD 10pk mini cans,Bundaberg 4pk bottles,20oz PET into rows under a single column named 'Product'

Variable `dfs: list[pd.DataFrame]` is already declared.

At the end, declare "result" variable as a dictionary of type and value.

If you are asked to plot a chart, use "matplotlib" for charts, save as png.


Generate python code and return full updated code:

2024-11-27 13:54:47 [INFO] Code generated:
            ```
            # TODO: import the required dependencies
import pandas as pd

# Write code here
def pivot_products(df):
    # Select the columns to pivot
    cols_to_pivot = ['PEP 12pk cans', 'Dr Pepper 12pk cans', 'CSD 6pk PET', 'CSD 2L bottles', 'CSD 24pk cans', 'CSD 10pk mini cans', 'Bundaberg 4pk bottles', '20oz PET']

    # Melt the dataframe to pivot the columns into rows
    df_pivoted = pd.melt(df, id_vars=[col for col in df.columns if col not in cols_to_pivot], value_vars=cols_to_pivot, var_name='Product', value_name='Value')

    return df_pivoted

# Apply the function to the first dataframe in the list
result_df = pivot_products(dfs[0])

# Declare result var:
result = {"type": "dataframe", "value": result_df}
            ```

2024-11-27 13:54:47 [INFO] Executing Step 4: CachePopulation
2024-11-27 13:54:47 [INFO] Executing Step 5: CodeCleaning
2024-11-27 13:54:47 [INFO]
Code running:
```
def pivot_products(df):
    cols_to_pivot = ['PEP 12pk cans', 'Dr Pepper 12pk cans', 'CSD 6pk PET', 'CSD 2L bottles', 'CSD 24pk cans', 'CSD 10pk mini cans', 'Bundaberg 4pk bottles', '20oz PET']
    df_pivoted = pd.melt(df, id_vars=[col for col in df.columns if col not in cols_to_pivot], value_vars=cols_to_pivot, var_name='Product', value_name='Value')
    return df_pivoted


result_df = pivot_products(dfs[0])
result = {'type': 'dataframe', 'value': result_df}
        ```
2024-11-27 13:54:47 [INFO] Executing Step 6: CodeExecution
2024-11-27 13:54:47 [INFO] Executing Step 7: ResultValidation
2024-11-27 13:54:47 [INFO] Answer: {'type': 'dataframe', 'value':     2023\nPEP Period  2023\nPEP WK 2023\nTGT WK   2023\nSunday Start  \
0              P13W5            53      Dec wk5  2022-12-25 00:00:00
1               P1W1             1      Jan wk1  2023-01-01 00:00:00
2               P1W2             2      Jan wk2  2023-01-08 00:00:00
3               P1W3             3      Jan wk3  2023-01-15 00:00:00
4               P1W4             4      Jan wk4  2023-01-22 00:00:00
..               ...           ...          ...                  ...
451            P13W4            52      Dec wk5  2023-12-24 00:00:00
452             P1W1             1      Jan wk1  2023-12-31 00:00:00
453             P1W2             2      Jan wk2  2024-01-07 00:00:00
454             P1W3             3      Jan wk3  2024-01-14 00:00:00
455             P1W4             4      Jan wk4  2024-01-21 00:00:00

       TPM Pending Close                                       2023\nCSD AD  \
0    2022-12-31 00:00:00               3/$15 MB Tri Man + 25% Circle 383275
1    2023-01-07 00:00:00     Tri-Man Spend $15, Save $3 + 20% Circle 383273
2    2023-01-14 00:00:00  KDP + Pepper 12pk cans 3/$15 + PEP 20% Circle ...
3    2023-01-21 00:00:00                                   PEP/KDP 3/$15 MB
4    2023-01-28 00:00:00                   PEP/KDP 3/$15 MB +25% TC Digital
..                   ...                                                ...
451  2023-12-30 00:00:00  Buy three 12pk sodas, save 40% via Target Circ...
452  2024-01-06 00:00:00                Tri-Man Circle Buy 3, Save 20% off
453  2024-01-13 00:00:00  PEP 3/$16 MB all mkts except R300 (R300 B2G1 F...
454  2024-01-20 00:00:00  PEP 3/$16 MB all mkts except R300 (R300 B2G1 F...
455  2024-01-27 00:00:00  PEP 3/$16 MB all mkts except R300 (R300 B2G1 F...

           Product                                   Value
0    PEP 12pk cans                   3/$15 +25% TC\n383275
1    PEP 12pk cans  Spend $15, Save $3 TC + 20% TC\n383273
2    PEP 12pk cans                      20% Circle\n383273
3    PEP 12pk cans                                   3/$15
4    PEP 12pk cans                          3/$15 + 25% TC
..             ...                                     ...
451       20oz PET                                     EDV
452       20oz PET                                     EDV
453       20oz PET                                     EDV
454       20oz PET                                     EDV
455       20oz PET                                     EDV

[456 rows x 8 columns]}
2024-11-27 13:54:47 [INFO] Executing Step 8: ResultParsing

,2023\nPEP Period,2023\nPEP WK,2023\nTGT WK,2023\nSunday Start,TPM Pending Close,2023\nCSD AD,Product,Value
0,P13W5,53,Dec wk5,2022-12-25 00:00:00,2022-12-31 00:00:00,3/$15 MB Tri Man + 25% Circle 383275,PEP 12pk cans,3/$15 +25% TC\n383275
1,P1W1,1,Jan wk1,2023-01-01 00:00:00,2023-01-07 00:00:00,"Tri-Man Spend $15, Save $3 + 20% Circle 383273",PEP 12pk cans,"Spend $15, Save $3 TC + 20% TC\n383273"
2,P1W2,2,Jan wk2,2023-01-08 00:00:00,2023-01-14 00:00:00,KDP + Pepper 12pk cans 3/$15 + PEP 20% Circle ...,PEP 12pk cans,20% Circle\n383273
3,P1W3,3,Jan wk3,2023-01-15 00:00:00,2023-01-21 00:00:00,PEP/KDP 3/$15 MB,PEP 12pk cans,3/$15
4,P1W4,4,Jan wk4,2023-01-22 00:00:00,2023-01-28 00:00:00,PEP/KDP 3/$15 MB +25% TC Digital,PEP 12pk cans,3/$15 + 25% TC
...,...,...,...,...,...,...,...,...
451,P13W4,52,Dec wk5,2023-12-24 00:00:00,2023-12-30 00:00:00,"Buy three 12pk sodas, save 40% via Target Circ...",20oz PET,EDV
452,P1W1,1,Jan wk1,2023-12-31 00:00:00,2024-01-06 00:00:00,"Tri-Man Circle Buy 3, Save 20% off",20oz PET,EDV
453,P1W2,2,Jan wk2,2024-01-07 00:00:00,2024-01-13 00:00:00,PEP 3/$16 MB all mkts except R300 (R300 B2G1 F...,20oz PET,EDV
454,P1W3,3,Jan wk3,2024-01-14 00:00:00,2024-01-20 00:00:00,PEP 3/$16 MB all mkts except R300 (R300 B2G1 F...,20oz PET,EDV
455,P1W4,4,Jan wk4,2024-01-21 00:00:00,2024-01-27 00:00:00,PEP 3/$16 MB all mkts except R300 (R300 B2G1 F...,20oz PET,EDV

In [4]:
print(pandas_ai_agent_with_new_df.last_code_generated)

# TODO: import the required dependencies
import pandas as pd

# Write code here
def pivot_products(df):
    # Select the columns to pivot
    cols_to_pivot = ['PEP 12pk cans', 'Dr Pepper 12pk cans', 'CSD 6pk PET', 'CSD 2L bottles', 'CSD 24pk cans', 'CSD 10pk mini cans', 'Bundaberg 4pk bottles', '20oz PET']

    # Melt the dataframe to pivot the columns into rows
    df_pivoted = pd.melt(df, id_vars=[col for col in df.columns if col not in cols_to_pivot], value_vars=cols_to_pivot, var_name='Product', value_name='Value')

    return df_pivoted

# Apply the function to the first dataframe in the list
result_df = pivot_products(dfs[0])

# Declare result var:
result = {"type": "dataframe", "value": result_df}

In [14]:
pandas_ai_agent_with_new_df = Agent(response, description = "You are an expert Data engineer whose sole responsibility is to generate the most efficient and accurate python code that will handle the given query",config={"llm": llm_pa, "enforce_privacy": True, "verbose": True, "enable_cache":False, "max_retries": 10})
second_response = pandas_ai_agent_with_new_df.chat("Split the data in the Value column into separate columns and based on all kinds of special characters", output_type="dataframe")

2024-11-27 13:09:43 [INFO] Question: Split the data in the Value column into separate columns based on all kinds of special characters
2024-11-27 13:09:43 [INFO] Running PandasAI with langchain_chat-databricks LLM...
2024-11-27 13:09:43 [INFO] Prompt ID: 1c0e5600-eff8-4585-be00-c8ee4baaec84
2024-11-27 13:09:43 [INFO] Executing Pipeline: GenerateChatPipeline
2024-11-27 13:09:43 [INFO] Executing Step 0: ValidatePipelineInput
2024-11-27 13:09:43 [INFO] Executing Step 1: CacheLookup
2024-11-27 13:09:43 [INFO] Executing Step 2: PromptGeneration
2024-11-27 13:09:43 [INFO] Using prompt: <dataframe>
dfs[0]:456x11
"2023
PEP Period","2023
PEP WK","2023
TGT WK","2023
Sunday Start",TPM Pending Close,"2023
CSD AD",Product,Value,Value1,Value2,Value3
P13W5,6,May wk3,2023-03-19 00:00:00,2023-12-30 00:00:00,"PEP 2/$11 MB 12pks & Minis
277100923",CSD 6pk PET,"3/$6 TPC
362894325","TC 15%
700842801",,20% TC 386498
P13W3,9,Mar wk3,2023-06-04 00:00:00,2023-01-14 00:00:00,KO 3/$18 MB (KDP Included) Target Circle Wk,CSD 10pk mini cans,"$5.89 TPC
216211993","Spend $15, Save $3",$12 or 3,25% TC 386500
P6W4,52,May wk1,2023-03-05 00:00:00,2023-05-20 00:00:00,KO 3/$18 MB (KDP included),CSD 24pk cans,"Spend $18, get $3 off",$2 off Brand Funded,"$8 TPC
809817090",
</dataframe>




Update this initial code:
```python
# TODO: import the required dependencies
import pandas as pd

# Write code here

# Declare result var:
type (must be "dataframe"), value must be pd.DataFrame or pd.Series. Example: { "type": "dataframe", "value": pd.DataFrame({...}) }

```



### QUERY
 Split the data in the Value column into separate columns based on all kinds of special characters

Variable `dfs: list[pd.DataFrame]` is already declared.

At the end, declare "result" variable as a dictionary of type and value.

If you are asked to plot a chart, use "matplotlib" for charts, save as png.


Generate python code and return full updated code:
2024-11-27 13:09:43 [INFO] Executing Step 3: CodeGenerator
2024-11-27 13:09:49 [INFO] Prompt used:
             You are an expert Data engineer whose sole responsibility is to generate the most efficient and accurate python code that will handle the given query
<dataframe>
dfs[0]:456x11
"2023
PEP Period","2023
PEP WK","2023
TGT WK","2023
Sunday Start",TPM Pending Close,"2023
CSD AD",Product,Value,Value1,Value2,Value3
P13W5,6,May wk3,2023-03-19 00:00:00,2023-12-30 00:00:00,"PEP 2/$11 MB 12pks & Minis
277100923",CSD 6pk PET,"3/$6 TPC
362894325","TC 15%
700842801",,20% TC 386498
P13W3,9,Mar wk3,2023-06-04 00:00:00,2023-01-14 00:00:00,KO 3/$18 MB (KDP Included) Target Circle Wk,CSD 10pk mini cans,"$5.89 TPC
216211993","Spend $15, Save $3",$12 or 3,25% TC 386500
P6W4,52,May wk1,2023-03-05 00:00:00,2023-05-20 00:00:00,KO 3/$18 MB (KDP included),CSD 24pk cans,"Spend $18, get $3 off",$2 off Brand Funded,"$8 TPC
809817090",
</dataframe>




Update this initial code:
```python
# TODO: import the required dependencies
import pandas as pd

# Write code here

# Declare result var:
type (must be "dataframe"), value must be pd.DataFrame or pd.Series. Example: { "type": "dataframe", "value": pd.DataFrame({...}) }

```



### QUERY
 Split the data in the Value column into separate columns based on all kinds of special characters

Variable `dfs: list[pd.DataFrame]` is already declared.

At the end, declare "result" variable as a dictionary of type and value.

If you are asked to plot a chart, use "matplotlib" for charts, save as png.


Generate python code and return full updated code:

2024-11-27 13:09:49 [INFO] Code generated:
            ```
            import pandas as pd
import re

# Assuming dfs is a list of dataframes, we'll work with the first dataframe
df = dfs[0]

# Define a function to split the value column into separate columns
def split_value_column(row):
    values = re.split(r'[^a-zA-Z0-9\s]', row['Value'])
    return pd.Series([v.strip() for v in values if v.strip()])

# Apply the function to the Value column
df_split = df['Value'].apply(split_value_column)

# Add the new columns to the original dataframe
df = pd.concat([df, df_split], axis=1)

# Declare the result variable
result = {"type": "dataframe", "value": df}
            ```

2024-11-27 13:09:49 [INFO] Executing Step 4: CachePopulation
2024-11-27 13:09:49 [INFO] Executing Step 5: CodeCleaning
2024-11-27 13:09:49 [INFO] Executing Pipeline: ErrorCorrectionPipeline
2024-11-27 13:09:49 [INFO] Executing Step 0: ErrorPromptGeneration
2024-11-27 13:09:49 [INFO] Using prompt: <dataframe>
dfs[0]:456x11
"2023
PEP Period","2023
PEP WK","2023
TGT WK","2023
Sunday Start",TPM Pending Close,"2023
CSD AD",Product,Value,Value1,Value2,Value3
P13W5,6,May wk3,2023-03-19 00:00:00,2023-12-30 00:00:00,"PEP 2/$11 MB 12pks & Minis
277100923",CSD 6pk PET,"3/$6 TPC
362894325","TC 15%
700842801",,20% TC 386498
P13W3,9,Mar wk3,2023-06-04 00:00:00,2023-01-14 00:00:00,KO 3/$18 MB (KDP Included) Target Circle Wk,CSD 10pk mini cans,"$5.89 TPC
216211993","Spend $15, Save $3",$12 or 3,25% TC 386500
P6W4,52,May wk1,2023-03-05 00:00:00,2023-05-20 00:00:00,KO 3/$18 MB (KDP included),CSD 24pk cans,"Spend $18, get $3 off",$2 off Brand Funded,"$8 TPC
809817090",
</dataframe>


The user asked the following question:
### QUERY
 Split the data in the Value column into separate columns based on all kinds of special characters

You generated this python code:
import pandas as pd
import re

# Assuming dfs is a list of dataframes, we'll work with the first dataframe
df = dfs[0]

# Define a function to split the value column into separate columns
def split_value_column(row):
    values = re.split(r'[^a-zA-Z0-9\s]', row['Value'])
    return pd.Series([v.strip() for v in values if v.strip()])

# Apply the function to the Value column
df_split = df['Value'].apply(split_value_column)

# Add the new columns to the original dataframe
df = pd.concat([df, df_split], axis=1)

# Declare the result variable
result = {"type": "dataframe", "value": df}

It fails with the following error:
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandasai/pipelines/chat/code_cleaning.py", line 95, in execute
    code_to_run = self.get_code_to_run(input, code_context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandasai/pipelines/chat/code_cleaning.py", line 152, in get_code_to_run
    code_to_run = self._clean_code(code, context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandasai/pipelines/chat/code_cleaning.py", line 481, in _clean_code
    self._check_imports(node)
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandasai/pipelines/chat/code_cleaning.py", line 577, in _check_imports
    raise BadImportError(library)
pandasai.exceptions.BadImportError: Generated code includes import of re which is not in whitelist.


Fix the python code above and return the new python code:
2024-11-27 13:09:49 [INFO] Executing Step 1: CodeGenerator
2024-11-27 13:09:53 [INFO] Prompt used:
             You are an expert Data engineer whose sole responsibility is to generate the most efficient and accurate python code that will handle the given query
<dataframe>
dfs[0]:456x11
"2023
PEP Period","2023
PEP WK","2023
TGT WK","2023
Sunday Start",TPM Pending Close,"2023
CSD AD",Product,Value,Value1,Value2,Value3
P13W5,6,May wk3,2023-03-19 00:00:00,2023-12-30 00:00:00,"PEP 2/$11 MB 12pks & Minis
277100923",CSD 6pk PET,"3/$6 TPC
362894325","TC 15%
700842801",,20% TC 386498
P13W3,9,Mar wk3,2023-06-04 00:00:00,2023-01-14 00:00:00,KO 3/$18 MB (KDP Included) Target Circle Wk,CSD 10pk mini cans,"$5.89 TPC
216211993","Spend $15, Save $3",$12 or 3,25% TC 386500
P6W4,52,May wk1,2023-03-05 00:00:00,2023-05-20 00:00:00,KO 3/$18 MB (KDP included),CSD 24pk cans,"Spend $18, get $3 off",$2 off Brand Funded,"$8 TPC
809817090",
</dataframe>


The user asked the following question:
### QUERY
 Split the data in the Value column into separate columns based on all kinds of special characters

You generated this python code:
import pandas as pd
import re

# Assuming dfs is a list of dataframes, we'll work with the first dataframe
df = dfs[0]

# Define a function to split the value column into separate columns
def split_value_column(row):
    values = re.split(r'[^a-zA-Z0-9\s]', row['Value'])
    return pd.Series([v.strip() for v in values if v.strip()])

# Apply the function to the Value column
df_split = df['Value'].apply(split_value_column)

# Add the new columns to the original dataframe
df = pd.concat([df, df_split], axis=1)

# Declare the result variable
result = {"type": "dataframe", "value": df}

It fails with the following error:
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandasai/pipelines/chat/code_cleaning.py", line 95, in execute
    code_to_run = self.get_code_to_run(input, code_context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandasai/pipelines/chat/code_cleaning.py", line 152, in get_code_to_run
    code_to_run = self._clean_code(code, context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandasai/pipelines/chat/code_cleaning.py", line 481, in _clean_code
    self._check_imports(node)
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandasai/pipelines/chat/code_cleaning.py", line 577, in _check_imports
    raise BadImportError(library)
pandasai.exceptions.BadImportError: Generated code includes import of re which is not in whitelist.


Fix the python code above and return the new python code:

2024-11-27 13:09:53 [INFO] Code generated:
            ```
            import pandas as pd

# Assuming dfs is a list of dataframes, we'll work with the first dataframe
df = dfs[0]

# Define a function to split the value column into separate columns
def split_value_column(row):
    values = []
    temp = ''
    for char in row['Value']:
        if char.isalnum() or char.isspace():
            temp += char
        else:
            if temp:
                values.append(temp.strip())
                temp = ''
    if temp:
        values.append(temp.strip())
    return pd.Series(values)

# Apply the function to the Value column
df_split = df['Value'].apply(split_value_column)

# Add the new columns to the original dataframe
df = pd.concat([df, df_split], axis=1)

# Declare the result variable
result = {"type": "dataframe", "value": df}
            ```

2024-11-27 13:09:53 [INFO] Executing Step 2: CodeCleaning
2024-11-27 13:09:53 [INFO]
Code running:
```
df = dfs[0]


def split_value_column(row):
    values = []
    temp = ''
    for char in row['Value']:
        if char.isalnum() or char.isspace():
            temp += char
        elif temp:
            values.append(temp.strip())
            temp = ''
    if temp:
        values.append(temp.strip())
    return pd.Series(values)


df_split = df['Value'].apply(split_value_column)
df = pd.concat([df, df_split], axis=1)
result = {'type': 'dataframe', 'value': df}
        ```
2024-11-27 13:09:53 [INFO] Executing Step 6: CodeExecution
2024-11-27 13:09:53 [ERROR] Failed with error: Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandasai/pipelines/chat/code_execution.py", line 85, in execute
    result = self.execute_code(code_to_run, code_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandasai/pipelines/chat/code_execution.py", line 171, in execute_code
    exec(code, environment)
  File "<string>", line 18, in <module>
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandas/core/series.py", line 4771, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandas/core/apply.py", line 1123, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandas/core/apply.py", line 1174, in apply_standard
    mapped = lib.map_infer(
             ^^^^^^^^^^^^^^
  File "pandas/_libs/lib.pyx", line 2924, in pandas._libs.lib.map_infer
  File "<string>", line 7, in split_value_column
TypeError: string indices must be integers, not 'str'

2024-11-27 13:09:53 [WARNING] Failed to execute code retrying with a correction framework [retry number: 1]
2024-11-27 13:09:53 [INFO] Executing Pipeline: ErrorCorrectionPipeline
2024-11-27 13:09:53 [INFO] Executing Step 0: ErrorPromptGeneration
2024-11-27 13:09:53 [INFO] Using prompt: <dataframe>
dfs[0]:456x11
"2023
PEP Period","2023
PEP WK","2023
TGT WK","2023
Sunday Start",TPM Pending Close,"2023
CSD AD",Product,Value,Value1,Value2,Value3
P13W5,6,May wk3,2023-03-19 00:00:00,2023-12-30 00:00:00,"PEP 2/$11 MB 12pks & Minis
277100923",CSD 6pk PET,"3/$6 TPC
362894325","TC 15%
700842801",,20% TC 386498
P13W3,9,Mar wk3,2023-06-04 00:00:00,2023-01-14 00:00:00,KO 3/$18 MB (KDP Included) Target Circle Wk,CSD 10pk mini cans,"$5.89 TPC
216211993","Spend $15, Save $3",$12 or 3,25% TC 386500
P6W4,52,May wk1,2023-03-05 00:00:00,2023-05-20 00:00:00,KO 3/$18 MB (KDP included),CSD 24pk cans,"Spend $18, get $3 off",$2 off Brand Funded,"$8 TPC
809817090",
</dataframe>


The user asked the following question:
### QUERY
 Split the data in the Value column into separate columns based on all kinds of special characters

You generated this python code:
df = dfs[0]


def split_value_column(row):
    values = []
    temp = ''
    for char in row['Value']:
        if char.isalnum() or char.isspace():
            temp += char
        elif temp:
            values.append(temp.strip())
            temp = ''
    if temp:
        values.append(temp.strip())
    return pd.Series(values)


df_split = df['Value'].apply(split_value_column)
df = pd.concat([df, df_split], axis=1)
result = {'type': 'dataframe', 'value': df}

It fails with the following error:
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandasai/pipelines/chat/code_execution.py", line 85, in execute
    result = self.execute_code(code_to_run, code_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandasai/pipelines/chat/code_execution.py", line 171, in execute_code
    exec(code, environment)
  File "<string>", line 18, in <module>
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandas/core/series.py", line 4771, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandas/core/apply.py", line 1123, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandas/core/apply.py", line 1174, in apply_standard
    mapped = lib.map_infer(
             ^^^^^^^^^^^^^^
  File "pandas/_libs/lib.pyx", line 2924, in pandas._libs.lib.map_infer
  File "<string>", line 7, in split_value_column
TypeError: string indices must be integers, not 'str'


Fix the python code above and return the new python code:
2024-11-27 13:09:53 [INFO] Executing Step 1: CodeGenerator
2024-11-27 13:09:57 [INFO] Prompt used:
             You are an expert Data engineer whose sole responsibility is to generate the most efficient and accurate python code that will handle the given query
<dataframe>
dfs[0]:456x11
"2023
PEP Period","2023
PEP WK","2023
TGT WK","2023
Sunday Start",TPM Pending Close,"2023
CSD AD",Product,Value,Value1,Value2,Value3
P13W5,6,May wk3,2023-03-19 00:00:00,2023-12-30 00:00:00,"PEP 2/$11 MB 12pks & Minis
277100923",CSD 6pk PET,"3/$6 TPC
362894325","TC 15%
700842801",,20% TC 386498
P13W3,9,Mar wk3,2023-06-04 00:00:00,2023-01-14 00:00:00,KO 3/$18 MB (KDP Included) Target Circle Wk,CSD 10pk mini cans,"$5.89 TPC
216211993","Spend $15, Save $3",$12 or 3,25% TC 386500
P6W4,52,May wk1,2023-03-05 00:00:00,2023-05-20 00:00:00,KO 3/$18 MB (KDP included),CSD 24pk cans,"Spend $18, get $3 off",$2 off Brand Funded,"$8 TPC
809817090",
</dataframe>


The user asked the following question:
### QUERY
 Split the data in the Value column into separate columns based on all kinds of special characters

You generated this python code:
df = dfs[0]


def split_value_column(row):
    values = []
    temp = ''
    for char in row['Value']:
        if char.isalnum() or char.isspace():
            temp += char
        elif temp:
            values.append(temp.strip())
            temp = ''
    if temp:
        values.append(temp.strip())
    return pd.Series(values)


df_split = df['Value'].apply(split_value_column)
df = pd.concat([df, df_split], axis=1)
result = {'type': 'dataframe', 'value': df}

It fails with the following error:
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandasai/pipelines/chat/code_execution.py", line 85, in execute
    result = self.execute_code(code_to_run, code_context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandasai/pipelines/chat/code_execution.py", line 171, in execute_code
    exec(code, environment)
  File "<string>", line 18, in <module>
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandas/core/series.py", line 4771, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandas/core/apply.py", line 1123, in apply
    return self.apply_standard()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ec2-user/anaconda3/envs/pepsico_ppa_new/lib/python3.11/site-packages/pandas/core/apply.py", line 1174, in apply_standard
    mapped = lib.map_infer(
             ^^^^^^^^^^^^^^
  File "pandas/_libs/lib.pyx", line 2924, in pandas._libs.lib.map_infer
  File "<string>", line 7, in split_value_column
TypeError: string indices must be integers, not 'str'


Fix the python code above and return the new python code:

2024-11-27 13:09:57 [INFO] Code generated:
            ```
            df = dfs[0]

def split_value_column(row):
    values = []
    temp = ''
    for char in row:
        if char.isalnum() or char.isspace():
            temp += char
        elif temp:
            values.append(temp.strip())
            temp = ''
    if temp:
        values.append(temp.strip())
    return pd.Series(values)

df_split = df['Value'].apply(split_value_column)
df = pd.concat([df, df_split], axis=1)
result = {'type': 'dataframe', 'value': df}
            ```

2024-11-27 13:09:57 [INFO] Executing Step 2: CodeCleaning
2024-11-27 13:09:57 [INFO]
Code running:
```
df = dfs[0]


def split_value_column(row):
    values = []
    temp = ''
    for char in row:
        if char.isalnum() or char.isspace():
            temp += char
        elif temp:
            values.append(temp.strip())
            temp = ''
    if temp:
        values.append(temp.strip())
    return pd.Series(values)


df_split = df['Value'].apply(split_value_column)
df = pd.concat([df, df_split], axis=1)
result = {'type': 'dataframe', 'value': df}

In [15]:
second_response

,2023\nPEP Period,2023\nPEP WK,2023\nTGT WK,2023\nSunday Start,TPM Pending Close,2023\nCSD AD,Product,Value,Value1,Value2,Value3,0,1,2,3,4,5,6,7
0,P13W5,53,Dec wk5,2022-12-25 00:00:00,2022-12-31 00:00:00,3/$15 MB Tri Man + 25% Circle 383275,PEP 12pk cans,3/$15 +25% TC\n383275,3,$15,25% TC\n383275,3,15,25,TC\n383275,NaN,NaN,NaN,NaN
1,P1W1,1,Jan wk1,2023-01-01 00:00:00,2023-01-07 00:00:00,"Tri-Man Spend $15, Save $3 + 20% Circle 383273",PEP 12pk cans,"Spend $15, Save $3 TC + 20% TC\n383273","Spend $15, Save $3 TC",20% TC\n383273,None,Spend,15,Save,3 TC,20,TC\n383273,NaN,NaN
2,P1W2,2,Jan wk2,2023-01-08 00:00:00,2023-01-14 00:00:00,KDP + Pepper 12pk cans 3/$15 + PEP 20% Circle ...,PEP 12pk cans,20% Circle\n383273,20% Circle\n383273,None,None,20,Circle\n383273,NaN,NaN,NaN,NaN,NaN,NaN
3,P1W3,3,Jan wk3,2023-01-15 00:00:00,2023-01-21 00:00:00,PEP/KDP 3/$15 MB,PEP 12pk cans,3/$15,3,$15,None,3,15,NaN,NaN,NaN,NaN,NaN,NaN
4,P1W4,4,Jan wk4,2023-01-22 00:00:00,2023-01-28 00:00:00,PEP/KDP 3/$15 MB +25% TC Digital,PEP 12pk cans,3/$15 + 25% TC,3,$15,25% TC,3,15,25,TC,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
451,P13W4,52,Dec wk5,2023-12-24 00:00:00,2023-12-30 00:00:00,"Buy three 12pk sodas, save 40% via Target Circ...",20oz PET,EDV,EDV,None,None,EDV,NaN,NaN,NaN,NaN,NaN,NaN,NaN
452,P1W1,1,Jan wk1,2023-12-31 00:00:00,2024-01-06 00:00:00,"Tri-Man Circle Buy 3, Save 20% off",20oz PET,EDV,EDV,None,None,EDV,NaN,NaN,NaN,NaN,NaN,NaN,NaN
453,P1W2,2,Jan wk2,2024-01-07 00:00:00,2024-01-13 00:00:00,PEP 3/$16 MB all mkts except R300 (R300 B2G1 F...,20oz PET,EDV,EDV,None,None,EDV,NaN,NaN,NaN,NaN,NaN,NaN,NaN
454,P1W3,3,Jan wk3,2024-01-14 00:00:00,2024-01-20 00:00:00,PEP 3/$16 MB all mkts except R300 (R300 B2G1 F...,20oz PET,EDV,EDV,None,None,EDV,NaN,NaN,NaN,NaN,NaN,NaN,NaN
455,P1W4,4,Jan wk4,2024-01-21 00:00:00,2024-01-27 00:00:00,PEP 3/$16 MB all mkts except R300 (R300 B2G1 F...,20oz PET,EDV,EDV,None,None,EDV,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
print(pandas_ai_agent_with_new_df.last_code_generated)

df = dfs[0]

def split_value_column(row):
    values = []
    temp = ''
    for char in row:
        if char.isalnum() or char.isspace():
            temp += char
        elif temp:
            values.append(temp.strip())
            temp = ''
    if temp:
        values.append(temp.strip())
    return pd.Series(values)

df_split = df['Value'].apply(split_value_column)
df = pd.concat([df, df_split], axis=1)
result = {'type': 'dataframe', 'value': df}

In [17]:
pandas_ai_agent_with_new_df = Agent(response, description = "You are an expert Data engineer whose sole responsibility is to generate the most efficient and accurate python code that will handle the given query",config={"llm": llm_pa, "enforce_privacy": True, "verbose": True, "enable_cache":False, "max_retries": 10})
pandas_ai_agent_with_new_df.rephrase_query("Split the data in the Value column into separate columns and based on all kinds of special characters")
# second_response = pandas_ai_agent_with_new_df.chat("Split the data in the Value column into separate columns and based on all kinds of special characters", output_type="dataframe")

2024-11-27 13:41:19 [INFO] Rephrased Response:  Split the data in the Value column into separate columns based on all kinds of special characters

'Split the data in the Value column into separate columns based on all kinds of special characters'

In [6]:
pandas_ai_agent_with_new_df = Agent(response, description = "You are an expert Data engineer whose sole responsibility is to generate the most efficient and accurate python code that will handle the given query",config={"llm": llm_pa, "enforce_privacy": True, "verbose": True, "enable_cache":False, "max_retries": 10, "custom_whitelisted_dependencies": ["re"]})
# pandas_ai_agent_with_new_df.rephrase_query("Split the data in the Value column into separate columns and based on all kinds of special characters")
third_response = pandas_ai_agent_with_new_df.chat("Split the data in the Value column into separate columns and based on all kinds of special characters", output_type="dataframe")
third_response

2024-11-27 13:55:55 [INFO] Question: Split the data in the Value column into separate columns and based on all kinds of special characters
2024-11-27 13:55:55 [INFO] Running PandasAI with langchain_chat-databricks LLM...
2024-11-27 13:55:55 [INFO] Prompt ID: 2a3c013d-56a2-4adc-8ca9-fca0c168aaa7
2024-11-27 13:55:55 [INFO] Executing Pipeline: GenerateChatPipeline
2024-11-27 13:55:55 [INFO] Executing Step 0: ValidatePipelineInput
2024-11-27 13:55:55 [INFO] Executing Step 1: CacheLookup
2024-11-27 13:55:55 [INFO] Executing Step 2: PromptGeneration
2024-11-27 13:55:55 [INFO] Using prompt: <dataframe>
dfs[0]:456x8
"2023
PEP Period","2023
PEP WK","2023
TGT WK","2023
Sunday Start",TPM Pending Close,"2023
CSD AD",Product,Value
P6W4,6,July wk3,2023-03-26 00:00:00,2024-01-27 00:00:00," 7/5-7/8  Circle GI - Spend $18 or more on 12pk soda, get $3 off via Target Circle (show 3)",20oz PET,2/$11  AD
P12W1,3,Feb wk1,2023-12-17 00:00:00,2024-01-13 00:00:00,"KO Ad BOGO, Buy 1, get 50% Off (Pepsi/KDP included) 741110659",CSD 24pk cans,2/$11 AD
P13W3,13,July wk4,2023-03-19 00:00:00,2023-12-02 00:00:00,"6/25 - 7/4 Tri-Man  - 3/$15 +25% Circle
737244662",Bundaberg 4pk bottles,"25% (Sun-Mon Only) Spend $18, Save $3 TC"
</dataframe>




Update this initial code:
```python
# TODO: import the required dependencies
import pandas as pd

# Write code here

# Declare result var:
type (must be "dataframe"), value must be pd.DataFrame or pd.Series. Example: { "type": "dataframe", "value": pd.DataFrame({...}) }

```



### QUERY
 Split the data in the Value column into separate columns and based on all kinds of special characters

Variable `dfs: list[pd.DataFrame]` is already declared.

At the end, declare "result" variable as a dictionary of type and value.

If you are asked to plot a chart, use "matplotlib" for charts, save as png.


Generate python code and return full updated code:
2024-11-27 13:55:55 [INFO] Executing Step 3: CodeGenerator
2024-11-27 13:56:02 [INFO] Prompt used:
             You are an expert Data engineer whose sole responsibility is to generate the most efficient and accurate python code that will handle the given query
<dataframe>
dfs[0]:456x8
"2023
PEP Period","2023
PEP WK","2023
TGT WK","2023
Sunday Start",TPM Pending Close,"2023
CSD AD",Product,Value
P6W4,6,July wk3,2023-03-26 00:00:00,2024-01-27 00:00:00," 7/5-7/8  Circle GI - Spend $18 or more on 12pk soda, get $3 off via Target Circle (show 3)",20oz PET,2/$11  AD
P12W1,3,Feb wk1,2023-12-17 00:00:00,2024-01-13 00:00:00,"KO Ad BOGO, Buy 1, get 50% Off (Pepsi/KDP included) 741110659",CSD 24pk cans,2/$11 AD
P13W3,13,July wk4,2023-03-19 00:00:00,2023-12-02 00:00:00,"6/25 - 7/4 Tri-Man  - 3/$15 +25% Circle
737244662",Bundaberg 4pk bottles,"25% (Sun-Mon Only) Spend $18, Save $3 TC"
</dataframe>




Update this initial code:
```python
# TODO: import the required dependencies
import pandas as pd

# Write code here

# Declare result var:
type (must be "dataframe"), value must be pd.DataFrame or pd.Series. Example: { "type": "dataframe", "value": pd.DataFrame({...}) }

```



### QUERY
 Split the data in the Value column into separate columns and based on all kinds of special characters

Variable `dfs: list[pd.DataFrame]` is already declared.

At the end, declare "result" variable as a dictionary of type and value.

If you are asked to plot a chart, use "matplotlib" for charts, save as png.


Generate python code and return full updated code:

2024-11-27 13:56:02 [INFO] Code generated:
            ```
            # TODO: import the required dependencies
import pandas as pd
import re

# Write code here
def split_value_column(df):
    # Split the Value column into separate columns based on special characters
    df[['Value1', 'Value2', 'Value3']] = df['Value'].str.split(r'[^a-zA-Z0-9]+', n=2, expand=True)

    # Remove any empty strings from the new columns
    df[['Value1', 'Value2', 'Value3']] = df[['Value1', 'Value2', 'Value3']].replace('', pd.NA)

    return df

# Apply the function to the first dataframe in the list
dfs[0] = split_value_column(dfs[0])

# Declare result var:
result = { "type": "dataframe", "value": dfs[0] }
            ```

2024-11-27 13:56:02 [INFO] Executing Step 4: CachePopulation
2024-11-27 13:56:02 [INFO] Executing Step 5: CodeCleaning
2024-11-27 13:56:02 [INFO]
Code running:
```
def split_value_column(df):
    df[['Value1', 'Value2', 'Value3']] = df['Value'].str.split('[^a-zA-Z0-9]+', n=2, expand=True)
    df[['Value1', 'Value2', 'Value3']] = df[['Value1', 'Value2', 'Value3']].replace('', pd.NA)
    return df


dfs[0] = split_value_column(dfs[0])
result = {'type': 'dataframe', 'value': dfs[0]}
        ```
2024-11-27 13:56:02 [INFO] Executing Step 6: CodeExecution
2024-11-27 13:56:02 [INFO] Executing Step 7: ResultValidation
2024-11-27 13:56:02 [INFO] Answer: {'type': 'dataframe', 'value':     2023\nPEP Period  2023\nPEP WK 2023\nTGT WK   2023\nSunday Start  \
0              P13W5            53      Dec wk5  2022-12-25 00:00:00
1               P1W1             1      Jan wk1  2023-01-01 00:00:00
2               P1W2             2      Jan wk2  2023-01-08 00:00:00
3               P1W3             3      Jan wk3  2023-01-15 00:00:00
4               P1W4             4      Jan wk4  2023-01-22 00:00:00
..               ...           ...          ...                  ...
451            P13W4            52      Dec wk5  2023-12-24 00:00:00
452             P1W1             1      Jan wk1  2023-12-31 00:00:00
453             P1W2             2      Jan wk2  2024-01-07 00:00:00
454             P1W3             3      Jan wk3  2024-01-14 00:00:00
455             P1W4             4      Jan wk4  2024-01-21 00:00:00

       TPM Pending Close                                       2023\nCSD AD  \
0    2022-12-31 00:00:00               3/$15 MB Tri Man + 25% Circle 383275
1    2023-01-07 00:00:00     Tri-Man Spend $15, Save $3 + 20% Circle 383273
2    2023-01-14 00:00:00  KDP + Pepper 12pk cans 3/$15 + PEP 20% Circle ...
3    2023-01-21 00:00:00                                   PEP/KDP 3/$15 MB
4    2023-01-28 00:00:00                   PEP/KDP 3/$15 MB +25% TC Digital
..                   ...                                                ...
451  2023-12-30 00:00:00  Buy three 12pk sodas, save 40% via Target Circ...
452  2024-01-06 00:00:00                Tri-Man Circle Buy 3, Save 20% off
453  2024-01-13 00:00:00  PEP 3/$16 MB all mkts except R300 (R300 B2G1 F...
454  2024-01-20 00:00:00  PEP 3/$16 MB all mkts except R300 (R300 B2G1 F...
455  2024-01-27 00:00:00  PEP 3/$16 MB all mkts except R300 (R300 B2G1 F...

           Product                                   Value Value1  Value2  \
0    PEP 12pk cans                   3/$15 +25% TC\n383275      3      15
1    PEP 12pk cans  Spend $15, Save $3 TC + 20% TC\n383273  Spend      15
2    PEP 12pk cans                      20% Circle\n383273     20  Circle
3    PEP 12pk cans                                   3/$15      3      15
4    PEP 12pk cans                          3/$15 + 25% TC      3      15
..             ...                                     ...    ...     ...
451       20oz PET                                     EDV    EDV    None
452       20oz PET                                     EDV    EDV    None
453       20oz PET                                     EDV    EDV    None
454       20oz PET                                     EDV    EDV    None
455       20oz PET                                     EDV    EDV    None

                          Value3
0                 25% TC\n383275
1    Save $3 TC + 20% TC\n383273
2                         383273
3                           None
4                         25% TC
..                           ...
451                         None
452                         None
453                         None
454                         None
455                         None

[456 rows x 11 columns]}
2024-11-27 13:56:02 [INFO] Executing Step 8: ResultParsing

,2023\nPEP Period,2023\nPEP WK,2023\nTGT WK,2023\nSunday Start,TPM Pending Close,2023\nCSD AD,Product,Value,Value1,Value2,Value3
0,P13W5,53,Dec wk5,2022-12-25 00:00:00,2022-12-31 00:00:00,3/$15 MB Tri Man + 25% Circle 383275,PEP 12pk cans,3/$15 +25% TC\n383275,3,15,25% TC\n383275
1,P1W1,1,Jan wk1,2023-01-01 00:00:00,2023-01-07 00:00:00,"Tri-Man Spend $15, Save $3 + 20% Circle 383273",PEP 12pk cans,"Spend $15, Save $3 TC + 20% TC\n383273",Spend,15,Save $3 TC + 20% TC\n383273
2,P1W2,2,Jan wk2,2023-01-08 00:00:00,2023-01-14 00:00:00,KDP + Pepper 12pk cans 3/$15 + PEP 20% Circle ...,PEP 12pk cans,20% Circle\n383273,20,Circle,383273
3,P1W3,3,Jan wk3,2023-01-15 00:00:00,2023-01-21 00:00:00,PEP/KDP 3/$15 MB,PEP 12pk cans,3/$15,3,15,None
4,P1W4,4,Jan wk4,2023-01-22 00:00:00,2023-01-28 00:00:00,PEP/KDP 3/$15 MB +25% TC Digital,PEP 12pk cans,3/$15 + 25% TC,3,15,25% TC
...,...,...,...,...,...,...,...,...,...,...,...
451,P13W4,52,Dec wk5,2023-12-24 00:00:00,2023-12-30 00:00:00,"Buy three 12pk sodas, save 40% via Target Circ...",20oz PET,EDV,EDV,None,None
452,P1W1,1,Jan wk1,2023-12-31 00:00:00,2024-01-06 00:00:00,"Tri-Man Circle Buy 3, Save 20% off",20oz PET,EDV,EDV,None,None
453,P1W2,2,Jan wk2,2024-01-07 00:00:00,2024-01-13 00:00:00,PEP 3/$16 MB all mkts except R300 (R300 B2G1 F...,20oz PET,EDV,EDV,None,None
454,P1W3,3,Jan wk3,2024-01-14 00:00:00,2024-01-20 00:00:00,PEP 3/$16 MB all mkts except R300 (R300 B2G1 F...,20oz PET,EDV,EDV,None,None
455,P1W4,4,Jan wk4,2024-01-21 00:00:00,2024-01-27 00:00:00,PEP 3/$16 MB all mkts except R300 (R300 B2G1 F...,20oz PET,EDV,EDV,None,None

In [9]:
third_response.head(15)

,2023\nPEP Period,2023\nPEP WK,2023\nTGT WK,2023\nSunday Start,TPM Pending Close,2023\nCSD AD,Product,Value,Value1,Value2,Value3
0,P13W5,53,Dec wk5,2022-12-25 00:00:00,2022-12-31 00:00:00,3/$15 MB Tri Man + 25% Circle 383275,PEP 12pk cans,3/$15 +25% TC\n383275,3,15,25% TC\n383275
1,P1W1,1,Jan wk1,2023-01-01 00:00:00,2023-01-07 00:00:00,"Tri-Man Spend $15, Save $3 + 20% Circle 383273",PEP 12pk cans,"Spend $15, Save $3 TC + 20% TC\n383273",Spend,15,Save $3 TC + 20% TC\n383273
2,P1W2,2,Jan wk2,2023-01-08 00:00:00,2023-01-14 00:00:00,KDP + Pepper 12pk cans 3/$15 + PEP 20% Circle ...,PEP 12pk cans,20% Circle\n383273,20,Circle,383273
3,P1W3,3,Jan wk3,2023-01-15 00:00:00,2023-01-21 00:00:00,PEP/KDP 3/$15 MB,PEP 12pk cans,3/$15,3,15,None
4,P1W4,4,Jan wk4,2023-01-22 00:00:00,2023-01-28 00:00:00,PEP/KDP 3/$15 MB +25% TC Digital,PEP 12pk cans,3/$15 + 25% TC,3,15,25% TC
5,P2W1,5,Feb wk1,2023-01-29 00:00:00,2023-02-04 00:00:00,"Circle GI - Spend $15 or more on 12pk soda, ge...",PEP 12pk cans,"Spend $15, Save $3 TC",Spend,15,Save $3 TC
6,P2W2,6,Feb wk2,2023-02-05 00:00:00,2023-02-11 00:00:00,Coke & Pepper 12pks 3/$18 MM (show 2) Pepsi & ...,PEP 12pk cans,3/$15 + 20% TC 386498,3,15,20% TC 386498
7,P2W3,7,Feb wk3,2023-02-12 00:00:00,2023-02-18 00:00:00,Pepsi 12pks 3/$15 MM (show 2) Does not include...,PEP 12pk cans,3/$15 + 25% TC 386500,3,15,25% TC 386500
8,P2W4,8,Feb wk4,2023-02-19 00:00:00,2023-02-25 00:00:00,Pepsi 12pks 3/$15 MM (show 2) Does not include...,PEP 12pk cans,3/$15,3,15,None
9,P3W1,9,Mar wk1,2023-02-26 00:00:00,2023-03-04 00:00:00,Pepsi 12pks 3/$15 MM (show 2) Does not include...,PEP 12pk cans,3/$15,3,15,None
10,P3W2,10,Mar wk2,2023-03-05 00:00:00,2023-03-11 00:00:00,KO 3/$18 MB,PEP 12pk cans,EDV: 20% TC 387742,EDV,20,TC 387742
11,P3W3,11,Mar wk3,2023-03-12 00:00:00,2023-03-18 00:00:00,KO 3/$18 MB,PEP 12pk cans,EDV: 20% TC 387742,EDV,20,TC 387742
12,P3W4,12,Mar wk4,2023-03-19 00:00:00,2023-03-25 00:00:00,KO 3/$18 MB,PEP 12pk cans,EDV,EDV,None,None
13,P4W1,13,Mar wk5,2023-03-26 00:00:00,2023-04-01 00:00:00,"Circle GI - Spend $18 or more on 12pk soda, ge...",PEP 12pk cans,"Spend $18, Save $3 TC",Spend,18,Save $3 TC
14,P4W2,14,Apr wk1,2023-04-02 00:00:00,2023-04-08 00:00:00,Coke & Pepper 12pks 3/$18 MM (show 2) Pepsi & ...,PEP 12pk cans,2/$11; 20% TC 387743,2,11,20% TC 387743

In [7]:
print(pandas_ai_agent_with_new_df.last_code_generated)

# TODO: import the required dependencies
import pandas as pd
import re

# Write code here
def split_value_column(df):
    # Split the Value column into separate columns based on special characters
    df[['Value1', 'Value2', 'Value3']] = df['Value'].str.split(r'[^a-zA-Z0-9]+', n=2, expand=True)

    # Remove any empty strings from the new columns
    df[['Value1', 'Value2', 'Value3']] = df[['Value1', 'Value2', 'Value3']].replace('', pd.NA)

    return df

# Apply the function to the first dataframe in the list
dfs[0] = split_value_column(dfs[0])

# Declare result var:
result = { "type": "dataframe", "value": dfs[0] }

### With newer description

In [2]:
import pandas as pd
from pandasai import Agent

df = pd.read_csv("/home/ec2-user/Pepsico_Hackathon/Pepsico_Main_Hackathon/Pepsico_demo_new_gen_mapping_approach/modified_files/2023 CSD Target Activity CalendarCSD Promo Activity 2023_header.csv")
pandas_ai_agent_with_new_df = Agent(df, description = "You are an expert Data Analyst and python developer whose sole responsibility is to generate the most efficient and accurate python code that will handle the given query. Your job is to understand the given sample dataframe thoroughly by analyzing all the columns, their datatype etc and the given query. After you are done with the analysis, generate a meaningful, syntactically and semantically correct python code. Make sure to consider the column names properly with appropriate special characters if applicable. If the query is asking for specific columns then provide only those specific columns. If the query has not mentioned anything about the other columns then consider keeping them.",config={"llm": llm_pa, "enforce_privacy": True, "verbose": True, "enable_cache":False, "max_retries": 10, "custom_whitelisted_dependencies": ["re"]})
response = pandas_ai_agent_with_new_df.chat("Pivot the columns PEP 12pk cans,Dr Pepper 12pk cans,CSD 6pk PET,CSD 2L bottles,CSD 24pk cans,CSD 10pk mini cans,Bundaberg 4pk bottles,20oz PET into rows under a single column named 'Product'", output_type="dataframe")
response

2024-11-28 07:31:00 [INFO] Question: Pivot the columns PEP 12pk cans,Dr Pepper 12pk cans,CSD 6pk PET,CSD 2L bottles,CSD 24pk cans,CSD 10pk mini cans,Bundaberg 4pk bottles,20oz PET into rows under a single column named 'Product'
2024-11-28 07:31:00 [INFO] Running PandasAI with langchain_chat-databricks LLM...
2024-11-28 07:31:00 [INFO] Prompt ID: c7c620e1-7e22-4e04-9e96-a02769d6dfcb
2024-11-28 07:31:00 [INFO] Executing Pipeline: GenerateChatPipeline
2024-11-28 07:31:00 [INFO] Executing Step 0: ValidatePipelineInput
2024-11-28 07:31:00 [INFO] Executing Step 1: CacheLookup
2024-11-28 07:31:00 [INFO] Executing Step 2: PromptGeneration
2024-11-28 07:31:00 [INFO] Using prompt: <dataframe>
dfs[0]:57x14
"2023
PEP Period","2023
PEP WK","2023
TGT WK","2023
Sunday Start",TPM Pending Close,"2023
CSD AD",PEP 12pk cans,Dr Pepper 12pk cans,CSD 6pk PET,CSD 2L bottles,CSD 24pk cans,CSD 10pk mini cans,Bundaberg 4pk bottles,20oz PET
P2W1,26,Sep wk1,2023-02-05 00:00:00,2023-03-11 00:00:00,"Buy three 12pk sodas, save 40% via Target Circle (show 4) Does include Dr. Pepper IVY ID 212794203",DEW ONLY TC,"Buy 3, get 20% off TC",4/$14 Ad,4/$9 TPC,"TC 15%
700842801",2/$11 TPC,$5.89 TPC,EDV
P11W2,31,Mar wk3,2023-12-03 00:00:00,2023-01-14 00:00:00,Coke & Pepper 12pks 3/$18 MM (show 2) Pepsi & KDP 2/$11 MM (show 2) 803924201,EDV,"Spend $18, get $3 off","4/$12 Ad
429678394","3/$6 TPC
362894325","TC 15% Off 389145
",3/$15,"$5.89 TPC
216211993",EDV
P10W3,51,May wk3,2023-03-26 00:00:00,2023-10-14 00:00:00,KDP 3/$15,BOGO,"Spend $15, Save $3 TC",2/$7 TPC,"3/$6 TPC
591941695","TC 15% Off #811031806
",EDV,TPC $5.89,EDV
</dataframe>




Update this initial code:
```python
# TODO: import the required dependencies
import pandas as pd

# Write code here

# Declare result var:
type (must be "dataframe"), value must be pd.DataFrame or pd.Series. Example: { "type": "dataframe", "value": pd.DataFrame({...}) }

```



### QUERY
 Pivot the columns PEP 12pk cans,Dr Pepper 12pk cans,CSD 6pk PET,CSD 2L bottles,CSD 24pk cans,CSD 10pk mini cans,Bundaberg 4pk bottles,20oz PET into rows under a single column named 'Product'

Variable `dfs: list[pd.DataFrame]` is already declared.

At the end, declare "result" variable as a dictionary of type and value.

If you are asked to plot a chart, use "matplotlib" for charts, save as png.


Generate python code and return full updated code:
2024-11-28 07:31:00 [INFO] Executing Step 3: CodeGenerator
2024-11-28 07:31:08 [INFO] Prompt used:
             You are an expert Data Analyst and python developer whose sole responsibility is to generate the most efficient and accurate python code that will handle the given query. Your job is to understand the given sample dataframe thoroughly by analyzing all the columns, their datatype etc and the given query. After you are done with the analysis, generate a meaningful, syntactically and semantically correct python code. Make sure to consider the column names properly with appropriate special characters if applicable. If the query is asking for specific columns then provide only those specific columns. If the query has not mentioned anything about the other columns then consider keeping them.
<dataframe>
dfs[0]:57x14
"2023
PEP Period","2023
PEP WK","2023
TGT WK","2023
Sunday Start",TPM Pending Close,"2023
CSD AD",PEP 12pk cans,Dr Pepper 12pk cans,CSD 6pk PET,CSD 2L bottles,CSD 24pk cans,CSD 10pk mini cans,Bundaberg 4pk bottles,20oz PET
P2W1,26,Sep wk1,2023-02-05 00:00:00,2023-03-11 00:00:00,"Buy three 12pk sodas, save 40% via Target Circle (show 4) Does include Dr. Pepper IVY ID 212794203",DEW ONLY TC,"Buy 3, get 20% off TC",4/$14 Ad,4/$9 TPC,"TC 15%
700842801",2/$11 TPC,$5.89 TPC,EDV
P11W2,31,Mar wk3,2023-12-03 00:00:00,2023-01-14 00:00:00,Coke & Pepper 12pks 3/$18 MM (show 2) Pepsi & KDP 2/$11 MM (show 2) 803924201,EDV,"Spend $18, get $3 off","4/$12 Ad
429678394","3/$6 TPC
362894325","TC 15% Off 389145
",3/$15,"$5.89 TPC
216211993",EDV
P10W3,51,May wk3,2023-03-26 00:00:00,2023-10-14 00:00:00,KDP 3/$15,BOGO,"Spend $15, Save $3 TC",2/$7 TPC,"3/$6 TPC
591941695","TC 15% Off #811031806
",EDV,TPC $5.89,EDV
</dataframe>




Update this initial code:
```python
# TODO: import the required dependencies
import pandas as pd

# Write code here

# Declare result var:
type (must be "dataframe"), value must be pd.DataFrame or pd.Series. Example: { "type": "dataframe", "value": pd.DataFrame({...}) }

```



### QUERY
 Pivot the columns PEP 12pk cans,Dr Pepper 12pk cans,CSD 6pk PET,CSD 2L bottles,CSD 24pk cans,CSD 10pk mini cans,Bundaberg 4pk bottles,20oz PET into rows under a single column named 'Product'

Variable `dfs: list[pd.DataFrame]` is already declared.

At the end, declare "result" variable as a dictionary of type and value.

If you are asked to plot a chart, use "matplotlib" for charts, save as png.


Generate python code and return full updated code:

2024-11-28 07:31:08 [INFO] Code generated:
            ```
            # TODO: import the required dependencies
import pandas as pd

# Write code here
def pivot_columns(df):
    # Select the columns to pivot
    cols_to_pivot = ['PEP 12pk cans', 'Dr Pepper 12pk cans', 'CSD 6pk PET', 'CSD 2L bottles', 'CSD 24pk cans', 'CSD 10pk mini cans', 'Bundaberg 4pk bottles', '20oz PET']

    # Melt the dataframe to pivot the columns
    df_pivoted = pd.melt(df, id_vars=[col for col in df.columns if col not in cols_to_pivot], value_vars=cols_to_pivot, var_name='Product', value_name='Value')

    return df_pivoted

# Apply the function to the dataframe
df_pivoted = pivot_columns(dfs[0])

# Declare result var:
result = { "type": "dataframe", "value": df_pivoted }
            ```

2024-11-28 07:31:08 [INFO] Executing Step 4: CachePopulation
2024-11-28 07:31:08 [INFO] Executing Step 5: CodeCleaning
2024-11-28 07:31:08 [INFO]
Code running:
```
def pivot_columns(df):
    cols_to_pivot = ['PEP 12pk cans', 'Dr Pepper 12pk cans', 'CSD 6pk PET', 'CSD 2L bottles', 'CSD 24pk cans', 'CSD 10pk mini cans', 'Bundaberg 4pk bottles', '20oz PET']
    df_pivoted = pd.melt(df, id_vars=[col for col in df.columns if col not in cols_to_pivot], value_vars=cols_to_pivot, var_name='Product', value_name='Value')
    return df_pivoted


df_pivoted = pivot_columns(dfs[0])
result = {'type': 'dataframe', 'value': df_pivoted}
        ```
2024-11-28 07:31:08 [INFO] Executing Step 6: CodeExecution
2024-11-28 07:31:08 [INFO] Executing Step 7: ResultValidation
2024-11-28 07:31:08 [INFO] Answer: {'type': 'dataframe', 'value':     2023\nPEP Period  2023\nPEP WK 2023\nTGT WK   2023\nSunday Start  \
0              P13W5            53      Dec wk5  2022-12-25 00:00:00
1               P1W1             1      Jan wk1  2023-01-01 00:00:00
2               P1W2             2      Jan wk2  2023-01-08 00:00:00
3               P1W3             3      Jan wk3  2023-01-15 00:00:00
4               P1W4             4      Jan wk4  2023-01-22 00:00:00
..               ...           ...          ...                  ...
451            P13W4            52      Dec wk5  2023-12-24 00:00:00
452             P1W1             1      Jan wk1  2023-12-31 00:00:00
453             P1W2             2      Jan wk2  2024-01-07 00:00:00
454             P1W3             3      Jan wk3  2024-01-14 00:00:00
455             P1W4             4      Jan wk4  2024-01-21 00:00:00

       TPM Pending Close                                       2023\nCSD AD  \
0    2022-12-31 00:00:00               3/$15 MB Tri Man + 25% Circle 383275
1    2023-01-07 00:00:00     Tri-Man Spend $15, Save $3 + 20% Circle 383273
2    2023-01-14 00:00:00  KDP + Pepper 12pk cans 3/$15 + PEP 20% Circle ...
3    2023-01-21 00:00:00                                   PEP/KDP 3/$15 MB
4    2023-01-28 00:00:00                   PEP/KDP 3/$15 MB +25% TC Digital
..                   ...                                                ...
451  2023-12-30 00:00:00  Buy three 12pk sodas, save 40% via Target Circ...
452  2024-01-06 00:00:00                Tri-Man Circle Buy 3, Save 20% off
453  2024-01-13 00:00:00  PEP 3/$16 MB all mkts except R300 (R300 B2G1 F...
454  2024-01-20 00:00:00  PEP 3/$16 MB all mkts except R300 (R300 B2G1 F...
455  2024-01-27 00:00:00  PEP 3/$16 MB all mkts except R300 (R300 B2G1 F...

           Product                                   Value
0    PEP 12pk cans                   3/$15 +25% TC\n383275
1    PEP 12pk cans  Spend $15, Save $3 TC + 20% TC\n383273
2    PEP 12pk cans                      20% Circle\n383273
3    PEP 12pk cans                                   3/$15
4    PEP 12pk cans                          3/$15 + 25% TC
..             ...                                     ...
451       20oz PET                                     EDV
452       20oz PET                                     EDV
453       20oz PET                                     EDV
454       20oz PET                                     EDV
455       20oz PET                                     EDV

[456 rows x 8 columns]}
2024-11-28 07:31:08 [INFO] Executing Step 8: ResultParsing

,2023\nPEP Period,2023\nPEP WK,2023\nTGT WK,2023\nSunday Start,TPM Pending Close,2023\nCSD AD,Product,Value
0,P13W5,53,Dec wk5,2022-12-25 00:00:00,2022-12-31 00:00:00,3/$15 MB Tri Man + 25% Circle 383275,PEP 12pk cans,3/$15 +25% TC\n383275
1,P1W1,1,Jan wk1,2023-01-01 00:00:00,2023-01-07 00:00:00,"Tri-Man Spend $15, Save $3 + 20% Circle 383273",PEP 12pk cans,"Spend $15, Save $3 TC + 20% TC\n383273"
2,P1W2,2,Jan wk2,2023-01-08 00:00:00,2023-01-14 00:00:00,KDP + Pepper 12pk cans 3/$15 + PEP 20% Circle ...,PEP 12pk cans,20% Circle\n383273
3,P1W3,3,Jan wk3,2023-01-15 00:00:00,2023-01-21 00:00:00,PEP/KDP 3/$15 MB,PEP 12pk cans,3/$15
4,P1W4,4,Jan wk4,2023-01-22 00:00:00,2023-01-28 00:00:00,PEP/KDP 3/$15 MB +25% TC Digital,PEP 12pk cans,3/$15 + 25% TC
...,...,...,...,...,...,...,...,...
451,P13W4,52,Dec wk5,2023-12-24 00:00:00,2023-12-30 00:00:00,"Buy three 12pk sodas, save 40% via Target Circ...",20oz PET,EDV
452,P1W1,1,Jan wk1,2023-12-31 00:00:00,2024-01-06 00:00:00,"Tri-Man Circle Buy 3, Save 20% off",20oz PET,EDV
453,P1W2,2,Jan wk2,2024-01-07 00:00:00,2024-01-13 00:00:00,PEP 3/$16 MB all mkts except R300 (R300 B2G1 F...,20oz PET,EDV
454,P1W3,3,Jan wk3,2024-01-14 00:00:00,2024-01-20 00:00:00,PEP 3/$16 MB all mkts except R300 (R300 B2G1 F...,20oz PET,EDV
455,P1W4,4,Jan wk4,2024-01-21 00:00:00,2024-01-27 00:00:00,PEP 3/$16 MB all mkts except R300 (R300 B2G1 F...,20oz PET,EDV

In [3]:
pandas_ai_agent_with_new_df = Agent(response, description = "You are an expert Data Analyst and python developer whose sole responsibility is to generate the most efficient and accurate python code that will handle the given query. Your job is to understand the given sample dataframe thoroughly by analyzing all the columns, their datatype etc and the given query. After you are done with the analysis, generate a meaningful, syntactically and semantically correct python code.",config={"llm": llm_pa, "enforce_privacy": True, "verbose": True, "enable_cache":False, "max_retries": 10, "custom_whitelisted_dependencies": ["re"]})
# pandas_ai_agent_with_new_df.rephrase_query("Split the data in the Value column into separate columns and based on all kinds of special characters")
third_response = pandas_ai_agent_with_new_df.chat("Split the data in the Value column into separate columns and based on all kinds of special characters", output_type="dataframe")
third_response

2024-11-27 14:53:02 [INFO] Question: Split the data in the Value column into separate columns and based on all kinds of special characters
2024-11-27 14:53:02 [INFO] Running PandasAI with langchain_chat-databricks LLM...
2024-11-27 14:53:02 [INFO] Prompt ID: c4c3c740-c20d-4ee7-a033-8ccfab1cc222
2024-11-27 14:53:02 [INFO] Executing Pipeline: GenerateChatPipeline
2024-11-27 14:53:02 [INFO] Executing Step 0: ValidatePipelineInput
2024-11-27 14:53:02 [INFO] Executing Step 1: CacheLookup
2024-11-27 14:53:02 [INFO] Executing Step 2: PromptGeneration
2024-11-27 14:53:02 [INFO] Using prompt: <dataframe>
dfs[0]:456x8
"2023
PEP Period","2023
PEP WK","2023
TGT WK","2023
Sunday Start",TPM Pending Close,"2023
CSD AD",Product,Value
P4W1,8,Nov wk2,2023-04-16 00:00:00,2023-07-29 00:00:00,Coke & Pepper 12pks 3/$18 MM (show 2) Pepsi & KDP 2/$11 MM (show 2) 803924201,CSD 24pk cans,20% Circle  IVY Id 212794203
P4W4,26,Sep wk4,2023-08-27 00:00:00,2023-11-11 00:00:00,KO Ad (KDP included) BOGO 50%,CSD 10pk mini cans,"Buy 3, get 20% off TC"
P10W4,16,Aug wk3,2023-06-25 00:00:00,2023-02-04 00:00:00,KDP 3/$15,PEP 12pk cans,"3/$6 TPC
362894325"
</dataframe>




Update this initial code:
```python
# TODO: import the required dependencies
import pandas as pd

# Write code here

# Declare result var:
type (must be "dataframe"), value must be pd.DataFrame or pd.Series. Example: { "type": "dataframe", "value": pd.DataFrame({...}) }

```



### QUERY
 Split the data in the Value column into separate columns and based on all kinds of special characters

Variable `dfs: list[pd.DataFrame]` is already declared.

At the end, declare "result" variable as a dictionary of type and value.

If you are asked to plot a chart, use "matplotlib" for charts, save as png.


Generate python code and return full updated code:
2024-11-27 14:53:02 [INFO] Executing Step 3: CodeGenerator
2024-11-27 14:53:07 [INFO] Prompt used:
             You are an expert Data Analyst and python developer whose sole responsibility is to generate the most efficient and accurate python code that will handle the given query. Your job is to understand the given sample dataframe thoroughly by analyzing all the columns, their datatype etc and the given query. After you are done with the analysis, generate a meaningful, syntactically and semantically correct python code.
<dataframe>
dfs[0]:456x8
"2023
PEP Period","2023
PEP WK","2023
TGT WK","2023
Sunday Start",TPM Pending Close,"2023
CSD AD",Product,Value
P4W1,8,Nov wk2,2023-04-16 00:00:00,2023-07-29 00:00:00,Coke & Pepper 12pks 3/$18 MM (show 2) Pepsi & KDP 2/$11 MM (show 2) 803924201,CSD 24pk cans,20% Circle  IVY Id 212794203
P4W4,26,Sep wk4,2023-08-27 00:00:00,2023-11-11 00:00:00,KO Ad (KDP included) BOGO 50%,CSD 10pk mini cans,"Buy 3, get 20% off TC"
P10W4,16,Aug wk3,2023-06-25 00:00:00,2023-02-04 00:00:00,KDP 3/$15,PEP 12pk cans,"3/$6 TPC
362894325"
</dataframe>




Update this initial code:
```python
# TODO: import the required dependencies
import pandas as pd

# Write code here

# Declare result var:
type (must be "dataframe"), value must be pd.DataFrame or pd.Series. Example: { "type": "dataframe", "value": pd.DataFrame({...}) }

```



### QUERY
 Split the data in the Value column into separate columns and based on all kinds of special characters

Variable `dfs: list[pd.DataFrame]` is already declared.

At the end, declare "result" variable as a dictionary of type and value.

If you are asked to plot a chart, use "matplotlib" for charts, save as png.


Generate python code and return full updated code:

2024-11-27 14:53:07 [INFO] Code generated:
            ```
            # TODO: import the required dependencies
import pandas as pd
import re

# Write code here
def split_value_column(df):
    # Split the 'Value' column into separate columns based on special characters
    new_cols = df['Value'].str.split(r'[^a-zA-Z0-9\s]+', expand=True)

    # Drop the original 'Value' column
    df = df.drop('Value', axis=1)

    # Add the new columns to the dataframe
    df = pd.concat([df, new_cols], axis=1)

    return df

# Apply the function to the dataframe
dfs[0] = split_value_column(dfs[0])

# Declare result var:
result = { "type": "dataframe", "value": dfs[0] }
            ```

2024-11-27 14:53:07 [INFO] Executing Step 4: CachePopulation
2024-11-27 14:53:07 [INFO] Executing Step 5: CodeCleaning
2024-11-27 14:53:07 [INFO]
Code running:
```
def split_value_column(df):
    new_cols = df['Value'].str.split('[^a-zA-Z0-9\\s]+', expand=True)
    df = df.drop('Value', axis=1)
    df = pd.concat([df, new_cols], axis=1)
    return df


dfs[0] = split_value_column(dfs[0])
result = {'type': 'dataframe', 'value': dfs[0]}
        ```
2024-11-27 14:53:07 [INFO] Executing Step 6: CodeExecution
2024-11-27 14:53:07 [INFO] Executing Step 7: ResultValidation
2024-11-27 14:53:07 [INFO] Answer: {'type': 'dataframe', 'value':     2023\nPEP Period  2023\nPEP WK 2023\nTGT WK   2023\nSunday Start  \
0              P13W5            53      Dec wk5  2022-12-25 00:00:00
1               P1W1             1      Jan wk1  2023-01-01 00:00:00
2               P1W2             2      Jan wk2  2023-01-08 00:00:00
3               P1W3             3      Jan wk3  2023-01-15 00:00:00
4               P1W4             4      Jan wk4  2023-01-22 00:00:00
..               ...           ...          ...                  ...
451            P13W4            52      Dec wk5  2023-12-24 00:00:00
452             P1W1             1      Jan wk1  2023-12-31 00:00:00
453             P1W2             2      Jan wk2  2024-01-07 00:00:00
454             P1W3             3      Jan wk3  2024-01-14 00:00:00
455             P1W4             4      Jan wk4  2024-01-21 00:00:00

       TPM Pending Close                                       2023\nCSD AD  \
0    2022-12-31 00:00:00               3/$15 MB Tri Man + 25% Circle 383275
1    2023-01-07 00:00:00     Tri-Man Spend $15, Save $3 + 20% Circle 383273
2    2023-01-14 00:00:00  KDP + Pepper 12pk cans 3/$15 + PEP 20% Circle ...
3    2023-01-21 00:00:00                                   PEP/KDP 3/$15 MB
4    2023-01-28 00:00:00                   PEP/KDP 3/$15 MB +25% TC Digital
..                   ...                                                ...
451  2023-12-30 00:00:00  Buy three 12pk sodas, save 40% via Target Circ...
452  2024-01-06 00:00:00                Tri-Man Circle Buy 3, Save 20% off
453  2024-01-13 00:00:00  PEP 3/$16 MB all mkts except R300 (R300 B2G1 F...
454  2024-01-20 00:00:00  PEP 3/$16 MB all mkts except R300 (R300 B2G1 F...
455  2024-01-27 00:00:00  PEP 3/$16 MB all mkts except R300 (R300 B2G1 F...

           Product       0                1       2            3     4  \
0    PEP 12pk cans       3              15       25   TC\n383275  None
1    PEP 12pk cans  Spend                15   Save         3 TC     20
2    PEP 12pk cans      20   Circle\n383273    None         None  None
3    PEP 12pk cans       3               15    None         None  None
4    PEP 12pk cans       3              15       25           TC  None
..             ...     ...              ...     ...          ...   ...
451       20oz PET     EDV             None    None         None  None
452       20oz PET     EDV             None    None         None  None
453       20oz PET     EDV             None    None         None  None
454       20oz PET     EDV             None    None         None  None
455       20oz PET     EDV             None    None         None  None

               5     6     7
0           None  None  None
1     TC\n383273  None  None
2           None  None  None
3           None  None  None
4           None  None  None
..           ...   ...   ...
451         None  None  None
452         None  None  None
453         None  None  None
454         None  None  None
455         None  None  None

[456 rows x 15 columns]}
2024-11-27 14:53:07 [INFO] Executing Step 8: ResultParsing

,2023\nPEP Period,2023\nPEP WK,2023\nTGT WK,2023\nSunday Start,TPM Pending Close,2023\nCSD AD,Product,0,1,2,3,4,5,6,7
0,P13W5,53,Dec wk5,2022-12-25 00:00:00,2022-12-31 00:00:00,3/$15 MB Tri Man + 25% Circle 383275,PEP 12pk cans,3,15,25,TC\n383275,None,None,None,None
1,P1W1,1,Jan wk1,2023-01-01 00:00:00,2023-01-07 00:00:00,"Tri-Man Spend $15, Save $3 + 20% Circle 383273",PEP 12pk cans,Spend,15,Save,3 TC,20,TC\n383273,None,None
2,P1W2,2,Jan wk2,2023-01-08 00:00:00,2023-01-14 00:00:00,KDP + Pepper 12pk cans 3/$15 + PEP 20% Circle ...,PEP 12pk cans,20,Circle\n383273,None,None,None,None,None,None
3,P1W3,3,Jan wk3,2023-01-15 00:00:00,2023-01-21 00:00:00,PEP/KDP 3/$15 MB,PEP 12pk cans,3,15,None,None,None,None,None,None
4,P1W4,4,Jan wk4,2023-01-22 00:00:00,2023-01-28 00:00:00,PEP/KDP 3/$15 MB +25% TC Digital,PEP 12pk cans,3,15,25,TC,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
451,P13W4,52,Dec wk5,2023-12-24 00:00:00,2023-12-30 00:00:00,"Buy three 12pk sodas, save 40% via Target Circ...",20oz PET,EDV,None,None,None,None,None,None,None
452,P1W1,1,Jan wk1,2023-12-31 00:00:00,2024-01-06 00:00:00,"Tri-Man Circle Buy 3, Save 20% off",20oz PET,EDV,None,None,None,None,None,None,None
453,P1W2,2,Jan wk2,2024-01-07 00:00:00,2024-01-13 00:00:00,PEP 3/$16 MB all mkts except R300 (R300 B2G1 F...,20oz PET,EDV,None,None,None,None,None,None,None
454,P1W3,3,Jan wk3,2024-01-14 00:00:00,2024-01-20 00:00:00,PEP 3/$16 MB all mkts except R300 (R300 B2G1 F...,20oz PET,EDV,None,None,None,None,None,None,None
455,P1W4,4,Jan wk4,2024-01-21 00:00:00,2024-01-27 00:00:00,PEP 3/$16 MB all mkts except R300 (R300 B2G1 F...,20oz PET,EDV,None,None,None,None,None,None,None

In [4]:
print(pandas_ai_agent_with_new_df.last_code_generated)

# TODO: import the required dependencies
import pandas as pd
import re

# Write code here
def split_value_column(df):
    # Split the 'Value' column into separate columns based on special characters
    new_cols = df['Value'].str.split(r'[^a-zA-Z0-9\s]+', expand=True)

    # Drop the original 'Value' column
    df = df.drop('Value', axis=1)

    # Add the new columns to the dataframe
    df = pd.concat([df, new_cols], axis=1)

    return df

# Apply the function to the dataframe
dfs[0] = split_value_column(dfs[0])

# Declare result var:
result = { "type": "dataframe", "value": dfs[0] }

In [1]:
import pandas as pd
df= pd.read_excel("/home/ec2-user/Pepsico_Hackathon/Pepsico_Main_Hackathon/Pepsico_demo_new_gen_mapping_approach/uploaded_files/2023 CSD Target Activity Calendar.xlsx", sheet_name=["CSD Promo Activity 2023 "])

df = df["CSD Promo Activity 2023 "]
df.head()

,Unnamed: 0,2023 TARGET CSD PROMO PRICING CALENDAR,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,MM = Mandated Multiple (Must Buy),Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,Build week solo in TPM/CNA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2023\nPEP Period,2023\nPEP WK,2023\nTGT WK,2023\nSunday Start,TPM Pending Close,2023\nCSD AD,PEP 12pk cans,Dr Pepper 12pk cans,CSD 6pk PET,CSD 2L bottles,CSD 24pk cans,CSD 10pk mini cans,Bundaberg 4pk bottles,20oz PET
3,NaN,P13W5,53,Dec wk5,2022-12-25 00:00:00,2022-12-31 00:00:00,3/$15 MB Tri Man + 25% Circle 383275,3/$15 +25% TC\n383275,3/$15,EDV,EDV,EDV,EDV,EDV,EDV
4,Q1,P1W1,1,Jan wk1,2023-01-01 00:00:00,2023-01-07 00:00:00,"Tri-Man Spend $15, Save $3 + 20% Circle 383273","Spend $15, Save $3 TC + 20% TC\n383273","Spend $15, Save $3",4/$14 Ad,4/$9 TPC,EDV,EDV,EDV,EDV

In [6]:
import pandas as pd

data = {
    "Hello": [None, None, None],
    'Column1': [4, 5, 6],
    None: [7, None, 9]
}

df = pd.DataFrame(data)

# Retain columns with any non-NaN values
df = df.loc[:, (df.notna().any() | df.columns.notna())]

print(df)

  Hello  Column1  None
0  None        4   7.0
1  None        5   NaN
2  None        6   9.0

In [10]:
import openpyxl

path = "/home/ec2-user/Pepsico_Hackathon/Pepsico_Main_Hackathon/Pepsico_demo_new_gen_mapping_approach/uploaded_files/2021 Target Promo Calendar.xlsx"
sheet_name="CSD Promo Activity 2021"
workbook = openpyxl.load_workbook(path, data_only=True)
sheet = workbook[sheet_name]

# Create a dictionary to store merged cell information
merged_cells = {}

# Loop through merged cell ranges
for merged_range in sheet.merged_cells.ranges:
    # Get the top-left cell's value
    start_cell = sheet.cell(merged_range.min_row, merged_range.min_col)
    value = start_cell.value

    # Extract coordinates of merged cells
    for row in range(merged_range.min_row, merged_range.max_row + 1):
        for col in range(merged_range.min_col, merged_range.max_col + 1):
            merged_cells[(row, col)] = value

# Print the merged cell values
for coord, value in merged_cells.items():
    print(f"Cell {coord}: {value}")

import pandas as pd

# Create a list of rows
data = []
for row in sheet.iter_rows(values_only=True):
    data.append(list(row))

# Fill merged cells using the dictionary
for (row, col), value in merged_cells.items():
    data[row - 1][col - 1] = value  # Adjusting for zero-based indexing

# Convert to a DataFrame
df = pd.DataFrame(data[1:], columns=data[0])  # Skip header row for DataFrame
df

Cell (17, 1): Q2
Cell (18, 1): Q2
Cell (19, 1): Q2
Cell (20, 1): Q2
Cell (21, 1): Q2
Cell (22, 1): Q2
Cell (23, 1): Q2
Cell (24, 1): Q2
Cell (25, 1): Q2
Cell (26, 1): Q2
Cell (27, 1): Q2
Cell (28, 1): Q2
Cell (3, 7): 2021 ADS & DISPLAYS
Cell (3, 8): 2021 ADS & DISPLAYS
Cell (3, 9): 2021 ADS & DISPLAYS
Cell (3, 10): 2021 ADS & DISPLAYS
Cell (3, 11): 2021 ADS & DISPLAYS
Cell (3, 12): 2021 ADS & DISPLAYS
Cell (3, 13): 2021 ADS & DISPLAYS
Cell (3, 14): 2021 ADS & DISPLAYS
Cell (3, 15): 2021 ADS & DISPLAYS
Cell (3, 16): 2021 ADS & DISPLAYS
Cell (3, 17): 2021 ADS & DISPLAYS
Cell (3, 18): 2021 ADS & DISPLAYS
Cell (3, 19): 2021 ADS & DISPLAYS
Cell (3, 20): 2021 ADS & DISPLAYS
Cell (3, 21): 2021 ADS & DISPLAYS
Cell (3, 22): 2021 ADS & DISPLAYS
Cell (3, 23): 2021 ADS & DISPLAYS
Cell (57, 1): Q1 2020
Cell (58, 1): Q1 2020
Cell (59, 1): Q1 2020
Cell (60, 1): Q1 2020
Cell (61, 1): Q1 2020
Cell (29, 1): Q3
Cell (30, 1): Q3
Cell (31, 1): Q3
Cell (32, 1): Q3
Cell (33, 1): Q3
Cell (34, 1): Q3
Cell (35, 1): Q3
Cell (36, 1): Q3
Cell (37, 1): Q3
Cell (38, 1): Q3
Cell (39, 1): Q3
Cell (40, 1): Q3
Cell (41, 1): Q4
Cell (42, 1): Q4
Cell (43, 1): Q4
Cell (44, 1): Q4
Cell (45, 1): Q4
Cell (46, 1): Q4
Cell (47, 1): Q4
Cell (48, 1): Q4
Cell (49, 1): Q4
Cell (50, 1): Q4
Cell (51, 1): Q4
Cell (52, 1): Q4
Cell (53, 1): Q4
Cell (54, 1): Q4
Cell (55, 1): Q4
Cell (56, 1): Q4
Cell (5, 1): Q1
Cell (6, 1): Q1
Cell (7, 1): Q1
Cell (8, 1): Q1
Cell (9, 1): Q1
Cell (10, 1): Q1
Cell (11, 1): Q1
Cell (12, 1): Q1
Cell (13, 1): Q1
Cell (14, 1): Q1
Cell (15, 1): Q1
Cell (16, 1): Q1

,None,2021 TARGET CSD PROMO PRICING CALENDAR,None,None,None,None,None,MM = Mandated Multiple (Must Buy),None,BF = Brand Funded SMF = Shopper Marketing Funded TF = Target Funded TPM = Funded through TPM (not NCDA),...,None,None,None,None,None,None,None,None,None,None
0,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,None,None,None,None,None,Build week solo in TPM/CNA,2021 ADS & DISPLAYS,2021 ADS & DISPLAYS,2021 ADS & DISPLAYS,2021 ADS & DISPLAYS,...,None,None,None,None,None,None,None,None,None,None
2,None,2021\nPEP Period,2021\nPEP WK,2021\nTGT WK,2021\nSunday Start,TPM Pending Close,2020\nCSD AD,2021\nCSD AD,2021\nAD Liner,2021\nCircle (Cartwheel),...,CSD 8pk PET,Kickstart 16oz cans,Bundaberg 4pk bottles,20oz PET,bubly 16oz can,2020\nRockstar 16oz,Rockstar 16oz cans,Mtn Dew Rise 16oz cans,BANG 16oz cans,BANG 4pk cans
3,Q1,P1W1,1,Dec wk5,2020-12-27 00:00:00,2021-02-05 00:00:00,Grocery GI S$50G$10 GC (PEP 12pk cans 3/$10.50...,"Tri-manf. 12pk cans 35% off Target Circle, Tri...",None,35% off ALL CSD 12pk cans (TPM),...,EDV,EDV,$6.49 TPC,EDV,EDV,3/$4 TPC,4/$5 AD,None,EDV,EDV
4,Q1,P1W2,2,Jan wk1,2021-01-03 00:00:00,2021-02-05 00:00:00,PEP 12pk cans 3/$10.50,"PEP / KDP 12pk cans 2/$9 MB (no Pepper), PEP /...",None,Fri - Sun Only; 20% off CSD 12pk cans,...,EDV,EDV,EDV,EDV,EDV,EDV,EDV,None,EDV,EDV
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,None,P12W4,48,Nov wk4,2022-11-20 00:00:00,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
103,None,P13W1,49,Dec wk1,2022-11-27 00:00:00,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
104,None,P13W2,50,Dec wk2,2022-12-04 00:00:00,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
105,None,P13W3,51,Dec wk3,2022-12-11 00:00:00,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
106,None,P13W4,52,Dec wk4,2022-12-18 00:00:00,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [14]:
df.columns = [
    col if col is not None else f"Unnamed {idx+1}"
    for idx, col in enumerate(df.columns)
]
df.to_json()

'{"Unnamed 1":{"0":null,"1":null,"2":null,"3":"Q1","4":"Q1","5":"Q1","6":"Q1","7":"Q1","8":"Q1","9":"Q1","10":"Q1","11":"Q1","12":"Q1","13":"Q1","14":"Q1","15":"Q2","16":"Q2","17":"Q2","18":"Q2","19":"Q2","20":"Q2","21":"Q2","22":"Q2","23":"Q2","24":"Q2","25":"Q2","26":"Q2","27":"Q3","28":"Q3","29":"Q3","30":"Q3","31":"Q3","32":"Q3","33":"Q3","34":"Q3","35":"Q3","36":"Q3","37":"Q3","38":"Q3","39":"Q4","40":"Q4","41":"Q4","42":"Q4","43":"Q4","44":"Q4","45":"Q4","46":"Q4","47":"Q4","48":"Q4","49":"Q4","50":"Q4","51":"Q4","52":"Q4","53":"Q4","54":"Q4","55":"Q1 2020","56":"Q1 2020","57":"Q1 2020","58":"Q1 2020","59":"Q1 2020","60":null,"61":null,"62":null,"63":null,"64":null,"65":null,"66":null,"67":null,"68":null,"69":null,"70":null,"71":null,"72":null,"73":null,"74":null,"75":null,"76":null,"77":null,"78":null,"79":null,"80":null,"81":null,"82":null,"83":null,"84":null,"85":null,"86":null,"87":null,"88":null,"89":null,"90":null,"91":null,"92":null,"93":null,"94":null,"95":null,"96":null,"97":null,"98":null,"99":null,"100":null,"101":null,"102":null,"103":null,"104":null,"105":null,"106":null},"2021 TARGET CSD PROMO PRICING CALENDAR":{"0":null,"1":null,"2":"2021\\nPEP Period","3":"P1W1","4":"P1W2","5":"P1W3","6":"P1W4","7":"P2W1","8":"P2W2","9":"P2W3","10":"P2W4","11":"P3W1","12":"P3W2","13":"P3W3","14":"P3W4","15":"P4W1","16":"P4W2","17":"P4W3","18":"P4W4","19":"P5W1","20":"P5W2","21":"P5W3","22":"P5W4","23":"P6W1","24":"P6W2","25":"P6W3","26":"P6W4","27":"P7W1","28":"P7W2","29":"P7W3","30":"P7W4","31":"P8W1","32":"P8W2","33":"P8W3","34":"P8W4","35":"P9W1","36":"P9W2","37":"P9W3","38":"P9W4","39":"P10W1","40":"P10W2","41":"P10W3","42":"P10W4","43":"P11W1","44":"P11W2","45":"P11W3","46":"P11W4","47":"P12W1","48":"P12W2","49":"P12W3","50":"P12W4","51":"P13W1","52":"P13W2","53":"P13W3","54":"P13W4","55":"P1W1","56":"P1W2","57":"P1W3","58":"P1W4","59":"P2W1","60":"P2W2","61":"P2W3","62":"P2W4","63":"P3W1","64":"P3W2","65":"P3W3","66":"P3W4","67":"P4W1","68":"P4W2","69":"P4W3","70":"P4W4","71":"P5W1","72":"P5W2","73":"P5W3","74":"P5W4","75":"P6W1","76":"P6W2","77":"P6W3","78":"P6W4","79":"P7W1","80":"P7W2","81":"P7W3","82":"P7W4","83":"P8W1","84":"P8W2","85":"P8W3","86":"P8W4","87":"P9W1","88":"P9W2","89":"P9W3","90":"P9W4","91":"P10W1","92":"P10W2","93":"P10W3","94":"P10W4","95":"P11W1","96":"P11W2","97":"P11W3","98":"P11W4","99":"P12W1","100":"P12W2","101":"P12W3","102":"P12W4","103":"P13W1","104":"P13W2","105":"P13W3","106":"P13W4"},"Unnamed 3":{"0":null,"1":null,"2":"2021\\nPEP WK","3":1,"4":2,"5":3,"6":4,"7":5,"8":6,"9":7,"10":8,"11":9,"12":10,"13":11,"14":12,"15":13,"16":14,"17":15,"18":16,"19":17,"20":18,"21":19,"22":20,"23":21,"24":22,"25":23,"26":24,"27":25,"28":26,"29":27,"30":28,"31":29,"32":30,"33":31,"34":32,"35":33,"36":34,"37":35,"38":36,"39":37,"40":38,"41":39,"42":40,"43":41,"44":42,"45":43,"46":44,"47":45,"48":46,"49":47,"50":48,"51":49,"52":50,"53":51,"54":52,"55":1,"56":2,"57":3,"58":4,"59":5,"60":6,"61":7,"62":8,"63":9,"64":10,"65":11,"66":12,"67":13,"68":14,"69":15,"70":16,"71":17,"72":18,"73":19,"74":20,"75":21,"76":22,"77":23,"78":24,"79":25,"80":26,"81":27,"82":28,"83":29,"84":30,"85":31,"86":32,"87":33,"88":34,"89":35,"90":36,"91":37,"92":38,"93":39,"94":40,"95":41,"96":42,"97":43,"98":44,"99":45,"100":46,"101":47,"102":48,"103":49,"104":50,"105":51,"106":52},"Unnamed 4":{"0":null,"1":null,"2":"2021\\nTGT WK","3":"Dec wk5","4":"Jan wk1","5":"Jan wk2","6":"Jan wk3","7":"Jan wk4","8":"Feb wk1","9":"Feb wk2","10":"Feb wk3","11":"Feb wk4","12":"Mar wk1","13":"Mar wk2","14":"Mar wk3","15":"Mar wk4","16":"Mar wk5","17":"Apr wk1","18":"Apr wk2","19":"Apr wk3","20":"Apr wk4","21":"May wk1","22":"May wk2","23":"May wk3","24":"May wk4","25":"June wk1","26":"June wk2","27":"June wk3","28":"June wk4","29":"June wk5","30":"July wk1","31":"July wk2","32":"July wk3","33":"July wk4","34":"Aug wk1","35":"Aug wk2","36":"Aug wk3","37":"Aug wk4","38":"Sep wk1","39":"Sep wk2","40":"Sep wk3","41":"Sep wk4","42":"Sep wk5","43":"Oct wk1","44":"Oct wk2","45":"Oct wk3","46":"Oct wk4","47":"Nov wk1","48":"Nov wk2","49":"Nov wk3","50":"Nov wk4","51":"Dec wk1","52":"Dec wk2","53":"Dec wk3","54":"Dec wk4","55":"Dec wk5","56":"Jan wk1","57":"Jan wk2","58":"Jan wk3","59":"Jan wk4","60":"Feb wk1","61":"Feb wk2","62":"Feb wk3","63":"Feb wk4","64":"Mar wk1","65":"Mar wk2","66":"Mar wk3","67":"Mar wk4","68":"Mar wk5","69":"Apr wk1","70":"Apr wk2","71":"Apr wk3","72":"Apr wk4","73":"May wk1","74":"May wk2","75":"May wk3","76":"May wk4","77":"June wk1","78":"June wk2","79":"June wk3","80":"June wk4","81":"June wk5","82":"July wk1","83":"July wk2","84":"July wk3","85":"July wk4","86":"Aug wk1","87":"Aug wk2","88":"Aug wk3","89":"Aug wk4","90":"Sep wk1","91":"Sep wk2","92":"Sep wk3","93":"Sep wk4","94":"Sep wk5","95":"Oct wk1","96":"Oct wk2","97":"Oct wk3","98":"Oct wk4","99":"Nov wk1","100":"Nov wk2","101":"Nov wk3","102":"Nov wk4","103":"Dec wk1","104":"Dec wk2","105":"Dec wk3","106":"Dec wk4"},"Unnamed 5":{"0":null,"1":null,"2":"2021\\nSunday Start","3":1609027200000,"4":1609632000000,"5":1610236800000,"6":1610841600000,"7":1611446400000,"8":1612051200000,"9":1612656000000,"10":1613260800000,"11":1613865600000,"12":1614470400000,"13":1615075200000,"14":1615680000000,"15":1616284800000,"16":1616889600000,"17":1617494400000,"18":1618099200000,"19":1618704000000,"20":1619308800000,"21":1619913600000,"22":1620518400000,"23":1621123200000,"24":1621728000000,"25":1622332800000,"26":1622937600000,"27":1623542400000,"28":1624147200000,"29":1624752000000,"30":1625356800000,"31":1625961600000,"32":1626566400000,"33":1627171200000,"34":1627776000000,"35":1628380800000,"36":1628985600000,"37":1629590400000,"38":1630195200000,"39":1630800000000,"40":1631404800000,"41":1632009600000,"42":1632614400000,"43":1633219200000,"44":1633824000000,"45":1634428800000,"46":1635033600000,"47":1635638400000,"48":1636243200000,"49":1636848000000,"50":1637452800000,"51":1638057600000,"52":1638662400000,"53":1639267200000,"54":1639872000000,"55":1640476800000,"56":1641081600000,"57":1641686400000,"58":1642291200000,"59":1642896000000,"60":1643500800000,"61":1644105600000,"62":1644710400000,"63":1645315200000,"64":1645920000000,"65":1646524800000,"66":1647129600000,"67":1647734400000,"68":1648339200000,"69":1648944000000,"70":1649548800000,"71":1650153600000,"72":1650758400000,"73":1651363200000,"74":1651968000000,"75":1652572800000,"76":1653177600000,"77":1653782400000,"78":1654387200000,"79":1654992000000,"80":1655596800000,"81":1656201600000,"82":1656806400000,"83":1657411200000,"84":1658016000000,"85":1658620800000,"86":1659225600000,"87":1659830400000,"88":1660435200000,"89":1661040000000,"90":1661644800000,"91":1662249600000,"92":1662854400000,"93":1663459200000,"94":1664064000000,"95":1664668800000,"96":1665273600000,"97":1665878400000,"98":1666483200000,"99":1667088000000,"100":1667692800000,"101":1668297600000,"102":1668902400000,"103":1669507200000,"104":1670112000000,"105":1670716800000,"106":1671321600000},"Unnamed 6":{"0":null,"1":"Build week solo in TPM\\/CNA","2":"TPM Pending Close","3":1612483200000,"4":1612483200000,"5":1612483200000,"6":1612483200000,"7":1615507200000,"8":1615507200000,"9":1615507200000,"10":1615507200000,"11":1615507200000,"12":1617926400000,"13":1617926400000,"14":1617926400000,"15":1617926400000,"16":1620345600000,"17":1620345600000,"18":1620345600000,"19":1620345600000,"20":1623369600000,"21":1623369600000,"22":1623369600000,"23":1623369600000,"24":1623369600000,"25":1625788800000,"26":1625788800000,"27":1625788800000,"28":1625788800000,"29":1628208000000,"30":1628208000000,"31":1628208000000,"32":1628208000000,"33":1631232000000,"34":1631232000000,"35":1631232000000,"36":1631232000000,"37":1631232000000,"38":1633651200000,"39":1633651200000,"40":1633651200000,"41":1633651200000,"42":1636070400000,"43":1636070400000,"44":1636070400000,"45":1636070400000,"46":1639094400000,"47":1639094400000,"48":1639094400000,"49":1639094400000,"50":1639094400000,"51":1641513600000,"52":1641513600000,"53":1641513600000,"54":1641513600000,"55":1643932800000,"56":1643932800000,"57":1643932800000,"58":1643932800000,"59":1646956800000,"60":null,"61":null,"62":null,"63":null,"64":null,"65":null,"66":null,"67":null,"68":null,"69":null,"70":null,"71":null,"72":null,"73":null,"74":null,"75":null,"76":null,"77":null,"78":null,"79":null,"80":null,"81":null,"82":null,"83":null,"84":null,"85":null,"86":null,"87":null,"88":null,"89":null,"90":null,"91":null,"92":null,"93":null,"94":null,"95":null,"96":null,"97":null,"98":null,"99":null,"100":null,"101":null,"102":null,"103":null,"104":null,"105":null,"106":null},"Unnamed 7":{"0":null,"1":"2021 ADS & DISPLAYS","2":"2020\\nCSD AD","3":"Grocery GI S$50G$10 GC (PEP 12pk cans 3\\/$10.50, Tri-Man 2L 4\\/$5)","4":"PEP 12pk cans 3\\/$10.50","5":"PEP 12pk cans 3\\/$10.50","6":"PEP Soda GI S$15G$5 GC (PEP 24pk cans $6.99)","7":"Grocery GI S$50G$10 GC (PEP\\/KO 24pk $5.99)","8":"KO 12pk cans & 8pk PET 3\\/$11  \\n35% off Target Circle (Sun only - in AD)","9":"KO 12pk cans & 8pk PET 3\\/$11","10":"KO 12pk cans & 8pk PET 3\\/$11","11":"KO Soda GI S$15G$5 GC (KO 12pk cans & 8pk PET 3\\/$11)","12":"PEP \\/ KDP 12pk cans 3\\/$10.50","13":"PEP \\/ KDP 12pk cans 3\\/$10.50","14":"PEP \\/ KDP 12pk cans 3\\/$10.50","15":"PEP Beverages GI B$20G$5 GC (PEP 12pk cans 3\\/$10.50)","16":"AD canceled due to CVID-19 (KO 12pk cans EDV on Soda Bulk)","17":"KO 12pk cans 35% off Target Circle","18":"AD canceled due to CVID-19 (KO 12pk cans EDV on Soda Bulk)","19":"KO 12pk cans & 8pk PET $4.49","20":"PEP \\/ KDP 12pk cans 2\\/$9","21":"PEP \\/ KDP 12pk cans 2\\/$9","22":"PEP \\/ KDP 12pk cans 2\\/$9","23":"PEP \\/ KO \\/ KDP 12pk cans 3\\/$12","24":"PEP \\/ KO \\/ KDP 12pk cans 3\\/$12 (25% off Circle Sun-Mon)\\nPEP \\/ KO 6pk PET 4\\/$11","25":"KO \\/ KDP 12pk cans & 8pk PET 3\\/$12","26":"KO \\/ KDP 12pk cans & 8pk PET 3\\/$12, PEP 6pk PET 4\\/$11 (AB Cut)","27":"KO \\/ KDP 12pk cans & 8pk PET 3\\/$12","28":"KO Beverage GI; Spend $25 Get $5 GC (12pk cans EDV - not pictured, 6pk PET 3\\/$9 - pictured)","29":"PEP \\/ KO \\/ KDP 12pk cans 3\\/$12 \\n(25% Target Circle Over-lay)","30":"PEP 6pk PET & 6pk mini cans 4\\/$11, KO 6pk PET 4\\/$11","31":"PEP 6pk PET & 6pk mini cans 4\\/$11","32":"PEP 6pk PET & 6pk mini cans 4\\/$11","33":"PepsiCo GI B$20G$5 GC (PEP 12pk cans 3\\/$12)","34":"KO \\/ Dr Pepper 12pk cans & 8pk PET 3\\/$12, Tri-manf. 10pk mini cans 2\\/$7","35":"KO \\/ Dr Pepper 12pk cans & 8pk PET 3\\/$12 MUST BUY, Tri-manf. 10pk mini cans 2\\/$7","36":"KO \\/ Dr Pepper 12pk cans & 8pk PET 3\\/$12 MB, Tri-manf. 10pk mini cans 2\\/$7","37":"KO Soda GI; S$15 G$5 GC, Tri-manf. 10pk mini cans 2\\/$7","38":"Tri-manf. 12pk cans 3\\/$12 MB + Target Circle","39":"Tri-manf. 12pk cans 3\\/$12 MB + Target Circle (Sun-Mon only), Tri-manf. 6pk PET 4\\/$11 MB (non-Liquor)","40":"PEP \\/ KDP 12pk cans 2\\/$9 MB, KO \\/ KDP 6pk PET $2.99 (non-Liquor)","41":"PEP \\/ KDP 12pk cans 3\\/$12 MB, KO \\/ KDP 6pk PET $2.99 (non-Liquor)","42":"PEP \\/ KDP 12pk cans 3\\/$12 MB, KO \\/ KDP 6pk PET $2.99 (non-Liquor)","43":"PepsiCo GI B$20G$5 GC (PEP 12pk cans 3\\/$12 MB), KO \\/ KDP 6pk PET 4\\/$12 (non-Liquor)","44":"KO \\/ Dr Pepper 12pk cans & 8pk PET 3\\/$12 (Buy 3 KO 12pks Get a Free AHA 8pk), PEP 6pk PET 4\\/$12 MB (non-Liquor Stores)","45":"KO 12pk cans & 8pk PET 3\\/$12, PEP 6pk PET 4\\/$12 MB (non-Liquor Stores)","46":"KO GI (S$20 G$5 GC - all KO), Tri-Manf. 2L Buy One Get One 50% Off, PEP 6pk PET 4\\/$12 (non-Liquor Stores)","47":"KO 12pk cans & 8pk PET 3\\/$12","48":"PEP \\/ KDP 12pk cans 3\\/$12 MB (no Pepper), Tri-manf. 2L 4\\/$6 MB","49":"PEP \\/ KDP 12pk cans 3\\/$12 MB (no Pepper) + 25% off Circle, Tri-manf. 2L 4\\/$6 MB, Target Grocery GI; Spend $50 Save $10","50":"PEP \\/ KDP 12pk cans 3\\/$12 MB (no Pepper), KO 12pk cans 20% off Target Circle, Tri-manf. 2L 4\\/$6 MB","51":"PepsiCo GI B$20G$5 GC (PEP 12pk cans 3\\/$12 MB - no Pepper)","52":"KO 12pk cans & 8pk PET 3\\/$12 MB","53":"KO 12pk cans & 8pk PET 3\\/$12 MB, Tri-manf. 2L 4\\/$6 MB","54":"Tri-manf. 12pk cans 3\\/$12 MB, Tri-manf. 2L 4\\/$6 MB","55":"Tri-manf. 12pk cans 35% off Target Circle, Tri-manf. 2L 4\\/$6 MB, Rockstar 16oz cans 4\\/$5","56":"PEP \\/ KDP 12pk cans 2\\/$9 MB (no Pepper), PEP \\/ KO 24pk cans 2\\/$15 MB (includes Pepper)","57":"PEP \\/ KDP 12pk cans 2\\/$9 MB (no Pepper), PEP \\/ KO 24pk cans 2\\/$15 MB (includes Pepper)","58":"PEP \\/ KDP 12pk cans 2\\/$9 MB (no Pepper), PEP \\/ KO 24pk cans 2\\/$15 MB (includes Pepper)","59":"PepsiCo GI B$20G$5 GC (PEP 12pk cans 3\\/$12 MB - no Pepper), PEP \\/ KO 24pk cans 2\\/$15 MB (includes Pepper)","60":null,"61":null,"62":null,"63":null,"64":null,"65":null,"66":null,"67":null,"68":null,"69":null,"70":null,"71":null,"72":null,"73":null,"74":null,"75":null,"76":null,"77":null,"78":null,"79":null,"80":null,"81":null,"82":null,"83":null,"84":null,"85":null,"86":null,"87":null,"88":null,"89":null,"90":null,"91":null,"92":null,"93":null,"94":null,"95":null,"96":null,"97":null,"98":null,"99":null,"100":null,"101":null,"102":null,"103":null,"104":null,"105":null,"106":null},"MM = Mandated Multiple (Must Buy)":{"0":null,"1":"2021 ADS & DISPLAYS","2":"2021\\nCSD AD","3":"Tri-manf. 12pk cans 35% off Target Circle, Tri-manf. 2L 4\\/$6 MB, Rockstar 16oz cans 4\\/$5","4":"PEP \\/ KDP 12pk cans 2\\/$9 MB (no Pepper), PEP \\/ KO 24pk cans 2\\/$15 MB (includes Pepper)","5":"PEP \\/ KDP 12pk cans 2\\/$9 MB (no Pepper), PEP \\/ KO 24pk cans 2\\/$15 MB (includes Pepper)","6":"PEP \\/ KDP 12pk cans 2\\/$9 MB (no Pepper), PEP \\/ KO 24pk cans 2\\/$15 MB (includes Pepper)","7":"PepsiCo GI B$20G$5 GC (PEP 12pk cans 3\\/$12 MB - no Pepper), PEP \\/ KO 24pk cans 2\\/$15 MB (includes Pepper)","8":"Tr-Manf. 12pk cans 3\\/$12 MB, PEP 6pk PET 4\\/$12 MB (no Pepper - non-Liq ADs only)","9":"KO \\/ KDP 12pk cans & 8pk PET 2\\/$9, PEP 6pk PET 4\\/$12 MB (no Pepper - non-Liq ADs only)","10":"KO \\/ KDP 12pk cans & 8pk PET 3\\/$13, PEP 6pk PET 4\\/$12 MB (no Pepper - non-Liq ADs only)","11":"KO 12pk cans & 8pk PET 3\\/$13, PEP 6pk PET 4\\/$12 MB (no Pepper - non-Liq ADs only)","12":"KO Gift Card (Spend $20 Get $5 GC), PEP 6pk PET 4\\/$12 MB (no Pepper - non-Liq ADs only)","13":"Tri-Manf. 12pk cans 20% off Target Circle","14":"PEP 12pk cans 3\\/$13 MB (no Pepper)","15":"PEP \\/ KDP 12pk cans 3\\/$12 MB (show 3 w\\/ Pepper)","16":"Tri-Manf. 12pk cans 3\\/$12 MB","17":"KO \\/ KDP 12pk cans 3\\/$13","18":"KO \\/ KDP 12pk cans 3\\/$13, PEP 6pk PET 3\\/$8 MB (no Pepper - non-Liq ADs only)","19":"KO 12pk cans & 8pk PET 3\\/$13, PEP 6pk PET 3\\/$8 MB (no Pepper - non-Liq ADs only)","20":"PEP 12pk cans 3\\/$12 MB (no Pepper)","21":"PEP \\/ KDP 12pk cans 3\\/$12 MB (show 3 w\\/ Pepper)","22":"PEP \\/ KDP 12pk cans 3\\/$12 MB (show 3 w\\/ Pepper)","23":"PepsiCo GI B$20G$5 GC (PEP 12pk cans 3\\/$12 MB - no Pepper)","24":"PEP \\/ KO \\/ KDP 12pk cans 3\\/$12 MB + 25% off Circle","25":"PEP \\/ KO \\/ KDP 12pk cans 3\\/$12 MB + 25% off Circle (Sun-Mon only), PEP \\/ KO 6pk PET 4\\/$11 MB (no Pepper - non-Liq ADs only)","26":"KO 12pk cans & 8pk PET 3\\/$13, PEP 6pk PET 4\\/$11 MB (no Pepper - non-Liq ADs only)","27":"KO\\/ KDP 12pk cans & 8pk PET 3\\/$13, PEP 6pk PET 4\\/$11 MB (no Pepper - non-Liq ADs only)","28":"KO 12pk cans & 8pk PET 3\\/$13 + Free $5 Target Gift Card when you spend $15 or more on Select Coke Products","29":"PEP \\/ KO \\/ KDP 12pk cans 3\\/$12 MB + 25% off Circle","30":"PEP \\/ KO \\/ KDP 12pk cans 3\\/$12 MB + 25% off Circle (Sun-Mon only), PEP \\/ KO 6pk PET 4\\/$11 MB (no Pepper)","31":"PEP \\/ KDP 12pk cans 3\\/$12 MB (show 3 w\\/ Pepper)","32":"PEP 12pk cans 3\\/$12 MB (no Pepper)","33":"PepsiCo GI B$20G$5 GC (PEP 12pk cans 3\\/$12 MB - no Pepper)","34":"KO & Pepper 12pk cans & 8pk PET 3\\/$13","35":"KO & Pepper 12pk cans & 8pk PET 3\\/$13","36":"KO 12pk cans & 8pk PET 3\\/$14","37":"Spend $20, Get a $5 Gift Card off Select Coca-Cola Products","38":"PEP \\/ KO \\/ KDP 12pk cans 3\\/$13 MB or 3\\/$14MB (25% off Circle)","39":"PEP \\/ KO \\/ KDP 12pk cans 3\\/$13 MB or 3\\/$14MB + 25% off Circle (Sun-Mon only), PEP \\/ KO \\/ KDP 6pk PET 4\\/$11 MB ","40":"Pepsi 12pks 3\\/$13 MM Does NOT include Dr. Pepper (show 1)","41":"Tri Man 12pk soda 20% off with Target Circle (show 3) Fun Run; 349577","42":"PEP \\/ KDP 12pk cans 3\\/$13 MB","43":"PepsiCo GI B$20G$5 GC (PEP 12pk cans 3\\/$13 MB)","44":"PEP\\/ KDP 12pk cans 3\\/$14MB- NCDA Funded","45":"PEP\\/ KDP 12pk cans 3\\/$14MB- NCDA Funded","46":"PEP 12pk cans 3\\/$13MB (3\\/$14 NE) & PepsiCo GI S$20G$5 Frito\\/Pepsi - NCDA Funded","47":"PEP 12pk Cans 3\\/$14 MB- NCDA Funded","48":"PEP\\/KDP  12pk cans 3\\/$13 MB","49":"PEP \\/ KO \\/ KDP 12pk cans 3\\/$13 MB","50":"PEP \\/ KDP 12pk cans 3\\/$13 MB","51":"PepsiCo GI B$20G$5 GC (PEP 12pk cans 3\\/$13 MB - no Pepper)","52":"KO 12pk cans & 8pk PET 3\\/$13?","53":"KO 12pk cans & 8pk PET 3\\/$13","54":"PEP \\/ KO \\/ KDP 12pk cans 3\\/$13 MB","55":"PEP \\/ KO \\/ KDP 12pk cans 3\\/$15 MB +20% Off Circle","56":"PEP  12pk cans 3\\/$13 MB","57":"PEP \\/ KDP 12pk cans 3\\/$13 MB","58":"PEP \\/ KDP 12pk cans 3\\/$13 MB","59":"PepsiCo GI B$20G$5 GC (PEP 12pk cans 3\\/$13 MB)","60":null,"61":null,"62":null,"63":null,"64":null,"65":null,"66":null,"67":null,"68":null,"69":null,"70":null,"71":null,"72":null,"73":null,"74":null,"75":null,"76":null,"77":null,"78":null,"79":null,"80":null,"81":null,"82":null,"83":null,"84":null,"85":null,"86":null,"87":null,"88":null,"89":null,"90":null,"91":null,"92":null,"93":null,"94":null,"95":null,"96":null,"97":null,"98":null,"99":null,"100":null,"101":null,"102":null,"103":null,"104":null,"105":null,"106":null},"Unnamed 9":{"0":null,"1":"2021 ADS & DISPLAYS","2":"2021\\nAD Liner","3":null,"4":null,"5":null,"6":null,"7":null,"8":null,"9":null,"10":null,"11":null,"12":null,"13":null,"14":null,"15":null,"16":null,"17":null,"18":null,"19":null,"20":null,"21":null,"22":"6pk PET 4\\/$11","23":"6pk PET 4\\/$11","24":null,"25":null,"26":null,"27":null,"28":null,"29":null,"30":null,"31":"6pk PET & mini can 4\\/$11","32":"6pk PET & mini can 4\\/$11","33":null,"34":null,"35":null,"36":null,"37":null,"38":null,"39":"6pk PET 4\\/$11MM","40":"6pk PET 4\\/$11","41":"6pk PET 4\\/$11","42":"6pk PET 4\\/$11 MM RHB","43":null,"44":null,"45":null,"46":null,"47":null,"48":null,"49":"2L Tri-Man 4\\/$7","50":"2L Tri-Man 4\\/$7","51":"6pk PET 4\\/$11","52":null,"53":"2L Tri-Man 4\\/$7","54":"2L Tri-Man 4\\/$7","55":"2L Tri-Man 4\\/$7","56":"6pk PET 4\\/$12MB","57":"6pk PET 4\\/$12MB","58":"6pk PET 4\\/$12MB","59":"6pk PET 4\\/$12MB","60":null,"61":null,"62":null,"63":null,"64":null,"65":null,"66":null,"67":null,"68":null,"69":null,"70":null,"71":null,"72":null,"73":null,"74":null,"75":null,"76":null,"77":null,"78":null,"79":null,"80":null,"81":null,"82":null,"83":null,"84":null,"85":null,"86":null,"87":null,"88":null,"89":null,"90":null,"91":null,"92":null,"93":null,"94":null,"95":null,"96":null,"97":null,"98":null,"99":null,"100":null,"101":null,"102":null,"103":null,"104":null,"105":null,"106":null},"BF = Brand Funded    SMF = Shopper Marketing Funded    TF = Target Funded    TPM = Funded through TPM (not NCDA)":{"0":null,"1":"2021 ADS & DISPLAYS","2":"2021\\nCircle (Cartwheel)","3":"35% off ALL CSD 12pk cans (TPM)","4":"Fri - Sun Only; 20% off CSD 12pk cans","5":"Fri - Sun Only; 20% off CSD 12pk cans","6":"Fri - Sat Only; 20% off CSD 12pk cans","7":null,"8":null,"9":null,"10":null,"11":null,"12":null,"13":"20% off CSD 12pk cans (TPM)","14":null,"15":null,"16":null,"17":"30% off Mtn Dew RISE (BF)","18":"30% off Mtn Dew RISE (BF)","19":"Central Division Only:  20% off TM Mtn Dew, 20% off TM Pepsi","20":"30% off Rockstar 16oz cans (TPM)","21":"30% off Rockstar 16oz cans (TPM)","22":null,"23":null,"24":"25% off CSD 12pk cans (TPM)","25":"Sun-Mon only:  25% off CSD 12pk cans (TPM)","26":null,"27":null,"28":null,"29":"25% off CSD 12pk cans (TPM)","30":"Sun-Mon only:  25% off CSD 12pk cans (TPM)","31":null,"32":null,"33":null,"34":null,"35":null,"36":"15% Of

In [11]:
df_old= pd.read_excel(path, sheet_name=[sheet_name])

df_o = df_old[sheet_name]
df_o

,Unnamed: 0,2021 TARGET CSD PROMO PRICING CALENDAR,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,MM = Mandated Multiple (Must Buy),Unnamed: 8,BF = Brand Funded SMF = Shopper Marketing Funded TF = Target Funded TPM = Funded through TPM (not NCDA),...,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,Build week solo in TPM/CNA,2021 ADS & DISPLAYS,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2021\nPEP Period,2021\nPEP WK,2021\nTGT WK,2021\nSunday Start,TPM Pending Close,2020\nCSD AD,2021\nCSD AD,2021\nAD Liner,2021\nCircle (Cartwheel),...,CSD 8pk PET,Kickstart 16oz cans,Bundaberg 4pk bottles,20oz PET,bubly 16oz can,2020\nRockstar 16oz,Rockstar 16oz cans,Mtn Dew Rise 16oz cans,BANG 16oz cans,BANG 4pk cans
3,Q1,P1W1,1,Dec wk5,2020-12-27 00:00:00,2021-02-05 00:00:00,Grocery GI S$50G$10 GC (PEP 12pk cans 3/$10.50...,"Tri-manf. 12pk cans 35% off Target Circle, Tri...",NaN,35% off ALL CSD 12pk cans (TPM),...,EDV,EDV,$6.49 TPC,EDV,EDV,3/$4 TPC,4/$5 AD,NaN,EDV,EDV
4,NaN,P1W2,2,Jan wk1,2021-01-03 00:00:00,2021-02-05 00:00:00,PEP 12pk cans 3/$10.50,"PEP / KDP 12pk cans 2/$9 MB (no Pepper), PEP /...",NaN,Fri - Sun Only; 20% off CSD 12pk cans,...,EDV,EDV,EDV,EDV,EDV,EDV,EDV,NaN,EDV,EDV
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102,NaN,P12W4,48,Nov wk4,2022-11-20 00:00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,NaN,P13W1,49,Dec wk1,2022-11-27 00:00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,NaN,P13W2,50,Dec wk2,2022-12-04 00:00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
105,NaN,P13W3,51,Dec wk3,2022-12-11 00:00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,NaN,P13W4,52,Dec wk4,2022-12-18 00:00:00,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
import openpyxl
path = "/home/ec2-user/Pepsico_Hackathon/Pepsico_Main_Hackathon/Pepsico_demo_new_gen_mapping_approach/uploaded_files/2021 Target Promo Calendar.xlsx"
sheet_name="CSD Promo Activity 2021"
workbook = openpyxl.load_workbook(path, data_only=True)
sheet = workbook[sheet_name]

df = pd.DataFrame(sheet.values)
df

,0,1,2,3,4,5,6,7,8,9,...,34,35,36,37,38,39,40,41,42,43
0,None,2021 TARGET CSD PROMO PRICING CALENDAR,None,None,None,None,None,MM = Mandated Multiple (Must Buy),None,BF = Brand Funded SMF = Shopper Marketing F...,...,None,None,None,None,None,None,None,None,None,None
1,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,None,None,None,None,None,Build week solo in TPM/CNA,2021 ADS & DISPLAYS,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,None,2021\nPEP Period,2021\nPEP WK,2021\nTGT WK,2021\nSunday Start,TPM Pending Close,2020\nCSD AD,2021\nCSD AD,2021\nAD Liner,2021\nCircle (Cartwheel),...,CSD 8pk PET,Kickstart 16oz cans,Bundaberg 4pk bottles,20oz PET,bubly 16oz can,2020\nRockstar 16oz,Rockstar 16oz cans,Mtn Dew Rise 16oz cans,BANG 16oz cans,BANG 4pk cans
4,Q1,P1W1,1,Dec wk5,2020-12-27 00:00:00,2021-02-05 00:00:00,Grocery GI S$50G$10 GC (PEP 12pk cans 3/$10.50...,"Tri-manf. 12pk cans 35% off Target Circle, Tri...",None,35% off ALL CSD 12pk cans (TPM),...,EDV,EDV,$6.49 TPC,EDV,EDV,3/$4 TPC,4/$5 AD,None,EDV,EDV
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,None,P12W4,48,Nov wk4,2022-11-20 00:00:00,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
104,None,P13W1,49,Dec wk1,2022-11-27 00:00:00,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
105,None,P13W2,50,Dec wk2,2022-12-04 00:00:00,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
106,None,P13W3,51,Dec wk3,2022-12-11 00:00:00,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
107,None,P13W4,52,Dec wk4,2022-12-18 00:00:00,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

#### Publix retailer

In [3]:
from langchain_core.output_parsers import PydanticOutputParser
from langchain_core.prompts import PromptTemplate
from pydantic import BaseModel, Field, model_validator

import openpyxl
import pandas as pd

path = "/home/ec2-user/Pepsico_Hackathon/Pepsico_Main_Hackathon/Pepsico_demo_new_gen_mapping_approach/uploaded_files/Copy of 2021 Promotions Calendar 11.03.21.xlsm"
sheet_name = "Q1 CSD"
workbook = openpyxl.load_workbook(path, data_only=True)
sheet = workbook[sheet_name]
# sheet[1]
# Create a dictionary to store merged cell information
merged_cells = {}

# Loop through merged cell ranges
for merged_range in sheet.merged_cells.ranges:
    # Get the top-left cell's value
    start_cell = sheet.cell(merged_range.min_row, merged_range.min_col)
    value = start_cell.value


    # Extract coordinates of merged cells
    for row in range(merged_range.min_row, merged_range.max_row + 1):
        for col in range(merged_range.min_col, merged_range.max_col + 1):
            merged_cells[(row, col)] = value


# Create a list of rows
data = []
for row in sheet.iter_rows(values_only=True):
    data.append(list(row))

# Fill merged cells using the dictionary
for (row, col), value in merged_cells.items():
    data[row - 1][col - 1] = value  # Adjusting for zero-based indexing

# Convert to a DataFrame
# df = pd.DataFrame(data[1:], columns=data[0])
unique_columns=[]
seen = {}
for col in df.columns:
    if col not in seen:
        unique_columns.append(col)
        seen[col]=1
    else:
        unique_columns.append(f"{col}_{seen[col]}")
        seen[col]+=1
df = pd.DataFrame(data[1:], columns=unique_columns)
display(df)
base_name_columns = []
for col in df.columns:
    print(col)
    if col is not None:
        base_name_columns.append(col.rsplit("_")[0] if '_' in col and col.rsplit("_")[-1].isdigit() else col)
    else:
        base_name_columns.append(col)
new_df = pd.DataFrame(data[1:], columns=base_name_columns)
display(new_df)

,None,None_1,None_2,None_3,2021 - Publix Promotion Calendar,2021 - Publix Promotion Calendar_1,2021 - Publix Promotion Calendar_2,Q1,Q1_1,Q1_2,Q1_3,Q1_4,Q1_5,Q1_6,Q1_7,Q1_8,Q1_9,Q1_10,Q1_11,None_4
0,None,None,None,None,Week #,Week #,Week #,Wk 1,Wk 2,Wk 3,Wk 4,Wk 5,Wk 6,Wk 7,Wk 8,Wk 9,Wk 10,Wk 11,Wk 12,None
1,None,None,None,None,LTSH/LTSH\n(1st week is Ad feature. Weeks 2-3 ...,LTSH/LTSH\n(1st week is Ad feature. Weeks 2-3 ...,LTSH/LTSH\n(1st week is Ad feature. Weeks 2-3 ...,2020-12-31 00:00:00,2020-12-31 00:00:00,2020-12-31 00:00:00,2021-01-21 00:00:00,2021-01-21 00:00:00,2021-01-21 00:00:00,2021-02-11 00:00:00,2021-02-18 00:00:00,2021-02-18 00:00:00,2021-02-18 00:00:00,2021-03-11 00:00:00,2021-03-18 00:00:00,None
2,None,None,None,None,Period,Period,Period,Period 1,Period 1,Period 1,Period 1,Period 2,Period 2,Period 2,Period 2,Period 3,Period 3,Period 3,Period 3,None
3,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
4,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
5,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
6,None,None,None,None,Co-ops,Co-ops,Co-ops,12/19 - 1/1,1/2 - 1/15,1/2 - 1/15,1/16 - 1/29,1/16 - 1/29,1/30 - 2/12,1/30 - 2/12,2/13 - 2/26,2/13 - 2/26,2/27 - 3/12,2/27 - 3/12,3/13 - 3/26,None
7,None,None,None,None,Co-ops,Co-ops,Co-ops,Holiday,New Year,New Year,Healthy You,Healthy You,Super Bowl,Super Bowl,HEART HEALTH,HEART HEALTH,SPRING BREAK,SPRING BREAK,MARCH MADNESS,None
8,None,None,None,None,Updated: 11/3/21,Updated: 11/3/21,Holidays,Holiday Ad dates ( 1/2 -...,00:00:00,00:00:00,Pre SuperBowl,SuperBowl,#REF!,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,None
9,None,None,None,None,Updated: 11/3/21,Updated: 11/3/21,Year,2020-12-31 00:00:00,2021-01-07 00:00:00,2021-01-14 00:00:00,2021-01-21 00:00:00,2021-01-28 00:00:00,2021-02-04 00:00:00,2021-02-11 00:00:00,2021-02-18 00:00:00,2021-02-25 00:00:00,2021-03-04 00:00:00,2021-03-11 00:00:00,2021-03-18 00:00:00,None
10,None,CSD,None,12pk / 18pk Cans,12pk Cans,All,2021,6.19,6.19,B2G1,B2G1,B2G1,B2G2,6.19,B2G1,B2G1,6.19,6.19,B2G1,None
11,None,CSD,None,12pk / 18pk Cans,None,None,2020,5.99,5.99,B2G1,B2G1,B2G2,5.99,5.99,B2G1,B2G1,B2G1,5.99,5.99,None
12,None,CSD,None,None,7.5oz 6pk Minis,All,2021,3.49,3.49,2/$6,2/$6,2/$6,2/$6,3.49,3.49,2/$6,3.49,3.49,3.49,None
13,None,CSD,None,None,None,None,2020,3.29,3.29,B2G1,B2G1,B2G1,3.29,2/$5,2/$5,2/$5,3.29,B2G1,3.29,None
14,None,CSD,None,None,7.5oz 10pk Minis,All,2021,4.99,4.99,4.99,4.99,4.99,4.99,4.99,4.99,4.99,4.99,4.99,4.99,None
15,None,CSD,None,None,None,None,2020,4.49,4.49,4.49,4.49,4.49,4.49,4.49,4.49,4.49,BOGO,4.49,4.49,None
16,None,CSD,None,None,2 Liters,All,2021,B2G1,B2G1,2.19,2.19,2.19,2.19,B2G2,2.19,2.19,B2G2,B2G2,2.19,None
17,None,CSD,None,None,None,None,2020,B2G2,B2G2,2.19,2.19,2.19,B2G1,B2G1,2.19,2.19,B2G1,2.19,B2G1,None
18,None,CSD,None,None,16.9oz 6pk PET,ALL,2021,BOGO,BOGO,5.79,5.79,5.79,5.79,BOGO,5.79,5.79,BOGO,BOGO,BOGO,None
19,None,CSD,None,None,None,None,2020,BOGO,BOGO,5.49,5.49,BOGO,BOGO,BOGO,5.49,5.49,5.49,BOGO,BOGO,None
20,None,CSD,None,None,12oz 8pk PET,All,2021,BOGO,BOGO,5.79,5.79,5.79,5.79,BOGO,5.79,5.79,BOGO,BOGO,BOGO,None
21,None,CSD,None,None,None,None,2020,BOGO,BOGO,5.49,5.49,BOGO,BOGO,BOGO,5.49,5.49,5.49,BOGO,BOGO,None
22,None,CSD,None,SS CD,1L Schweppes,All,2021,1.79,New Retail $1.99,3/$4,3/$4,3/$4,3/$4,3/$4,3/$4,1.99,1.99,1.99,1.99,None
23,None,CSD,None,SS CD,None,None,2020,1.79,3/$4,3/$4,3/$4,3/$4,3/$4,3/$4,1.79,1.79,1.79,1.79,1.79,None
24,None,CSD,None,SS CD,Schweppes 1783 4pks,All,2021,5.49,5.49,2/$9,2/$9,2/$9,2/$9,2/$9,2/$9,2/$9,2/$9,2/$9,2/$9,None
25,None,CSD,None,SS CD,None,None,2020,0,0,0,0,0,0,0,0,5.49,5.49,5.49,5.49,None
26,None,CSD,None,SS CD,Neon Zebra,All,2021,7.49,7.49,7.49,7.49,7.49,7.49,7.49,7.49,7.49,7.49,7.49,7.49,None
27,None,CSD,None,SS CD,None,None,2020,7.49,7.49,7.49,7.49,7.49,7.49,7.49,7.49,7.49,7.49,7.49,7.49,None
28,None,CSD,None,SS CD,Kickstart SS Cans,All,2021,5/$5,5/$5,5/$5,5/$5,5/$5,5/$5,5/$5,5/$5,5/$5,5/$5,5/$5,5/$5,None
29,None,CSD,None,SS CD,None,None,2020,5/$5,5/$5,5/$5,5/$5,5/$5,5/$5,5/$5,5/$5,5/$5,5/$5,5/$5,5/$5,None
30,None,CSD,None,SS CD,20oz CSD/NCB,All,2021,1.99,1.99,1.99,1.99,1.99,1.99,1.99,1.99,1.99,1.99,1.99,1.99,None
31,None,CSD,None,SS CD,None,None,2020,1.99,1.99,1.99,1.99,1.99,1.99,1.99,1.99,1.99,1.99,1.99,1.99,None
32,None,None,None,None,Miscellaneous,None,None,None,None,None,None,None,None,None,None,None,$1 off 12pk Mt Dew Zero,$1 off 12pk Mt Dew Zero,None,None
33,None,None,None,None,*Pending approval,**Flavor Excursion Program,**Flavor Excursion Program,Proposed,Ad,Temp Price Reduction,Mighty Mini Meals,In-Store Special,Coupon,Co-op,Stocking Spree,Effective Retail Date\n(NCB Co-ops Only),Best Meals at Home,Skip the Clip,EDV,None
34,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
35,None,None,None,None,None,None,None,None,None,None,None,`,None,None,None,None,None,None,None,None
36,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
37,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
38,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
39,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
40,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
41,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
42,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
43,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
44,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
45,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
46,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
47,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
48,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
49,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
50,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
51,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
52,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
53,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
54,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
55,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
56,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
57,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
58,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
59,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

None
None_1
None_2
None_3
2021 - Publix Promotion Calendar
2021 - Publix Promotion Calendar_1
2021 - Publix Promotion Calendar_2
Q1
Q1_1
Q1_2
Q1_3
Q1_4
Q1_5
Q1_6
Q1_7
Q1_8
Q1_9
Q1_10
Q1_11
None_4

,None,None,None,None,2021 - Publix Promotion Calendar,2021 - Publix Promotion Calendar,2021 - Publix Promotion Calendar,Q1,Q1,Q1,Q1,Q1,Q1,Q1,Q1,Q1,Q1,Q1,Q1,None
0,None,None,None,None,Week #,Week #,Week #,Wk 1,Wk 2,Wk 3,Wk 4,Wk 5,Wk 6,Wk 7,Wk 8,Wk 9,Wk 10,Wk 11,Wk 12,None
1,None,None,None,None,LTSH/LTSH\n(1st week is Ad feature. Weeks 2-3 ...,LTSH/LTSH\n(1st week is Ad feature. Weeks 2-3 ...,LTSH/LTSH\n(1st week is Ad feature. Weeks 2-3 ...,2020-12-31 00:00:00,2020-12-31 00:00:00,2020-12-31 00:00:00,2021-01-21 00:00:00,2021-01-21 00:00:00,2021-01-21 00:00:00,2021-02-11 00:00:00,2021-02-18 00:00:00,2021-02-18 00:00:00,2021-02-18 00:00:00,2021-03-11 00:00:00,2021-03-18 00:00:00,None
2,None,None,None,None,Period,Period,Period,Period 1,Period 1,Period 1,Period 1,Period 2,Period 2,Period 2,Period 2,Period 3,Period 3,Period 3,Period 3,None
3,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
4,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
5,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
6,None,None,None,None,Co-ops,Co-ops,Co-ops,12/19 - 1/1,1/2 - 1/15,1/2 - 1/15,1/16 - 1/29,1/16 - 1/29,1/30 - 2/12,1/30 - 2/12,2/13 - 2/26,2/13 - 2/26,2/27 - 3/12,2/27 - 3/12,3/13 - 3/26,None
7,None,None,None,None,Co-ops,Co-ops,Co-ops,Holiday,New Year,New Year,Healthy You,Healthy You,Super Bowl,Super Bowl,HEART HEALTH,HEART HEALTH,SPRING BREAK,SPRING BREAK,MARCH MADNESS,None
8,None,None,None,None,Updated: 11/3/21,Updated: 11/3/21,Holidays,Holiday Ad dates ( 1/2 -...,00:00:00,00:00:00,Pre SuperBowl,SuperBowl,#REF!,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,None
9,None,None,None,None,Updated: 11/3/21,Updated: 11/3/21,Year,2020-12-31 00:00:00,2021-01-07 00:00:00,2021-01-14 00:00:00,2021-01-21 00:00:00,2021-01-28 00:00:00,2021-02-04 00:00:00,2021-02-11 00:00:00,2021-02-18 00:00:00,2021-02-25 00:00:00,2021-03-04 00:00:00,2021-03-11 00:00:00,2021-03-18 00:00:00,None
10,None,CSD,None,12pk / 18pk Cans,12pk Cans,All,2021,6.19,6.19,B2G1,B2G1,B2G1,B2G2,6.19,B2G1,B2G1,6.19,6.19,B2G1,None
11,None,CSD,None,12pk / 18pk Cans,None,None,2020,5.99,5.99,B2G1,B2G1,B2G2,5.99,5.99,B2G1,B2G1,B2G1,5.99,5.99,None
12,None,CSD,None,None,7.5oz 6pk Minis,All,2021,3.49,3.49,2/$6,2/$6,2/$6,2/$6,3.49,3.49,2/$6,3.49,3.49,3.49,None
13,None,CSD,None,None,None,None,2020,3.29,3.29,B2G1,B2G1,B2G1,3.29,2/$5,2/$5,2/$5,3.29,B2G1,3.29,None
14,None,CSD,None,None,7.5oz 10pk Minis,All,2021,4.99,4.99,4.99,4.99,4.99,4.99,4.99,4.99,4.99,4.99,4.99,4.99,None
15,None,CSD,None,None,None,None,2020,4.49,4.49,4.49,4.49,4.49,4.49,4.49,4.49,4.49,BOGO,4.49,4.49,None
16,None,CSD,None,None,2 Liters,All,2021,B2G1,B2G1,2.19,2.19,2.19,2.19,B2G2,2.19,2.19,B2G2,B2G2,2.19,None
17,None,CSD,None,None,None,None,2020,B2G2,B2G2,2.19,2.19,2.19,B2G1,B2G1,2.19,2.19,B2G1,2.19,B2G1,None
18,None,CSD,None,None,16.9oz 6pk PET,ALL,2021,BOGO,BOGO,5.79,5.79,5.79,5.79,BOGO,5.79,5.79,BOGO,BOGO,BOGO,None
19,None,CSD,None,None,None,None,2020,BOGO,BOGO,5.49,5.49,BOGO,BOGO,BOGO,5.49,5.49,5.49,BOGO,BOGO,None
20,None,CSD,None,None,12oz 8pk PET,All,2021,BOGO,BOGO,5.79,5.79,5.79,5.79,BOGO,5.79,5.79,BOGO,BOGO,BOGO,None
21,None,CSD,None,None,None,None,2020,BOGO,BOGO,5.49,5.49,BOGO,BOGO,BOGO,5.49,5.49,5.49,BOGO,BOGO,None
22,None,CSD,None,SS CD,1L Schweppes,All,2021,1.79,New Retail $1.99,3/$4,3/$4,3/$4,3/$4,3/$4,3/$4,1.99,1.99,1.99,1.99,None
23,None,CSD,None,SS CD,None,None,2020,1.79,3/$4,3/$4,3/$4,3/$4,3/$4,3/$4,1.79,1.79,1.79,1.79,1.79,None
24,None,CSD,None,SS CD,Schweppes 1783 4pks,All,2021,5.49,5.49,2/$9,2/$9,2/$9,2/$9,2/$9,2/$9,2/$9,2/$9,2/$9,2/$9,None
25,None,CSD,None,SS CD,None,None,2020,0,0,0,0,0,0,0,0,5.49,5.49,5.49,5.49,None
26,None,CSD,None,SS CD,Neon Zebra,All,2021,7.49,7.49,7.49,7.49,7.49,7.49,7.49,7.49,7.49,7.49,7.49,7.49,None
27,None,CSD,None,SS CD,None,None,2020,7.49,7.49,7.49,7.49,7.49,7.49,7.49,7.49,7.49,7.49,7.49,7.49,None
28,None,CSD,None,SS CD,Kickstart SS Cans,All,2021,5/$5,5/$5,5/$5,5/$5,5/$5,5/$5,5/$5,5/$5,5/$5,5/$5,5/$5,5/$5,None
29,None,CSD,None,SS CD,None,None,2020,5/$5,5/$5,5/$5,5/$5,5/$5,5/$5,5/$5,5/$5,5/$5,5/$5,5/$5,5/$5,None
30,None,CSD,None,SS CD,20oz CSD/NCB,All,2021,1.99,1.99,1.99,1.99,1.99,1.99,1.99,1.99,1.99,1.99,1.99,1.99,None
31,None,CSD,None,SS CD,None,None,2020,1.99,1.99,1.99,1.99,1.99,1.99,1.99,1.99,1.99,1.99,1.99,1.99,None
32,None,None,None,None,Miscellaneous,None,None,None,None,None,None,None,None,None,None,None,$1 off 12pk Mt Dew Zero,$1 off 12pk Mt Dew Zero,None,None
33,None,None,None,None,*Pending approval,**Flavor Excursion Program,**Flavor Excursion Program,Proposed,Ad,Temp Price Reduction,Mighty Mini Meals,In-Store Special,Coupon,Co-op,Stocking Spree,Effective Retail Date\n(NCB Co-ops Only),Best Meals at Home,Skip the Clip,EDV,None
34,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
35,None,None,None,None,None,None,None,None,None,None,None,`,None,None,None,None,None,None,None,None
36,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
37,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
38,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
39,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
40,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
41,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
42,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
43,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
44,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
45,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
46,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
47,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
48,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
49,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
50,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
51,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
52,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
53,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
54,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
55,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
56,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
57,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
58,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
59,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

In [50]:
from langchain_core.output_parsers import PydanticOutputParser
from langchain_core.prompts import PromptTemplate
from pydantic import BaseModel, Field, model_validator

import openpyxl
import pandas as pd

# path = "/home/ec2-user/Pepsico_Hackathon/Pepsico_Main_Hackathon/Pepsico_demo_new_gen_mapping_approach/uploaded_files/2021 Target Promo Calendar.xlsx"
# sheet_name="CSD Promo Activity 2021"

path = "/home/ec2-user/Pepsico_Hackathon/Pepsico_Main_Hackathon/Pepsico_demo_new_gen_mapping_approach/uploaded_files/Copy of 2021 Promotions Calendar 11.03.21.xlsm"
sheet_name = "Q2 CSD"
workbook = openpyxl.load_workbook(path, data_only=True)
sheet = workbook[sheet_name]
# sheet[1]
# Create a dictionary to store merged cell information
merged_cells = {}

# Loop through merged cell ranges
for merged_range in sheet.merged_cells.ranges:
    # Get the top-left cell's value
    start_cell = sheet.cell(merged_range.min_row, merged_range.min_col)
    value = start_cell.value


    # Extract coordinates of merged cells
    for row in range(merged_range.min_row, merged_range.max_row + 1):
        for col in range(merged_range.min_col, merged_range.max_col + 1):
            merged_cells[(row, col)] = value


# Create a list of rows
data = []
for row in sheet.iter_rows(values_only=True):
    data.append(list(row))

# Fill merged cells using the dictionary
for (row, col), value in merged_cells.items():
    data[row - 1][col - 1] = value  # Adjusting for zero-based indexing

# Convert to a DataFrame
df = pd.DataFrame(data[1:], columns=data[0])

unique_columns=[]
seen = {}
for col in df.columns:
    if col not in seen:
        unique_columns.append(col)
        seen[col]=1
    else:
        unique_columns.append(f"{col}_{seen[col]}")
        seen[col]+=1
df = pd.DataFrame(data[1:], columns=unique_columns)

# Giving unique columns to avoid errors when passing it's json format in the prompt
# df.columns = [
#     col if col is not None else f"Unnamed {idx+1}"
#     for idx, col in enumerate(df.columns)
# ]
# df.head()
header_identification_template= '''
    <|begin_of_text|><|start_header_id|>system<|end_header_id|>

    You are an expert in CPG domain and you are highly capable in interpreting semi-structured tabular data. Your job is to extract a template after thorough analysis of the provided data in csv format. The first character in your response should be **{{**.

    <|eot_id|><|start_header_id|>user<|end_header_id|>

    DataFrame:{dataframe}

    1. Header Row Number:
    <Instructions>
    Ignore the row as an header if it is a merged index,look for others rows to find the header.For example if the whole row contains only 1 meaningful value and other values are null or "Unnamed" then ignore that row.
    Identify the specific row number that can serve as the header row for the dataset.
    This header row should contain the column names that are most representative of the actual data.
    This header row should contain unique values since header values cannot be duplicate.

    </Instructions>

    2. Data Start Row Number:
    <Instructions Note>:
        Identify the row number immediately following the header row where the actual data entries begin.
        This row should be the first row containing valid data under the identified header.

    3. Data End Row Number:
    <Instructions Note>:
        Identify the row number wherever the valid data entries ends.
        This row should be the last row containing valid data entries under identified header.

    The output should be provided as step-by-step instructions in the following format, don't give extra information:
        {{
        "Header_Row_Number":"<Row number where the header is located>",
        "Data_Start_Row_Number": "<Row number where valid data starts>",
        "Data_End_Row_Number": "<Row number where valid data ends>"
    }}
    Respond only with valid JSON. Do not write an introduction or summary.
    <|eot_id|><|start_header_id|>assistant<|end_header_id|>
    {{
    '''

from langchain_databricks import ChatDatabricks
import os
os.environ["DATABRICKS_HOST"] = "https://adb-6926527074777965.5.azuredatabricks.net"
os.environ["DATABRICKS_TOKEN"] = "dapi477662799536f4c6227fc9ba317d49f8-3"

model= ChatDatabricks(
        endpoint = "databricks-meta-llama-3-1-70b-instruct",
        max_tokens=8192,
        temperature=0,
    )


# Define your desired data structure.
class Header(BaseModel):
    Header_Row_Number: int = Field(description="Row number where the header is located")
    Data_Start_Row_Number: int = Field(description="Row number where valid data starts")
    Data_End_Row_Number: int = Field(description="Row number where valid data ends")

    # You can add custom validation logic easily with Pydantic.
    @model_validator(mode="before")
    @classmethod
    def header_row_less_than_data_start_row(cls, values: dict) -> dict:
        Header_Row_Number = values.get("Header_Row_Number")
        Data_Start_Row_Number = values.get("Data_Start_Row_Number")
        if Header_Row_Number and Data_Start_Row_Number and Header_Row_Number > Data_Start_Row_Number:
            raise ValueError("Invalid header row number")
        return values


# Set up a parser + inject instructions into the prompt template.
parser = PydanticOutputParser(pydantic_object=Header)

prompt = PromptTemplate(
    template=header_identification_template + "\n {format_instructions}",
    input_variables=["dataframe"],
    partial_variables={"format_instructions": parser.get_format_instructions()},
)


# And a query intended to prompt a language model to populate the data structure.
prompt_and_model = prompt | model
output = prompt_and_model.invoke({"dataframe": df.iloc[:15,:].to_json()})
result = parser.invoke(output)

steps_dict = result.dict()
print(steps_dict)

{'Header_Row_Number': 4, 'Data_Start_Row_Number': 5, 'Data_End_Row_Number': 11}

In [51]:
header_row = int(steps_dict["Header_Row_Number"])
data_start_row = int(steps_dict["Data_Start_Row_Number"])
data_end_row = len(df)

if all(col is None for col in df.iloc[header_row].to_list()):
    if header_row > 0:
        for i in reversed(range(header_row)):
            if not all(col is None for col in df.iloc[i].to_list()):
                df.columns = df.iloc[i]
                break
            else:
                df.columns = df.iloc[header_row]
    else:
        df.columns = df.iloc[header_row]
else:
    df.columns = df.iloc[header_row]  # Set header row as column names

df = df[data_start_row:data_end_row].reset_index(drop=True)
df.index = df.index + 1
# df=df.loc[:, df.columns.notna()]
df = df.loc[:, (df.notna().any() | df.columns.notna())] # Retain columns with any non-NaN values and also those columns which has some name but contains no values
df.head()

2,None,None,Period,Period,Period,Period 4,Period 4,Period 4,Period 4,Period 5,Period 5,Period 5,Period 5,Period 6,Period 6,Period 6,Period 6
1,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2,None,None,Co-ops,Co-ops,Co-ops,3/13 - 3/26,3/27 - 4/9,3/27 - 4/9,4/10 - 4/23,4/10 - 4/23,4/24 - 5/7,4/24 - 5/7,5/8 - 5/21,5/8 - 5/21,5/22 - 6/4,5/22 - 6/4,6/5 - 6/18
3,None,None,None,None,None,MARCH MADNESS,Easter 4/4,Easter 4/4,SPRING,SPRING,MOTHER'S DAY 5/9,MOTHER'S DAY 5/9,Grilling,Grilling,Memorial Day 5/31,Memorial Day 5/31,FATHER'S DAY 6/20
4,None,None,Updated: 11/3/21,Updated: 11/3/21,Holidays,00:00:00,00:00:00,Easter 11-day & 3 day Ads\n(4/11 - 4/21) & (4/...,Easter 11-day & 3 day Ads\n(4/11 - 4/21) & (4/...,#REF!,#REF!,#REF!,Pre-Mem,#REF!,None,#REF!,00:00:00
5,None,None,Updated: 11/3/21,Updated: 11/3/21,Year,2021-03-25 00:00:00,2021-04-01 00:00:00,2021-04-08 00:00:00,2021-04-15 00:00:00,2021-04-22 00:00:00,2021-04-29 00:00:00,2021-05-06 00:00:00,2021-05-13 00:00:00,2021-05-20 00:00:00,2021-05-27 00:00:00,2021-06-03 00:00:00,2021-06-10 00:00:00

In [41]:
df=df.dropna(how='all')
if all(col is None for col in df.columns):
    for i in range(len(df)):
        if not all(col is None for col in df.iloc[i].to_list()):
            df.columns = df.iloc[i]
            df = df[i+1:].reset_index(drop=True)
            break
df.head()

2,None,None,Co-ops,Co-ops,Co-ops,12/19 - 1/1,1/2 - 1/15,1/2 - 1/15,1/16 - 1/29,1/16 - 1/29,1/30 - 2/12,1/30 - 2/12,2/13 - 2/26,2/13 - 2/26,2/27 - 3/12,2/27 - 3/12,3/13 - 3/26
0,None,None,Co-ops,Co-ops,Co-ops,Holiday,New Year,New Year,Healthy You,Healthy You,Super Bowl,Super Bowl,HEART HEALTH,HEART HEALTH,SPRING BREAK,SPRING BREAK,MARCH MADNESS
1,None,None,Updated: 11/3/21,Updated: 11/3/21,Holidays,Holiday Ad dates ( 1/2 -...,00:00:00,00:00:00,Pre SuperBowl,SuperBowl,#REF!,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00
2,None,None,Updated: 11/3/21,Updated: 11/3/21,Year,2020-12-31 00:00:00,2021-01-07 00:00:00,2021-01-14 00:00:00,2021-01-21 00:00:00,2021-01-28 00:00:00,2021-02-04 00:00:00,2021-02-11 00:00:00,2021-02-18 00:00:00,2021-02-25 00:00:00,2021-03-04 00:00:00,2021-03-11 00:00:00,2021-03-18 00:00:00
3,CSD,12pk / 18pk Cans,12pk Cans,All,2021,6.19,6.19,B2G1,B2G1,B2G1,B2G2,6.19,B2G1,B2G1,6.19,6.19,B2G1
4,CSD,12pk / 18pk Cans,None,None,2020,5.99,5.99,B2G1,B2G1,B2G2,5.99,5.99,B2G1,B2G1,B2G1,5.99,5.99

In [44]:
df=df.dropna(how='all')
if all(col is None for col in df.columns):
    df.columns = df.iloc[0]
    df = df[1:].reset_index(drop=True)

In [45]:
df.head()

2,None,None,Co-ops,Co-ops,Co-ops,12/19 - 1/1,1/2 - 1/15,1/2 - 1/15,1/16 - 1/29,1/16 - 1/29,1/30 - 2/12,1/30 - 2/12,2/13 - 2/26,2/13 - 2/26,2/27 - 3/12,2/27 - 3/12,3/13 - 3/26
0,None,None,Co-ops,Co-ops,Co-ops,Holiday,New Year,New Year,Healthy You,Healthy You,Super Bowl,Super Bowl,HEART HEALTH,HEART HEALTH,SPRING BREAK,SPRING BREAK,MARCH MADNESS
1,None,None,Updated: 11/3/21,Updated: 11/3/21,Holidays,Holiday Ad dates ( 1/2 -...,00:00:00,00:00:00,Pre SuperBowl,SuperBowl,#REF!,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00,00:00:00
2,None,None,Updated: 11/3/21,Updated: 11/3/21,Year,2020-12-31 00:00:00,2021-01-07 00:00:00,2021-01-14 00:00:00,2021-01-21 00:00:00,2021-01-28 00:00:00,2021-02-04 00:00:00,2021-02-11 00:00:00,2021-02-18 00:00:00,2021-02-25 00:00:00,2021-03-04 00:00:00,2021-03-11 00:00:00,2021-03-18 00:00:00
3,CSD,12pk / 18pk Cans,12pk Cans,All,2021,6.19,6.19,B2G1,B2G1,B2G1,B2G2,6.19,B2G1,B2G1,6.19,6.19,B2G1
4,CSD,12pk / 18pk Cans,None,None,2020,5.99,5.99,B2G1,B2G1,B2G2,5.99,5.99,B2G1,B2G1,B2G1,5.99,5.99

In [2]:
set(["BB"])

{'BB'}

In [3]:
match_string = "BB"
set(match_string.split(", "))

{'BB'}

Modifying query Expander

In [3]:
import pickle
from langchain_core.prompts import PromptTemplate

query_generalized_template = """
    <|begin_of_text|><|start_header_id|>system<|end_header_id|>
    You are an AI assistant expert specializing in understanding of the {source_type} data and {source_desc}, particularly for a CPG (Consumer Packaged Goods) company and you will be provided with a set of definitions for some {source_type} terms and your task is to use your immense knowledge and these set of definitions to expand the input by adding a clear and concise context around the {source_type} related term mentioned in the input to improve retrieval in a RAG system.
    |eot_id|><|start_header_id|>user<|end_header_id|>
    It's not necessary to use the definition given here. If you do not find any match for the input in the definition set then use your knowledge to create the final definition.
    Make sure that context is concise and to the point and is not more than 20 words.

    Definitions for some {source_type} terms: {definitions}
    Input: {original_query}

    Do not write an introduction, summary or explanation. Just provide the final context-enriched input.
    Note: DO not include statements such as "in the context of the {source_type} data for a Consumer Packaged Goods (CPG) company".
    <|eot_id|><|start_header_id|>assistant<|end_header_id|>"""



with open("/home/ec2-user/Pepsico_Hackathon/Pepsico_Main_Hackathon/Pepsico_demo_new_gen_mapping_approach/mapping_assistant/query_expander_context.pkl", "rb") as file:

    definition_set = pickle.load(file)

query_expander_prompt = PromptTemplate(
    input_variables=["original_query"],
    partial_variables={"definitions": definition_set,"source_type":"PPA","source_desc": "promotion and financial data"},
    template=query_generalized_template
)
print(query_expander_prompt)

input_variables=['original_query'] partial_variables={'definitions': [{'COGS/unit': {'definition': "The main parameter mentioned is Cost of Goods Sold (COGS). In the context of a CPG company's PPA data, COGS represents the direct costs incurred to produce a product, including labor, materials, and overhead, which is crucial for determining product profitability and pricing strategy. This data point is essential for financial analysis and decision-making, as it directly impacts the company's bottom line.\n\nCost of Goods Sold.  All direct costs needed to produce a product for sale.", 'alternative names': ['COGS/unit']}}, {'SCAN': {'definition': "The main parameter mentioned is the allowance amount approved by the business, specifically the BB_DSCNT_AMT (Bill Back Discount Amount) paid by PepsiCo to the retailer when a promotion is scanned. This data point is crucial in tracking the financial transactions between PepsiCo and its retailers, enabling accurate reimbursement for promotional activities. In the context of PPA mapping, this data helps to reconcile the promotional spend with the actual sales data, ensuring that PepsiCo's trade promotion strategies are effectively executed and measured.\n\nThis is the allowance amount approved by the business paid by PepsiCo to the retailer when a promotion is Scanned. The retailer sends an invoice back to PepsiCo as dues to be paid by PepsiCo for only the count of products which triggered the promotion conditions. ", 'alternative names': ['Coupon']}}, {'EDLP Trade': {'definition': 'The main parameter mentioned in the explanation is EDLP (Everyday Low Price) Trade, a pricing strategy in the CPG industry where a flat discount is offered to certain products, deducted directly from the invoice, unaffected by promotions. This data point is crucial in understanding the pricing architecture of the company, as it influences the final cost of products to customers. In the context of PPA mapping, this data helps in accurately calculating the net sales and revenue, enabling better financial analysis and decision-making.\n\nDefinition - EDLP is a flat discount given to certain PPGs, off invoice regardless of any promotions ', 'alternative names': []}}, {'PA \nPromo': {'definition': 'The main parameter mentioned in the explanation is Promotional Allowance (PA), a type of price reduction offered to retailers as an incentive to display and feature specific Frito-Lay items. In the context of PPA mapping, PA is a key component of the Net Cost Sheet, derived from Off Invoice (OI) discounts, which are applied to all units loaded, regardless of scanning. This data point is crucial for accurately calculating the net cost of goods and understanding the financial impact of promotional activities on sales and revenue.\n\nPromotional allowance.  Price reductions that Customers(retailers) sometimes receive as incentives to display and feature specific Frito-Lay items.  PA is derived from OI (off invoice) on the Net Cost Sheet.  Off invoice (OI) is the discount given off invoice.  OI is received on all units loaded in, regardless of whether they scanned or not.', 'alternative names': ['Retro / Unit']}}, {'Promo Price': {'definition': 'The main parameter mentioned in the explanation is the "promoted price". In the context of CPG PPA data, the promoted price refers to the temporary discounted price offered to customers during a promotional period, which is a key pricing strategy to drive sales and increase market share. This data point is crucial for analyzing the effectiveness of promotional campaigns and informing future pricing decisions.\n\npromoted price', 'alternative names': ['Deal', 'Promotion', 'Feature_Price']}}, {'Promo Price per unit': {'definition': 'The main parameter mentioned in the explanation is the "Promo Price per unit", which is a crucial metric in the CPG industry for calculating the price of a single unit during promotional periods. This data point is essential for analyzing the effectiveness of promotions and understanding the revenue impact on the business. In the context of PPA mapping, this field is used to calculate the promoted price of a single unit, enabling accurate revenue management and pricing strategy optimization.\n\nPromo price / promo qty - promoted price of a single unit', 'alternative names': ['Feature_Price', 'Retail', 'ISP - Base/ Deal']}}, {'Promo Qty': {'definition': 'The main parameter mentioned in the explanation is the quantity required to purchase in order to be eligible for a promotion. In the context of CPG PPA data, this refers to the minimum quantity of a product that a customer must buy to qualify for a promotional offer, such as a discount or buy-one-get-one-free deal. This data point is crucial for tracking and analyzing the effectiveness of promotional campaigns and optimizing pricing strategies.\n\nQuantity to purchase to get a promotion', 'alternative names': ['Deal', 'Promotion', 'Event']}}, {'Mechanic Flag': {'definition': "The main parameter mentioned in the explanation is the type of promotion. This data point, 'MCHNC_TYP_NM', is crucial in the PPA mapping as it helps categorize promotions into distinct types, such as price-based, buy-one-get-one-free, or coupon-based offers, enabling CPG companies to analyze and optimize their promotional strategies effectively.\n\nDenotes the type of promotion (ex. price, must buy, coupon, etc.)", 'alternative names': []}}, {'SDV': {'definition': "This data pertains to the 'Importance' of a tactic in driving sales, specifically measuring the expected percentage of units purchased due to the tactic. The 'SDV_COST_AMT' column is directly pulled from the 'SDV' source column, indicating a key metric for evaluating the tactic's effectiveness. In the context of CPG PPA, this data likely informs pricing and promotion strategies to maximize sales volume and revenue.\n\nExpected percentage of units which are purchased due to the tactic.\n", 'alternative names': []}}, {'start date': {'definition': 'The main parameter mentioned in the explanation is the "effective start date of financials". This data point is crucial in the PPA mapping document as it determines the commencement date of promotional or base pricing for a specific product, influencing revenue calculations and financial reporting. In the context of CPG companies, this date is essential for tracking pricing changes, managing trade promotions, and analyzing sales performance.\n\neffective start date of financials related to promoted/base record', 'alternative names': ['From Period file of the corresponding retailers']}}, {'end date': {'definition': 'The main parameter mentioned in the explanation is the "effective end date of financials". This data point is crucial in the PPA mapping document as it determines the end date of promotional or base pricing for a specific product, influencing financial calculations and analysis. In the context of CPG companies, this date is essential for tracking pricing strategies and their impact on sales and revenue.\n\neffective end date of financials related to promoted/base record', 'alternative names': ['From Period file of the corresponding retailers']}}, {'Promo type': {'definition': 'The main parameter mentioned in the explanation is the "Promotion or base indicator". This data point is crucial in distinguishing between promotional and non-promotional pricing strategies, enabling CPG companies to analyze the effectiveness of their pricing tactics and make informed decisions. In the context of PPA, this field helps to categorize prices as either regular/base prices or promotional prices, which is essential for accurate price analysis and optimization.\n\nPromotion or base indicator', 'alternative names': ['price_type']}}, {'Final PPG Name': {'definition': 'The main parameter mentioned in the explanation is PPG (Promo Product Group), which represents the grain of product at which promotions are run. In the context of PPA mapping, PPG is a critical attribute that helps in identifying the specific product configuration (Brand & Size) eligible for promotions. This data point is essential for accurately mapping promotional activities to the corresponding product groups, enabling effective sales and revenue tracking.\n\nPPG is promo product group. This is grain of product at which promotions are run. Concat Brand & Size to get a PPG', 'alternative names': []}}, {'net revenue per unit': {'definition': 'The main parameter mentioned in the explanation is the Net Revenue Per Unit Amount (NRPU amt). This metric represents the amount of money PepsiCo receives from a retailer for one unit of product, calculated by subtracting various trade deductions (scan, bb, PA, EDLP Trade, and Merch) from the Standard Distribution Value (SDV). In the context of PPA mapping, this data point is crucial for understanding the revenue generated by each product unit, enabling accurate financial analysis and decision-making.\n\nThe amount of money PepsiCo receives from retailer for one unit of product.\n\nNRPU amt = SDV - (scan + bb + PA + EDLP Trade + Merch)', 'alternative names': ['Straight Net Cost', 'Dead Net Price / NR']}}, {'RSP': {'definition': 'The main parameter mentioned is the Suggested Retail Price (SRP), which is a crucial pricing strategy in the CPG industry. In the context of PPA mapping, SRP_COST_AMT is a key data point that helps PepsiCo track and analyze the recommended retail prices of their products across different markets and retailers. This data is essential for sales and revenue forecasting, as well as for monitoring price compliance and competitiveness in the market.\n\nSuggested Retail Price.  Denotes the price PepsiCo recommends retailers set for their product', 'alternative names': ['SRP', 'White Tag', 'White Price', 'EDV']}}, {'retailer margin ': {'definition': 'The main parameter mentioned in the explanation is the Retailer Margin, which represents the amount earned by the retailer per unit of quantity sold. In the context of PPA mapping, this data point is crucial for calculating the profitability of a product at the retail level, taking into account various trade promotions and discounts. By understanding the retailer margin, CPG companies can optimize their pricing strategies and trade spend to maximize returns.\n\nRetailer margin amount per unit of quantity sold.\n\nRetailer Margin = Promo price per unit – (SDV - (scan + bb + PA + EDLP Trade + Merch))', 'alternative names': ['TM $']}}, {'Open buy': {'definition': 'The main parameter mentioned is the "Open Buy amount", which refers to the cost a customer pays for not meeting the required purchase quantity for a promotion. In the context of PPA mapping for CPG companies, this data point is crucial for calculating promotional costs and understanding pricing strategies, particularly in markets like FLNA Kroger where the Open Buy amount may not align with the Everyday Low Price (EDLP) or Suggested Retail Price (SRP). This data helps in accurately modeling promotional scenarios and analyzing pricing dynamics.\n\nCost the customer pays if they do not purchase the required quantity to redeem the promotion. For FLNA Kroger, unlike other Markets, the Open Buy amount is not necessarily the EDLP/SRP. It may be a discounted price still. ', 'alternative names': ['Open Buy Price']}}, {'merch': {'definition': 'The main parameter mentioned in the explanation is "Merch", which represents a discount given at a fixed rate payment based on the invoice price. In the context of the PPA mapping document, Merch is a key component of the pricing architecture for CPG companies, allowing them to apply discounts at the PPG (Product Group) level, independent of promotions. This discount is calculated as a percentage of the difference between the Standard Discount Value (SDV) and the sum of scan, bb, PA, and EDLP values, with the percentage varying by banner.\n\nDefinition - Merch is a discount given at a fixed rate payment based on the invoice price applied at the PPG level and off invoice regardless of any promotions\n\nMerch = (SDV - (scan + bb + PA + EDLP)) * 18.125% (Sobeys All banners) \n\nMerch = (SDV - (scan + bb + PA + EDLP)) * X% (BU Provides the % for each Banner in the Input files. (Metro All banners) ', 'alternative names': []}}], 'source_type': 'PPA', 'source_desc': 'promotion and financial data'} template='\n    <|begin_of_text|><|start_header_id|>system<|end_header_id|>\n    You are an AI assistant expert specializing in understanding of the {source_type} data and {source_desc}, particularly for a CPG (Consumer Packaged Goods) company and you will be provided with a set of definitions for some {source_type} terms and your task is to use your immense knowledge and these set of definitions to expand the input by adding a clear and concise context around the {source_type} related term mentioned in the input to improve retrieval in a RAG system.\n    |eot_id|><|start_header_id|>user<|end_header_id|>\n    It\'s not necessary to use the definition given here. If you do not find any match for the input in the definition set then use your knowledge to create the final definition.\n    Make sure that context is concise and to the point and is not more than 20 words.\n\n    Definitions for some {source_type} terms: {definitions}\n    Input: {original_query}\n\n    Do not write an introduction, summary or explanation. Just provide the final context-enriched input.\n    Note: DO not include statements such as "in the context of the {source_type} data for a Consumer Packaged Goods (CPG) company".\n    <|eot_id|><|start_header_id|>assistant<|end_header_id|>'

In [5]:
query_expander_prompt.pretty_print()

    <|begin_of_text|><|start_header_id|>system<|end_header_id|>
    You are an AI assistant expert specializing in understanding of the PPA data and promotion and financial data, particularly for a CPG (Consumer Packaged Goods) company and you will be provided with a set of definitions for some PPA terms and your task is to use your immense knowledge and these set of definitions to expand the input by adding a clear and concise context around the PPA related term mentioned in the input to improve retrieval in a RAG system.
    |eot_id|><|start_header_id|>user<|end_header_id|>
    It's not necessary to use the definition given here. If you do not find any match for the input in the definition set then use your knowledge to create the final definition.
    Make sure that context is concise and to the point and is not more than 20 words.

    Definitions for some PPA terms: [{'COGS/unit': {'definition': "The main parameter mentioned is Cost of Goods Sold (COGS). In the context of a CPG company's PPA data, COGS represents the direct costs incurred to produce a product, including labor, materials, and overhead, which is crucial for determining product profitability and pricing strategy. This data point is essential for financial analysis and decision-making, as it directly impacts the company's bottom line.\n\nCost of Goods Sold.  All direct costs needed to produce a product for sale.", 'alternative names': ['COGS/unit']}}, {'SCAN': {'definition': "The main parameter mentioned is the allowance amount approved by the business, specifically the BB_DSCNT_AMT (Bill Back Discount Amount) paid by PepsiCo to the retailer when a promotion is scanned. This data point is crucial in tracking the financial transactions between PepsiCo and its retailers, enabling accurate reimbursement for promotional activities. In the context of PPA mapping, this data helps to reconcile the promotional spend with the actual sales data, ensuring that PepsiCo's trade promotion strategies are effectively executed and measured.\n\nThis is the allowance amount approved by the business paid by PepsiCo to the retailer when a promotion is Scanned. The retailer sends an invoice back to PepsiCo as dues to be paid by PepsiCo for only the count of products which triggered the promotion conditions. ", 'alternative names': ['Coupon']}}, {'EDLP Trade': {'definition': 'The main parameter mentioned in the explanation is EDLP (Everyday Low Price) Trade, a pricing strategy in the CPG industry where a flat discount is offered to certain products, deducted directly from the invoice, unaffected by promotions. This data point is crucial in understanding the pricing architecture of the company, as it influences the final cost of products to customers. In the context of PPA mapping, this data helps in accurately calculating the net sales and revenue, enabling better financial analysis and decision-making.\n\nDefinition - EDLP is a flat discount given to certain PPGs, off invoice regardless of any promotions ', 'alternative names': []}}, {'PA \nPromo': {'definition': 'The main parameter mentioned in the explanation is Promotional Allowance (PA), a type of price reduction offered to retailers as an incentive to display and feature specific Frito-Lay items. In the context of PPA mapping, PA is a key component of the Net Cost Sheet, derived from Off Invoice (OI) discounts, which are applied to all units loaded, regardless of scanning. This data point is crucial for accurately calculating the net cost of goods and understanding the financial impact of promotional activities on sales and revenue.\n\nPromotional allowance.  Price reductions that Customers(retailers) sometimes receive as incentives to display and feature specific Frito-Lay items.  PA is derived from OI (off invoice) on the Net Cost Sheet.  Off invoice (OI) is the discount given off invoice.  OI is received on all units loaded in, regardless of whether they scanned or not.', 'alternative names': ['Retro / Unit']}}, {'Promo Price': {'definition': 'The main parameter mentioned in the explanation is the "promoted price". In the context of CPG PPA data, the promoted price refers to the temporary discounted price offered to customers during a promotional period, which is a key pricing strategy to drive sales and increase market share. This data point is crucial for analyzing the effectiveness of promotional campaigns and informing future pricing decisions.\n\npromoted price', 'alternative names': ['Deal', 'Promotion', 'Feature_Price']}}, {'Promo Price per unit': {'definition': 'The main parameter mentioned in the explanation is the "Promo Price per unit", which is a crucial metric in the CPG industry for calculating the price of a single unit during promotional periods. This data point is essential for analyzing the effectiveness of promotions and understanding the revenue impact on the business. In the context of PPA mapping, this field is used to calculate the promoted price of a single unit, enabling accurate revenue management and pricing strategy optimization.\n\nPromo price / promo qty - promoted price of a single unit', 'alternative names': ['Feature_Price', 'Retail', 'ISP - Base/ Deal']}}, {'Promo Qty': {'definition': 'The main parameter mentioned in the explanation is the quantity required to purchase in order to be eligible for a promotion. In the context of CPG PPA data, this refers to the minimum quantity of a product that a customer must buy to qualify for a promotional offer, such as a discount or buy-one-get-one-free deal. This data point is crucial for tracking and analyzing the effectiveness of promotional campaigns and optimizing pricing strategies.\n\nQuantity to purchase to get a promotion', 'alternative names': ['Deal', 'Promotion', 'Event']}}, {'Mechanic Flag': {'definition': "The main parameter mentioned in the explanation is the type of promotion. This data point, 'MCHNC_TYP_NM', is crucial in the PPA mapping as it helps categorize promotions into distinct types, such as price-based, buy-one-get-one-free, or coupon-based offers, enabling CPG companies to analyze and optimize their promotional strategies effectively.\n\nDenotes the type of promotion (ex. price, must buy, coupon, etc.)", 'alternative names': []}}, {'SDV': {'definition': "This data pertains to the 'Importance' of a tactic in driving sales, specifically measuring the expected percentage of units purchased due to the tactic. The 'SDV_COST_AMT' column is directly pulled from the 'SDV' source column, indicating a key metric for evaluating the tactic's effectiveness. In the context of CPG PPA, this data likely informs pricing and promotion strategies to maximize sales volume and revenue.\n\nExpected percentage of units which are purchased due to the tactic.\n", 'alternative names': []}}, {'start date': {'definition': 'The main parameter mentioned in the explanation is the "effective start date of financials". This data point is crucial in the PPA mapping document as it determines the commencement date of promotional or base pricing for a specific product, influencing revenue calculations and financial reporting. In the context of CPG companies, this date is essential for tracking pricing changes, managing trade promotions, and analyzing sales performance.\n\neffective start date of financials related to promoted/base record', 'alternative names': ['From Period file of the corresponding retailers']}}, {'end date': {'definition': 'The main parameter mentioned in the explanation is the "effective end date of financials". This data point is crucial in the PPA mapping document as it determines the end date of promotional or base pricing for a specific product, influencing financial calculations and analysis. In the context of CPG companies, this date is essential for tracking pricing strategies and their impact on sales and revenue.\n\neffective end date of financials related to promoted/base record', 'alternative names': ['From Period file of the corresponding retailers']}}, {'Promo type': {'definition': 'The main parameter mentioned in the explanation is the "Promotion or base indicator". This data point is crucial in distinguishing between promotional and non-promotional pricing strategies, enabling CPG companies to analyze the effectiveness of their pricing tactics and make informed decisions. In the context of PPA, this field helps to categorize prices as either regular/base prices or promotional prices, which is essential for accurate price analysis and optimization.\n\nPromotion or base indicator', 'alternative names': ['price_type']}}, {'Final PPG Name': {'definition': 'The main parameter mentioned in the explanation is PPG (Promo Product Group), which represents the grain of product at which promotions are run. In the context of PPA mapping, PPG is a critical attribute that helps in identifying the specific product configuration (Brand & Size) eligible for promotions. This data point is essential for accurately mapping promotional activities to the corresponding product groups, enabling effective sales and revenue tracking.\n\nPPG is promo product group. This is grain of product at which promotions are run. Concat Brand & Size to get a PPG', 'alternative names': []}}, {'net revenue per unit': {'definition': 'The main parameter mentioned in the explanation is the Net Revenue Per Unit Amount (NRPU amt). This metric represents the amount of money PepsiCo receives from a retailer for one unit of product, calculated by subtracting various trade deductions (scan, bb, PA, EDLP Trade, and Merch) from the Standard Distribution Value (SDV). In the context of PPA mapping, this data point is crucial for understanding the revenue generated by each product unit, enabling accurate financial analysis and decision-making.\n\nThe amount of money PepsiCo receives from retailer for one unit of product.\n\nNRPU amt = SDV - (scan + bb + PA + EDLP Trade + Merch)', 'alternative names': ['Straight Net Cost', 'Dead Net Price / NR']}}, {'RSP': {'definition': 'The main parameter mentioned is the Suggested Retail Price (SRP), which is a crucial pricing strategy in the CPG industry. In the context of PPA mapping, SRP_COST_AMT is a key data point that helps PepsiCo track and analyze the recommended retail prices of their products across different markets and retailers. This data is essential for sales and revenue forecasting, as well as for monitoring price compliance and competitiveness in the market.\n\nSuggested Retail Price.  Denotes the price PepsiCo recommends retailers set for their product', 'alternative names': ['SRP', 'White Tag', 'White Price', 'EDV']}}, {'retailer margin ': {'definition': 'The main parameter mentioned in the explanation is the Retailer Margin, which represents the amount earned by the retailer per unit of quantity sold. In the context of PPA mapping, this data point is crucial for calculating the profitability of a product at the retail level, taking into account various trade promotions and discounts. By understanding the retailer margin, CPG companies can optimize their pricing strategies and trade spend to maximize returns.\n\nRetailer margin amount per unit of quantity sold.\n\nRetailer Margin = Promo price per unit – (SDV - (scan + bb + PA + EDLP Trade + Merch))', 'alternative names': ['TM $']}}, {'Open buy': {'definition': 'The main parameter mentioned is the "Open Buy amount", which refers to the cost a customer pays for not meeting the required purchase quantity for a promotion. In the context of PPA mapping for CPG companies, this data point is crucial for calculating promotional costs and understanding pricing strategies, particularly in markets like FLNA Kroger where the Open Buy amount may not align with the Everyday Low Price (EDLP) or Suggested Retail Price (SRP). This data helps in accurately modeling promotional scenarios and analyzing pricing dynamics.\n\nCost the customer pays if they do not purchase the required quantity to redeem the promotion. For FLNA Kroger, unlike other Markets, the Open Buy amount is not necessarily the EDLP/SRP. It may be a discounted price still. ', 'alternative names': ['Open Buy Price']}}, {'merch': {'definition': 'The main parameter mentioned in the explanation is "Merch", which represents a discount given at a fixed rate payment based on the invoice price. In the context of the PPA mapping document, Merch is a key component of the pricing architecture for CPG companies, allowing them to apply discounts at the PPG (Product Group) level, independent of promotions. This discount is calculated as a percentage of the difference between the Standard Discount Value (SDV) and the sum of scan, bb, PA, and EDLP values, with the percentage varying by banner.\n\nDefinition - Merch is a discount given at a fixed rate payment based on the invoice price applied at the PPG level and off invoice regardless of any promotions\n\nMerch = (SDV - (scan + bb + PA + EDLP)) * 18.125% (Sobeys All banners) \n\nMerch = (SDV - (scan + bb + PA + EDLP)) * X% (BU Provides the % for each Banner in the Input files. (Metro All banners) ', 'alternative names': []}}]
    Input: {original_query}

    Do not write an introduction, summary or explanation. Just provide the final context-enriched input.
    Note: DO not include statements such as "in the context of the PPA data for a Consumer Packaged Goods (CPG) company".
    <|eot_id|><|start_header_id|>assistant<|end_header_id|>

In [3]:
import pandas as pd
mosaic_df = pd.read_excel("/home/ec2-user/Pepsico_Hackathon/Pepsico_Main_Hackathon/Pepsico_demo_new_gen_mapping_approach/mapping_assistant/assistant_common/Mosaic-ER Diagram.xlsx",sheet_name="Topline Metadata")
mosaic_df.head()

,Topline Metadata,OPEX Metadata,Topline ER Diagram,OPEX ER Diagram,Relationship,Unnamed: 5,Unnamed: 6
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Dim_Customer,NaN,NaN,NaN,Dim_SalesGeo,NaN,NaN
2,Column,Type,Description,NaN,Column,Type,Description
3,CUST_HASH_CMPST_KEY,Bigint,"Represents the Customer Hash Composite Key, a ...",NaN,SLS_GEO_HASH_CMPST_KEY,Bigint,Represents a unique hashed composite key that ...
4,MU,String,The Business Unit break-down within a Cluster,NaN,SYS_ID,Int,NaN